package cards.tarot;

import cards.tarot.enumerations.BidTarot;
import cards.tarot.enumerations.CardTarot;
import cards.tarot.enumerations.ModeTarot;
import code.util.CustList;
import code.util.EnumList;
import org.junit.Test;

import static org.junit.Assert.assertSame;

public final class GameTarotMisereTest extends CommonGameTarot {
    @Test
    public void tryDiscard1Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        RulesTarot r_ = new RulesTarot();
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.CLUB_QUEEN);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_15);
        curHand_.ajouter(CardTarot.TRUMP_14);
        curHand_.ajouter(CardTarot.TRUMP_13);
        curHand_.ajouter(CardTarot.TRUMP_12);
        curHand_.ajouter(CardTarot.TRUMP_1);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_KING);
        t_.ajouter(CardTarot.HEART_4);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.HEART_QUEEN);
        t_.ajouter(CardTarot.HEART_8);
        t_.ajouter(CardTarot.HEART_7);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_6);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        TarotInfoPliEnCours infoTr_ = gbt_.initInformations();
        assertSame(CardTarot.TRUMP_12,gbt_.tryDiscard(infoTr_));
    }
    @Test
    public void tryDiscard2Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        RulesTarot r_ = new RulesTarot();
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.CLUB_QUEEN);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_15);
        curHand_.ajouter(CardTarot.TRUMP_14);
        curHand_.ajouter(CardTarot.TRUMP_13);
        curHand_.ajouter(CardTarot.TRUMP_12);
        curHand_.ajouter(CardTarot.TRUMP_1);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_KING);
        t_.ajouter(CardTarot.HEART_4);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.HEART_QUEEN);
        t_.ajouter(CardTarot.HEART_8);
        t_.ajouter(CardTarot.HEART_7);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_6);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        TarotInfoPliEnCours infoTr_ = gbt_.initInformations();
        addSureCard(infoTr_,1,CardTarot.TRUMP_11);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_KING);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_KNIGHT);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_10);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_9);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_8);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_7);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_6);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_5);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_4);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_3);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_2);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_1);
        assertSame(CardTarot.CLUB_QUEEN,gbt_.tryDiscard(infoTr_));
    }
    @Test
    public void tryDiscard3Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        RulesTarot r_ = new RulesTarot();
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.CLUB_10);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_8);
        curHand_.ajouter(CardTarot.TRUMP_15);
        curHand_.ajouter(CardTarot.TRUMP_14);
        curHand_.ajouter(CardTarot.TRUMP_13);
        curHand_.ajouter(CardTarot.TRUMP_12);
        curHand_.ajouter(CardTarot.TRUMP_1);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_KING);
        t_.ajouter(CardTarot.HEART_4);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.HEART_QUEEN);
        t_.ajouter(CardTarot.HEART_8);
        t_.ajouter(CardTarot.HEART_7);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_6);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        TarotInfoPliEnCours infoTr_ = gbt_.initInformations();
        addSureCard(infoTr_,1,CardTarot.TRUMP_11);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_KING);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_KNIGHT);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_9);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_QUEEN);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_JACK);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_7);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_6);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_5);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_4);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_3);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_2);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_1);
        assertSame(CardTarot.CLUB_8,gbt_.tryDiscard(infoTr_));
    }
    @Test
    public void tryDiscard4Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        RulesTarot r_ = new RulesTarot();
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.CLUB_10);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_8);
        curHand_.ajouter(CardTarot.CLUB_7);
        curHand_.ajouter(CardTarot.CLUB_6);
        curHand_.ajouter(CardTarot.DIAMOND_KNIGHT);
        curHand_.ajouter(CardTarot.DIAMOND_3);
        curHand_.ajouter(CardTarot.DIAMOND_4);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_KING);
        t_.ajouter(CardTarot.HEART_4);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.HEART_QUEEN);
        t_.ajouter(CardTarot.HEART_8);
        t_.ajouter(CardTarot.HEART_7);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_6);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        TarotInfoPliEnCours infoTr_ = gbt_.initInformations();
        assertSame(CardTarot.HEART_10,gbt_.tryDiscard(infoTr_));
    }
    @Test
    public void tryDiscard5Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        RulesTarot r_ = new RulesTarot();
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.CLUB_QUEEN);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_21);
        curHand_.ajouter(CardTarot.TRUMP_14);
        curHand_.ajouter(CardTarot.TRUMP_13);
        curHand_.ajouter(CardTarot.TRUMP_12);
        curHand_.ajouter(CardTarot.TRUMP_1);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_KING);
        t_.ajouter(CardTarot.HEART_4);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.HEART_QUEEN);
        t_.ajouter(CardTarot.HEART_8);
        t_.ajouter(CardTarot.HEART_7);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_6);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        TarotInfoPliEnCours infoTr_ = gbt_.initInformations();
        assertSame(CardTarot.TRUMP_1,gbt_.tryDiscard(infoTr_));
    }
}
