package cards.tarot;

import cards.tarot.enumerations.BidTarot;
import cards.tarot.enumerations.CardTarot;
import cards.tarot.enumerations.DealingTarot;
import cards.tarot.enumerations.ModeTarot;
import code.util.CustList;
import code.util.EnumList;
import org.junit.Test;

public final class GameTarotMisereTest extends CommonGameTarot {
    @Test
    public void tryDiscard1Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        RulesTarot r_ = new RulesTarot();
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.CLUB_QUEEN);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_15);
        curHand_.ajouter(CardTarot.TRUMP_14);
        curHand_.ajouter(CardTarot.TRUMP_13);
        curHand_.ajouter(CardTarot.TRUMP_12);
        curHand_.ajouter(CardTarot.TRUMP_1);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_KING);
        t_.ajouter(CardTarot.HEART_4);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.HEART_QUEEN);
        t_.ajouter(CardTarot.HEART_8);
        t_.ajouter(CardTarot.HEART_7);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_6);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        TarotInfoPliEnCours infoTr_ = gbt_.initInformations();
        assertSame(CardTarot.TRUMP_12,gbt_.tryDiscard(infoTr_));
    }
    @Test
    public void tryDiscard2Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        RulesTarot r_ = new RulesTarot();
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.CLUB_QUEEN);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_15);
        curHand_.ajouter(CardTarot.TRUMP_14);
        curHand_.ajouter(CardTarot.TRUMP_13);
        curHand_.ajouter(CardTarot.TRUMP_12);
        curHand_.ajouter(CardTarot.TRUMP_1);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_KING);
        t_.ajouter(CardTarot.HEART_4);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.HEART_QUEEN);
        t_.ajouter(CardTarot.HEART_8);
        t_.ajouter(CardTarot.HEART_7);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_6);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        TarotInfoPliEnCours infoTr_ = gbt_.initInformations();
        addSureCard(infoTr_,1,CardTarot.TRUMP_11);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_KING);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_KNIGHT);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_10);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_9);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_8);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_7);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_6);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_5);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_4);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_3);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_2);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_1);
        assertSame(CardTarot.CLUB_QUEEN,gbt_.tryDiscard(infoTr_));
    }
    @Test
    public void tryDiscard3Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        RulesTarot r_ = new RulesTarot();
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.CLUB_10);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_8);
        curHand_.ajouter(CardTarot.TRUMP_15);
        curHand_.ajouter(CardTarot.TRUMP_14);
        curHand_.ajouter(CardTarot.TRUMP_13);
        curHand_.ajouter(CardTarot.TRUMP_12);
        curHand_.ajouter(CardTarot.TRUMP_1);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_KING);
        t_.ajouter(CardTarot.HEART_4);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.HEART_QUEEN);
        t_.ajouter(CardTarot.HEART_8);
        t_.ajouter(CardTarot.HEART_7);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_6);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        TarotInfoPliEnCours infoTr_ = gbt_.initInformations();
        addSureCard(infoTr_,1,CardTarot.TRUMP_11);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_KING);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_KNIGHT);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_9);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_QUEEN);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_JACK);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_7);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_6);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_5);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_4);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_3);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_2);
        removePossibleCard(infoTr_, 1, CardTarot.CLUB_1);
        assertSame(CardTarot.CLUB_8,gbt_.tryDiscard(infoTr_));
    }
    @Test
    public void tryDiscard4Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        RulesTarot r_ = new RulesTarot();
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.CLUB_10);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_8);
        curHand_.ajouter(CardTarot.CLUB_7);
        curHand_.ajouter(CardTarot.CLUB_6);
        curHand_.ajouter(CardTarot.DIAMOND_KNIGHT);
        curHand_.ajouter(CardTarot.DIAMOND_3);
        curHand_.ajouter(CardTarot.DIAMOND_4);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_KING);
        t_.ajouter(CardTarot.HEART_4);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.HEART_QUEEN);
        t_.ajouter(CardTarot.HEART_8);
        t_.ajouter(CardTarot.HEART_7);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_6);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        TarotInfoPliEnCours infoTr_ = gbt_.initInformations();
        assertSame(CardTarot.HEART_10,gbt_.tryDiscard(infoTr_));
    }
    @Test
    public void tryDiscard5Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        RulesTarot r_ = new RulesTarot();
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.CLUB_QUEEN);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_21);
        curHand_.ajouter(CardTarot.TRUMP_14);
        curHand_.ajouter(CardTarot.TRUMP_13);
        curHand_.ajouter(CardTarot.TRUMP_12);
        curHand_.ajouter(CardTarot.TRUMP_1);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_KING);
        t_.ajouter(CardTarot.HEART_4);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.HEART_QUEEN);
        t_.ajouter(CardTarot.HEART_8);
        t_.ajouter(CardTarot.HEART_7);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_6);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        TarotInfoPliEnCours infoTr_ = gbt_.initInformations();
        assertSame(CardTarot.TRUMP_1,gbt_.tryDiscard(infoTr_));
    }
    @Test
    public void entame1Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        RulesTarot r_ = new RulesTarot();
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.CLUB_QUEEN);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_21);
        curHand_.ajouter(CardTarot.TRUMP_14);
        curHand_.ajouter(CardTarot.TRUMP_13);
        curHand_.ajouter(CardTarot.TRUMP_12);
        curHand_.ajouter(CardTarot.TRUMP_1);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_KING);
        t_.ajouter(CardTarot.HEART_4);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.HEART_QUEEN);
        t_.ajouter(CardTarot.HEART_8);
        t_.ajouter(CardTarot.HEART_7);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_6);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.TRUMP_1,gbt_.entame());
    }
    @Test
    public void entame2Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        RulesTarot r_ = new RulesTarot();
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.CLUB_QUEEN);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_21);
        curHand_.ajouter(CardTarot.TRUMP_14);
        curHand_.ajouter(CardTarot.TRUMP_13);
        curHand_.ajouter(CardTarot.TRUMP_12);
        curHand_.ajouter(CardTarot.TRUMP_2);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_KING);
        t_.ajouter(CardTarot.HEART_4);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.HEART_QUEEN);
        t_.ajouter(CardTarot.HEART_8);
        t_.ajouter(CardTarot.HEART_7);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_6);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.TRUMP_2,gbt_.entame());
    }
    @Test
    public void entame3Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        RulesTarot r_ = new RulesTarot();
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.CLUB_QUEEN);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_15);
        curHand_.ajouter(CardTarot.TRUMP_14);
        curHand_.ajouter(CardTarot.TRUMP_13);
        curHand_.ajouter(CardTarot.TRUMP_12);
        curHand_.ajouter(CardTarot.TRUMP_2);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_KING);
        t_.ajouter(CardTarot.HEART_4);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.HEART_QUEEN);
        t_.ajouter(CardTarot.HEART_8);
        t_.ajouter(CardTarot.HEART_7);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_6);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.TRUMP_12,gbt_.entame());
    }
    @Test
    public void entame4Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        RulesTarot r_ = new RulesTarot();
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.CLUB_QUEEN);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_21);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.SPADE_5);
        curHand_.ajouter(CardTarot.SPADE_4);
        curHand_.ajouter(CardTarot.SPADE_3);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_KING);
        t_.ajouter(CardTarot.HEART_4);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.HEART_QUEEN);
        t_.ajouter(CardTarot.HEART_8);
        t_.ajouter(CardTarot.HEART_7);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_6);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.TRUMP_21,gbt_.entame());
    }
    @Test
    public void entame5Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        RulesTarot r_ = new RulesTarot();
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.CLUB_QUEEN);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_20);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.SPADE_5);
        curHand_.ajouter(CardTarot.SPADE_4);
        curHand_.ajouter(CardTarot.SPADE_3);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_KING);
        t_.ajouter(CardTarot.HEART_4);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.HEART_QUEEN);
        t_.ajouter(CardTarot.HEART_8);
        t_.ajouter(CardTarot.HEART_7);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_6);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.TRUMP_20,gbt_.entame());
    }
    @Test
    public void entame6Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        RulesTarot r_ = new RulesTarot();
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.DIAMOND_JACK);
        byte d_ = 3;
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.TRUMP_21);
        t_.ajouter(CardTarot.TRUMP_2);
        t_.ajouter(CardTarot.TRUMP_3);
        t_.ajouter(CardTarot.TRUMP_4);
        t_.ajouter(CardTarot.TRUMP_5);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.TRUMP_6);
        t_.ajouter(CardTarot.TRUMP_20);
        t_.ajouter(CardTarot.TRUMP_7);
        t_.ajouter(CardTarot.TRUMP_8);
        t_.ajouter(CardTarot.TRUMP_9);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.TRUMP_19);
        t_.ajouter(CardTarot.TRUMP_10);
        t_.ajouter(CardTarot.TRUMP_11);
        t_.ajouter(CardTarot.TRUMP_12);
        t_.ajouter(CardTarot.TRUMP_13);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.TRUMP_18);
        t_.ajouter(CardTarot.TRUMP_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.SPADE_4);
        t_.ajouter(CardTarot.SPADE_5);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.TRUMP_17);
        t_.ajouter(CardTarot.SPADE_6);
        t_.ajouter(CardTarot.SPADE_7);
        t_.ajouter(CardTarot.SPADE_8);
        t_.ajouter(CardTarot.SPADE_9);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.TRUMP_16);
        t_.ajouter(CardTarot.SPADE_3);
        t_.ajouter(CardTarot.SPADE_KNIGHT);
        t_.ajouter(CardTarot.SPADE_JACK);
        t_.ajouter(CardTarot.SPADE_2);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.TRUMP_15);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_4);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.TRUMP_14);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_6);
        t_.ajouter(CardTarot.HEART_7);
        t_.ajouter(CardTarot.HEART_8);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.HEART_KING);
        t_.ajouter(CardTarot.HEART_9);
        t_.ajouter(CardTarot.HEART_10);
        t_.ajouter(CardTarot.HEART_JACK);
        t_.ajouter(CardTarot.HEART_KNIGHT);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.HEART_QUEEN);
        t_.ajouter(CardTarot.CLUB_4);
        t_.ajouter(CardTarot.CLUB_5);
        t_.ajouter(CardTarot.CLUB_6);
        t_.ajouter(CardTarot.CLUB_7);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.SPADE_KING);
        t_.ajouter(CardTarot.CLUB_8);
        t_.ajouter(CardTarot.CLUB_9);
        t_.ajouter(CardTarot.CLUB_10);
        t_.ajouter(CardTarot.CLUB_JACK);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.DIAMOND_KING);
        t_.ajouter(CardTarot.DIAMOND_1);
        t_.ajouter(CardTarot.DIAMOND_2);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_4);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.DIAMOND_QUEEN);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_6);
        t_.ajouter(CardTarot.DIAMOND_7);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.DIAMOND_KNIGHT);
        t_.ajouter(CardTarot.DIAMOND_9);
        t_.ajouter(CardTarot.DIAMOND_10);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_2);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.DIAMOND_JACK, gbt_.entame());
    }
    @Test
    public void enCours1Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.HEART_KING);
        curHand_.ajouter(CardTarot.HEART_JACK);
        curHand_.ajouter(CardTarot.HEART_5);
        curHand_.ajouter(CardTarot.CLUB_2);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_2);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        pr_.ajouter(CardTarot.HEART_1);
        pr_.ajouter(CardTarot.HEART_2);
        pr_.ajouter(CardTarot.HEART_4);
        pr_.ajouter(CardTarot.TRUMP_15);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.HEART_KING,gbt_.enCours());
    }
    @Test
    public void enCours2Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.HEART_KING);
        curHand_.ajouter(CardTarot.HEART_JACK);
        curHand_.ajouter(CardTarot.HEART_5);
        curHand_.ajouter(CardTarot.CLUB_2);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_2);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        pr_.ajouter(CardTarot.HEART_1);
        pr_.ajouter(CardTarot.TRUMP_21);
        pr_.ajouter(CardTarot.HEART_2);
        pr_.ajouter(CardTarot.HEART_4);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.HEART_5,gbt_.enCours());
    }
    @Test
    public void enCours3Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.HEART_8);
        curHand_.ajouter(CardTarot.HEART_5);
        curHand_.ajouter(CardTarot.CLUB_2);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_2);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        pr_.ajouter(CardTarot.HEART_1);
        pr_.ajouter(CardTarot.HEART_KING);
        pr_.ajouter(CardTarot.HEART_2);
        pr_.ajouter(CardTarot.HEART_4);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.HEART_10,gbt_.enCours());
    }
    @Test
    public void enCours4Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.HEART_8);
        curHand_.ajouter(CardTarot.HEART_5);
        curHand_.ajouter(CardTarot.CLUB_2);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_2);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        pr_.ajouter(CardTarot.HEART_1);
        pr_.ajouter(CardTarot.HEART_3);
        pr_.ajouter(CardTarot.HEART_2);
        pr_.ajouter(CardTarot.HEART_4);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.HEART_5,gbt_.enCours());
    }
    @Test
    public void enCours5Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.TRUMP_1);
        curHand_.ajouter(CardTarot.TRUMP_15);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_2);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.TRUMP_14);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.HEART_6);
        pr_.ajouter(CardTarot.HEART_7);
        pr_.ajouter(CardTarot.HEART_8);
        pr_.ajouter(CardTarot.HEART_9);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.TRUMP_1,gbt_.enCours());
    }
    @Test
    public void enCours6Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.TRUMP_3);
        curHand_.ajouter(CardTarot.TRUMP_15);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_2);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.TRUMP_14);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.HEART_6);
        pr_.ajouter(CardTarot.HEART_7);
        pr_.ajouter(CardTarot.HEART_8);
        pr_.ajouter(CardTarot.HEART_9);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.TRUMP_15,gbt_.enCours());
    }
    @Test
    public void enCours7Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.TRUMP_3);
        curHand_.ajouter(CardTarot.TRUMP_15);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_2);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_KING);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.HEART_6);
        pr_.ajouter(CardTarot.HEART_7);
        pr_.ajouter(CardTarot.HEART_8);
        pr_.ajouter(CardTarot.HEART_9);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.TRUMP_15,gbt_.enCours());
    }
    @Test
    public void enCours8Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.TRUMP_1);
        curHand_.ajouter(CardTarot.TRUMP_15);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_2);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_KING);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.HEART_6);
        pr_.ajouter(CardTarot.HEART_7);
        pr_.ajouter(CardTarot.HEART_8);
        pr_.ajouter(CardTarot.TRUMP_16);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.TRUMP_1,gbt_.enCours());
    }
    @Test
    public void enCours9Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.TRUMP_3);
        curHand_.ajouter(CardTarot.TRUMP_15);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_2);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_KING);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.HEART_6);
        pr_.ajouter(CardTarot.HEART_7);
        pr_.ajouter(CardTarot.HEART_8);
        pr_.ajouter(CardTarot.TRUMP_16);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.TRUMP_15,gbt_.enCours());
    }
    @Test
    public void enCours10Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.TRUMP_1);
        curHand_.ajouter(CardTarot.TRUMP_15);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_2);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_KING);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.HEART_6);
        pr_.ajouter(CardTarot.TRUMP_21);
        pr_.ajouter(CardTarot.HEART_7);
        pr_.ajouter(CardTarot.HEART_8);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.TRUMP_15,gbt_.enCours());
    }
    @Test
    public void enCours11Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.TRUMP_1);
        curHand_.ajouter(CardTarot.TRUMP_15);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_2);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_KING);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.TRUMP_4);
        pr_.ajouter(CardTarot.TRUMP_21);
        pr_.ajouter(CardTarot.HEART_7);
        pr_.ajouter(CardTarot.HEART_8);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.TRUMP_15,gbt_.enCours());
    }
    @Test
    public void enCours12Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.TRUMP_1);
        curHand_.ajouter(CardTarot.TRUMP_15);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_2);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_KING);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.TRUMP_4);
        pr_.ajouter(CardTarot.HEART_7);
        pr_.ajouter(CardTarot.HEART_8);
        pr_.ajouter(CardTarot.TRUMP_21);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.TRUMP_1,gbt_.enCours());
    }
    @Test
    public void enCours13Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.TRUMP_5);
        curHand_.ajouter(CardTarot.TRUMP_15);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.TRUMP_2);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_KING);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.TRUMP_4);
        pr_.ajouter(CardTarot.HEART_7);
        pr_.ajouter(CardTarot.HEART_8);
        pr_.ajouter(CardTarot.TRUMP_21);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.TRUMP_15,gbt_.enCours());
    }
    @Test
    public void enCours14Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.HEART_KNIGHT);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.HEART_8);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_KING);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.TRUMP_4);
        pr_.ajouter(CardTarot.TRUMP_21);
        pr_.ajouter(CardTarot.TRUMP_15);
        pr_.ajouter(CardTarot.TRUMP_1);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.SPADE_7,gbt_.enCours());
    }
    @Test
    public void enCours15Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.DIAMOND_1);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.HEART_KNIGHT);
        curHand_.ajouter(CardTarot.SPADE_JACK);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.HEART_9);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_KING);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.TRUMP_4);
        pr_.ajouter(CardTarot.TRUMP_21);
        pr_.ajouter(CardTarot.TRUMP_15);
        pr_.ajouter(CardTarot.TRUMP_1);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.HEART_9,gbt_.enCours());
    }
    @Test
    public void enCours16Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_KNIGHT);
        curHand_.ajouter(CardTarot.DIAMOND_KNIGHT);
        curHand_.ajouter(CardTarot.SPADE_KING);
        curHand_.ajouter(CardTarot.HEART_KNIGHT);
        curHand_.ajouter(CardTarot.SPADE_JACK);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.HEART_QUEEN);
        curHand_.ajouter(CardTarot.EXCUSE);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_KING);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.TRUMP_4);
        pr_.ajouter(CardTarot.TRUMP_21);
        pr_.ajouter(CardTarot.TRUMP_15);
        pr_.ajouter(CardTarot.TRUMP_1);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.CLUB_JACK,gbt_.enCours());
    }
    @Test
    public void enCours21Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_KNIGHT);
        curHand_.ajouter(CardTarot.DIAMOND_KNIGHT);
        curHand_.ajouter(CardTarot.SPADE_KING);
        curHand_.ajouter(CardTarot.HEART_KNIGHT);
        curHand_.ajouter(CardTarot.SPADE_JACK);
        curHand_.ajouter(CardTarot.CLUB_5);
        curHand_.ajouter(CardTarot.HEART_QUEEN);
        curHand_.ajouter(CardTarot.EXCUSE);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.DIAMOND_QUEEN);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_KING);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.TRUMP_4);
        pr_.ajouter(CardTarot.TRUMP_15);
        pr_.ajouter(CardTarot.TRUMP_1);
        pr_.ajouter(CardTarot.TRUMP_21);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.CLUB_5,gbt_.enCours());
    }
    @Test
    public void enCours22Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.SPADE_2);
        curHand_.ajouter(CardTarot.CLUB_10);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.HEART_KNIGHT);
        curHand_.ajouter(CardTarot.CLUB_6);
        curHand_.ajouter(CardTarot.CLUB_KNIGHT);
        curHand_.ajouter(CardTarot.HEART_QUEEN);
        curHand_.ajouter(CardTarot.EXCUSE);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.CLUB_7);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_KING);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.TRUMP_4);
        pr_.ajouter(CardTarot.TRUMP_15);
        pr_.ajouter(CardTarot.TRUMP_1);
        pr_.ajouter(CardTarot.TRUMP_21);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.DIAMOND_KING,gbt_.enCours());
    }
    @Test
    public void enCours23Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.DIAMOND_4);
        curHand_.ajouter(CardTarot.CLUB_10);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.CLUB_6);
        curHand_.ajouter(CardTarot.CLUB_KNIGHT);
        curHand_.ajouter(CardTarot.HEART_9);
        curHand_.ajouter(CardTarot.EXCUSE);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.CLUB_7);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_KING);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.TRUMP_4);
        pr_.ajouter(CardTarot.TRUMP_15);
        pr_.ajouter(CardTarot.TRUMP_1);
        pr_.ajouter(CardTarot.TRUMP_21);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.DIAMOND_KING,gbt_.enCours());
    }
    @Test
    public void enCours24Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.DIAMOND_4);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_JACK);
        curHand_.ajouter(CardTarot.SPADE_8);
        curHand_.ajouter(CardTarot.CLUB_6);
        curHand_.ajouter(CardTarot.CLUB_KNIGHT);
        curHand_.ajouter(CardTarot.HEART_9);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.DIAMOND_KING);
        curHand_.ajouter(CardTarot.CLUB_7);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_KING);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.TRUMP_4);
        pr_.ajouter(CardTarot.TRUMP_15);
        pr_.ajouter(CardTarot.TRUMP_1);
        pr_.ajouter(CardTarot.TRUMP_21);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.DIAMOND_KING,gbt_.enCours());
    }
    @Test
    public void enCours25Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.DIAMOND_4);
        curHand_.ajouter(CardTarot.CLUB_10);
        curHand_.ajouter(CardTarot.CLUB_8);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.CLUB_6);
        curHand_.ajouter(CardTarot.CLUB_7);
        curHand_.ajouter(CardTarot.HEART_9);
        curHand_.ajouter(CardTarot.EXCUSE);
        curHand_.ajouter(CardTarot.DIAMOND_7);
        curHand_.ajouter(CardTarot.CLUB_5);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_KING);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.TRUMP_4);
        pr_.ajouter(CardTarot.TRUMP_15);
        pr_.ajouter(CardTarot.TRUMP_1);
        pr_.ajouter(CardTarot.TRUMP_21);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.DIAMOND_4,gbt_.enCours());
    }
    @Test
    public void enCours26Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.DIAMOND_4);
        curHand_.ajouter(CardTarot.DIAMOND_6);
        curHand_.ajouter(CardTarot.SPADE_8);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.HEART_9);
        curHand_.ajouter(CardTarot.EXCUSE);
        curHand_.ajouter(CardTarot.DIAMOND_7);
        curHand_.ajouter(CardTarot.SPADE_5);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_KING);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.CLUB_10);
        pr_.ajouter(CardTarot.TRUMP_21);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.HEART_9,gbt_.enCours());
    }
    @Test
    public void enCours27Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.DIAMOND_4);
        curHand_.ajouter(CardTarot.DIAMOND_6);
        curHand_.ajouter(CardTarot.SPADE_8);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_9);
        curHand_.ajouter(CardTarot.HEART_9);
        curHand_.ajouter(CardTarot.DIAMOND_7);
        curHand_.ajouter(CardTarot.SPADE_5);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_KING);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.CLUB_10);
        pr_.ajouter(CardTarot.TRUMP_21);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.CLUB_9,gbt_.enCours());
    }
    @Test
    public void enCours28Test() {
        HandTarot last_ = new HandTarot();
        last_.ajouter(CardTarot.SPADE_QUEEN);
        last_.ajouter(CardTarot.SPADE_10);
        last_.ajouter(CardTarot.SPADE_1);
        last_.ajouter(CardTarot.DIAMOND_3);
        last_.ajouter(CardTarot.DIAMOND_5);
        last_.ajouter(CardTarot.DIAMOND_8);
        RulesTarot r_ = new RulesTarot((byte) 6);
        r_.setDealing(DealingTarot.DEAL_2_VS_4_WITHOUT_CALL);
        r_.setMode(ModeTarot.MISERE);
        HandTarot curHand_ = new HandTarot();
        curHand_.ajouter(CardTarot.DIAMOND_4);
        curHand_.ajouter(CardTarot.DIAMOND_6);
        curHand_.ajouter(CardTarot.SPADE_8);
        curHand_.ajouter(CardTarot.HEART_10);
        curHand_.ajouter(CardTarot.SPADE_6);
        curHand_.ajouter(CardTarot.SPADE_7);
        curHand_.ajouter(CardTarot.CLUB_9);
        curHand_.ajouter(CardTarot.HEART_9);
        curHand_.ajouter(CardTarot.DIAMOND_7);
        curHand_.ajouter(CardTarot.SPADE_5);
        EnumList<BidTarot> bids_ = new EnumList<BidTarot>();
        CustList<TrickTarot> trs_ = new CustList<TrickTarot>();
        byte d_ = 1;
        TrickTarot t_ = new TrickTarot((byte) getTaker(r_,d_,bids_),false);
        t_.ajouter(CardTarot.SPADE_QUEEN);
        t_.ajouter(CardTarot.SPADE_10);
        t_.ajouter(CardTarot.SPADE_1);
        t_.ajouter(CardTarot.DIAMOND_3);
        t_.ajouter(CardTarot.DIAMOND_5);
        t_.ajouter(CardTarot.DIAMOND_8);
        trs_.add(t_);
        t_ = new TrickTarot(r_.getDealing().getNextPlayer(d_),true);
        t_.ajouter(CardTarot.HEART_1);
        t_.ajouter(CardTarot.HEART_3);
        t_.ajouter(CardTarot.HEART_2);
        t_.ajouter(CardTarot.HEART_4);
        t_.ajouter(CardTarot.HEART_5);
        t_.ajouter(CardTarot.HEART_KING);
        trs_.add(t_);
        t_ = new TrickTarot(t_.getRamasseur(),true);
        t_.ajouter(CardTarot.CLUB_1);
        t_.ajouter(CardTarot.CLUB_KING);
        t_.ajouter(CardTarot.CLUB_QUEEN);
        t_.ajouter(CardTarot.CLUB_2);
        t_.ajouter(CardTarot.CLUB_3);
        t_.ajouter(CardTarot.CLUB_4);
        trs_.add(t_);
        TrickTarot pr_ = new TrickTarot(t_.getRamasseur(),true);
        pr_.ajouter(CardTarot.EXCUSE);
        HandTarot calledCards_ = new HandTarot();
        GameTarot g_ = newGameTarotWithourDecl(r_, trs_, pr_, d_, bids_, calledCards_, -1, last_);
        GameTarotTeamsRelation team_ = g_.getTeamsRelation();
        GameTarotTrickInfo info_ = newGameTarotTrickInfo(g_);
        GameTarotMisere gbt_ = newGameTarotMisere(g_,info_,team_,curHand_);
        assertSame(CardTarot.CLUB_9,gbt_.enCours());
    }
}
