package code.scripts.pages.aiki;
final class MesDataPokemonPokedex{
private static final String C_P_82_0="Search pokemon\n";
private static final String C_P_82_10="Searching mode of ability\n";
private static final String C_P_82_11="Move\n";
private static final String C_P_82_12="Searching mode of move\n";
private static final String C_P_82_13="Name\n";
private static final String C_P_82_14="Types\n";
private static final String C_P_82_15="Image\n";
private static final String C_P_82_16="Number of evolutions\n";
private static final String C_P_82_17="Legendary\n";
private static final String C_P_82_18="Return to the index\n";
private static final String C_P_82_19="Rechercher des pokemon\n";
private static final String C_P_82_1="Pokedex\n";
private static final String C_P_82_20="Pokedex\n";
private static final String C_P_82_21="Pokemon\n";
private static final String C_P_82_22="Avec évolution?\n";
private static final String C_P_82_23="Nombre d''évolutions directes\n";
private static final String C_P_82_24="Evolué\n";
private static final String C_P_82_25="Type\n";
private static final String C_P_82_26="Mot entier pour un des types\n";
private static final String C_P_82_27="Mode de recherche de type\n";
private static final String C_P_82_28="Capacité\n";
private static final String C_P_82_29="Mode de recherche de capacité\n";
private static final String C_P_82_2="Pokemon\n";
private static final String C_P_82_30="Attaque\n";
private static final String C_P_82_31="Mode de recherche d''attaque\n";
private static final String C_P_82_32="Nom\n";
private static final String C_P_82_33="Types\n";
private static final String C_P_82_34="Image\n";
private static final String C_P_82_35="Nombre d''évolutions\n";
private static final String C_P_82_36="Légendaire\n";
private static final String C_P_82_37="Revenir à l''indexe\n";
private static final String C_P_82_3="With evolution?\n";
private static final String C_P_82_4="Number of direct evolutions\n";
private static final String C_P_82_5="Evoluated\n";
private static final String C_P_82_6="Type\n";
private static final String C_P_82_7="Whole word for one of the types\n";
private static final String C_P_82_8="Searching mode of type\n";
private static final String C_P_82_9="Ability\n";
private static final String C_P_82_38="OK\n";
private static final String M_P_82_CONTENT_ABILITY="content_ability";
private static final String M_P_82_CONTENT_ABILITY_MODE="content_ability_mode";
private static final String M_P_82_CONTENT_MOVE="content_move";
private static final String M_P_82_CONTENT_MOVE_MODE="content_move_mode";
private static final String M_P_82_CONTENT_NAME="content_name";
private static final String M_P_82_CONTENT_TYPE="content_type";
private static final String M_P_82_CONTENT_TYPE_MODE="content_type_mode";
private static final String M_P_82_CONTENT_TYPE_WHOLE="content_type_whole";
private static final String M_P_82_EVOS="evos";
private static final String M_P_82_HAS_EVO="has_evo";
private static final String M_P_82_IMAGE="image";
private static final String M_P_82_INDEX="index";
private static final String M_P_82_IS_EVO="is_evo";
private static final String M_P_82_LEG="leg";
private static final String M_P_82_NAME="name";
private static final String M_P_82_NB_EVOS="nb_evos";
private static final String M_P_82_POKEDEX="pokedex";
private static final String M_P_82_TITLE="title";
private static final String M_P_82_TYPES="types";
private static final String M_P_82_OK="ok";
private static final char SEP='=';
private MesDataPokemonPokedex(){}
static String en(){
String f=M_P_82_TITLE+SEP+C_P_82_0;
f+=M_P_82_POKEDEX+SEP+C_P_82_1;
f+=M_P_82_CONTENT_NAME+SEP+C_P_82_2;
f+=M_P_82_HAS_EVO+SEP+C_P_82_3;
f+=M_P_82_NB_EVOS+SEP+C_P_82_4;
f+=M_P_82_IS_EVO+SEP+C_P_82_5;
f+=M_P_82_CONTENT_TYPE+SEP+C_P_82_6;
f+=M_P_82_CONTENT_TYPE_WHOLE+SEP+C_P_82_7;
f+=M_P_82_CONTENT_TYPE_MODE+SEP+C_P_82_8;
f+=M_P_82_CONTENT_ABILITY+SEP+C_P_82_9;
f+=M_P_82_CONTENT_ABILITY_MODE+SEP+C_P_82_10;
f+=M_P_82_CONTENT_MOVE+SEP+C_P_82_11;
f+=M_P_82_CONTENT_MOVE_MODE+SEP+C_P_82_12;
f+=M_P_82_NAME+SEP+C_P_82_13;
f+=M_P_82_TYPES+SEP+C_P_82_14;
f+=M_P_82_IMAGE+SEP+C_P_82_15;
f+=M_P_82_EVOS+SEP+C_P_82_16;
f+=M_P_82_LEG+SEP+C_P_82_17;
f+=M_P_82_INDEX+SEP+C_P_82_18;
f+=M_P_82_OK+SEP+C_P_82_38;
return f;
}
static String fr(){
String f=M_P_82_TITLE+SEP+C_P_82_19;
f+=M_P_82_POKEDEX+SEP+C_P_82_20;
f+=M_P_82_CONTENT_NAME+SEP+C_P_82_21;
f+=M_P_82_HAS_EVO+SEP+C_P_82_22;
f+=M_P_82_NB_EVOS+SEP+C_P_82_23;
f+=M_P_82_IS_EVO+SEP+C_P_82_24;
f+=M_P_82_CONTENT_TYPE+SEP+C_P_82_25;
f+=M_P_82_CONTENT_TYPE_WHOLE+SEP+C_P_82_26;
f+=M_P_82_CONTENT_TYPE_MODE+SEP+C_P_82_27;
f+=M_P_82_CONTENT_ABILITY+SEP+C_P_82_28;
f+=M_P_82_CONTENT_ABILITY_MODE+SEP+C_P_82_29;
f+=M_P_82_CONTENT_MOVE+SEP+C_P_82_30;
f+=M_P_82_CONTENT_MOVE_MODE+SEP+C_P_82_31;
f+=M_P_82_NAME+SEP+C_P_82_32;
f+=M_P_82_TYPES+SEP+C_P_82_33;
f+=M_P_82_IMAGE+SEP+C_P_82_34;
f+=M_P_82_EVOS+SEP+C_P_82_35;
f+=M_P_82_LEG+SEP+C_P_82_36;
f+=M_P_82_INDEX+SEP+C_P_82_37;
f+=M_P_82_OK+SEP+C_P_82_38;
return f;
}
}
