package cards.network.common;

public enum PlayerActionGameType {
    SIMPLE,SLAM,CALLED_CARD_KNOWN,COMPLETED_HAND,DEALT,
    DONE_BIDDING,DONE_DISPLAY_SLAM,DONE_PAUSE,DONE_PLAYING,
    REFHESHED_HAND_PRESIDENT,SELECT_TEAMS,SELECT_TRICKS_HANDS,
    SHOW_DOG,VALIDATE_DOG,
    OK
}
