package aiki.sml.init;
import aiki.map.characters.enums.*;
import aiki.map.characters.*;
import aiki.instances.*;
import aiki.fight.util.*;
import aiki.util.*;
import aiki.fight.*;
import aiki.fight.effects.*;
import aiki.fight.moves.effects.*;
import aiki.fight.status.effects.*;
import aiki.fight.moves.enums.*;
import aiki.fight.status.*;
import aiki.fight.enums.*;
import code.maths.*;
import code.maths.montecarlo.*;
import code.util.*;
import aiki.map.pokemon.*;
import aiki.map.levels.*;
import aiki.map.levels.enums.*;
import aiki.map.pokemon.enums.*;
public final class Lv extends CstIgame{
private static final short W1 = (short)1;
private static final short W2 = (short)2;
private static final short W3 = (short)3;
private static final short W4 = (short)4;
private static final short W5 = (short)5;
private static final short W6 = (short)6;
private static final short W7 = (short)7;
private static final short W8 = (short)8;
private static final short W9 = (short)9;
private static final short W10 = (short)10;
private static final short W11 = (short)11;
private static final short W12 = (short)12;
private static final short W13 = (short)13;
private static final short W14 = (short)14;
private static final short W30 = (short)30;
private static final short H1 = (short)1;
private static final short H2 = (short)2;
private static final short H3 = (short)3;
private static final short H4 = (short)4;
private static final short H5 = (short)5;
private static final short H6 = (short)6;
private static final short H7 = (short)7;
private static final short H8 = (short)8;
private static final short H9 = (short)9;
private static final short H10 = (short)10;
private static final short H11 = (short)11;
private static final short H12 = (short)12;
private static final short H13 = (short)13;
private static final short H14 = (short)14;
private static final short H30 = (short)30;
private static final short N0 = 0;
private static final short N1 = 1;
private static final short N2 = 2;
private static final short N3 = 3;
private static final short N4 = 4;
private static final short N5 = 5;
private static final short N6 = 6;
private static final short N7 = 7;
private Lv(){}
public static LevelIndoorPokemonCenter pc0(){
LevelIndoorPokemonCenter m516levelIndoorPokemonCenter_=Instances.newLevelIndoorPokemonCenter();
PointsPerson m516objectMapPointPerson_=new PointsPerson(new CollCapacity(5));
GerantPokemon m516gerantPokemon_=Instances.newGerantPokemon();
m516gerantPokemon_.setGerance(GeranceType.FOSSILE);
m516gerantPokemon_.setImageMiniFileName(F_BREEDER_M_TXT);
m516objectMapPointPerson_.addEntry(new Point((short)4,(short)2),m516gerantPokemon_);
Seller m516seller_=Instances.newSeller();
m516seller_.setSell(SellType.MOVE);
m516seller_.setImageMiniFileName(F_SELLER_M_TXT);
m516objectMapPointPerson_.addEntry(new Point((short)9,(short)3),m516seller_);
m516gerantPokemon_=Instances.newGerantPokemon();
m516gerantPokemon_.setGerance(GeranceType.HOST);
m516gerantPokemon_.setImageMiniFileName(F_BREEDER_M_TXT);
m516objectMapPointPerson_.addEntry(new Point((short)4,(short)0),m516gerantPokemon_);
m516gerantPokemon_=Instances.newGerantPokemon();
m516gerantPokemon_.setGerance(GeranceType.HEAL);
m516gerantPokemon_.setImageMiniFileName(F_BREEDER_F_TXT);
m516objectMapPointPerson_.addEntry(new Point((short)0,(short)5),m516gerantPokemon_);
m516seller_=Instances.newSeller();
m516seller_.setSell(SellType.ITEM);
m516seller_.setItems(new StringList(I_VIEIL_AMBRE,I_NAUTILE,I_FOSSILE_DOME,I_POKE_BALL,I_POTION,I_DENT_OCEAN,I_PIERRE_FOUDRE,I_GRIFFE_RASOIR,I_ENCENS_VAGUE,I_PIERRE_STASE,I_PIECE_RUNE,I_PIERRE_ECLAT,I_OEUF_CHANCE,I_ENCENS_FLEUR,I_PIERRE_EAU,I_ENCENS_ROC,I_ENCENS_PUR,I_PIERRE_OVALE,I_PIERRE_SOLAIRE,I_CEINT_POUV,I_ENCENS_VEINE,I_PIERRE_FEU,I_CHAINE_POUV,I_ECAILLE_OCEAN,I_PIERRE_NUIT,I_ENCENS_MER,I_MAGMARISEUR,I_PIERRE_MOUSSE,I_POIDS_POUV,I_BAND_POUV,I_PIERRE_LUNE,I_LENT_POUV,I_BRAC_MACHO,I_CD_DOUTEUX,I_GRELOT_ZEN,I_ROCHE_ROYALE,I_PROTECTEUR,I_CROC_RASOIR,I_PIERRE_PLANTE,I_PEAU_METAL,I_ECAILLE_DRACO,I_ENCENS_PLEIN,I_MULTI_EXP,I_BIZAR_ENCENS,I_AMELIORATOR,I_TISSU_FAUCHE,I_PIERRE_AUBE,I_POIGN_POUV,I_PIERRE_GLACE,I_CHANTIBONBON,I_ENCENS_DOUX,I_SACHET_SENTEUR,I_ELECTRISEUR));
m516seller_.setImageMiniFileName(F_SELLER_F_TXT);
m516objectMapPointPerson_.addEntry(new Point((short)9,(short)5),m516seller_);
m516levelIndoorPokemonCenter_.setGerants(m516objectMapPointPerson_);
m516levelIndoorPokemonCenter_.setStorageCoords(new Point((short)0,(short)8));
PointsBlock m516objectMapPointBlock_=new PointsBlock(new CollCapacity(1));
Block m516block_=Instances.newBlock();
m516block_.setWidth(W10);
m516block_.setHeight(H10);
m516block_.setTileFileName(F_BUILDING_INSIDE_TXT);
m516block_.setType(EnvironmentType.BUILDING);
m516objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m516block_);
m516levelIndoorPokemonCenter_.setBlocks(m516objectMapPointBlock_);
return m516levelIndoorPokemonCenter_;
}
public static LevelIndoorGym p0(){
LevelIndoorGym m517levelIndoorGym_=Instances.newLevelIndoorGym();
PointsGymTrainer m517objectMapPointGymTrainer_=new PointsGymTrainer(new CollCapacity(1));
m517objectMapPointGymTrainer_.addEntry(new Point((short)2,(short)8),TrGym.p0t0());
m517levelIndoorGym_.setGymTrainers(m517objectMapPointGymTrainer_);
m517levelIndoorGym_.setGymLeaderCoords(new Point((short)4,(short)0));
m517levelIndoorGym_.setGymLeader(TrGym.p0());
PointsBlock m517objectMapPointBlock_=new PointsBlock(new CollCapacity(1));
Block m517block_=Instances.newBlock();
m517block_.setWidth(W10);
m517block_.setHeight(H10);
m517block_.setTileFileName(F_BUILDING_10_10_TXT);
m517block_.setType(EnvironmentType.BUILDING);
m517objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m517block_);
m517levelIndoorGym_.setBlocks(m517objectMapPointBlock_);
return m517levelIndoorGym_;
}
public static LevelOutdoor po0(){
LevelOutdoor m518levelOutdoor_=Instances.newLevelOutdoor();
PointsBlock m518objectMapPointBlock_=new PointsBlock(new CollCapacity(19));
Block m518block_=Instances.newBlock();
m518block_.setWidth(W5);
m518block_.setHeight(H4);
m518block_.setTileFileName(F_CITY_NOTHING_PT_4_15_TXT);
m518block_.setType(EnvironmentType.NOTHING);
m518objectMapPointBlock_.addEntry(new Point((short)4,(short)15),m518block_);
m518block_=Instances.newBlock();
m518block_.setWidth(W4);
m518block_.setHeight(H4);
m518block_.setTileFileName(F_CITY_NOTHING_PT_22_15_TXT);
m518block_.setType(EnvironmentType.NOTHING);
m518objectMapPointBlock_.addEntry(new Point((short)22,(short)15),m518block_);
m518block_=Instances.newBlock();
m518block_.setWidth(W4);
m518block_.setHeight(H6);
m518block_.setTileFileName(F_CITY_ROAD_GRASS_PT_0_9_TXT);
m518block_.setType(EnvironmentType.ROAD);
m518objectMapPointBlock_.addEntry(new Point((short)0,(short)9),m518block_);
m518block_=Instances.newBlock();
m518block_.setWidth(W4);
m518block_.setHeight(H4);
m518block_.setTileFileName(F_CITY_NOTHING_PT_22_0_TXT);
m518block_.setType(EnvironmentType.NOTHING);
m518objectMapPointBlock_.addEntry(new Point((short)22,(short)0),m518block_);
m518block_=Instances.newBlock();
m518block_.setWidth(W5);
m518block_.setHeight(H7);
m518block_.setTileFileName(F_CITY_ROAD_PT_4_8_TXT);
m518block_.setType(EnvironmentType.ROAD);
m518objectMapPointBlock_.addEntry(new Point((short)4,(short)8),m518block_);
m518block_=Instances.newBlock();
m518block_.setWidth(W4);
m518block_.setHeight(H5);
m518block_.setTileFileName(F_CITY_NOTHING_PT_0_4_TXT);
m518block_.setType(EnvironmentType.NOTHING);
m518objectMapPointBlock_.addEntry(new Point((short)0,(short)4),m518block_);
m518block_=Instances.newBlock();
m518block_.setWidth(W6);
m518block_.setHeight(H4);
m518block_.setTileFileName(F_CITY_ROAD_GRASS_PT_9_0_TXT);
m518block_.setType(EnvironmentType.ROAD);
m518objectMapPointBlock_.addEntry(new Point((short)9,(short)0),m518block_);
m518block_=Instances.newBlock();
m518block_.setWidth(W7);
m518block_.setHeight(H4);
m518block_.setTileFileName(F_CITY_NOTHING_PT_15_0_TXT);
m518block_.setType(EnvironmentType.NOTHING);
m518objectMapPointBlock_.addEntry(new Point((short)15,(short)0),m518block_);
m518block_=Instances.newBlock();
m518block_.setWidth(W6);
m518block_.setHeight(H11);
m518block_.setTileFileName(F_CITY_ROAD_PT_9_4_TXT);
m518block_.setType(EnvironmentType.ROAD);
m518objectMapPointBlock_.addEntry(new Point((short)9,(short)4),m518block_);
m518block_=Instances.newBlock();
m518block_.setWidth(W5);
m518block_.setHeight(H4);
m518block_.setTileFileName(F_NOTHING_PK_CENTER_TXT);
m518block_.setType(EnvironmentType.NOTHING);
m518objectMapPointBlock_.addEntry(new Point((short)4,(short)4),m518block_);
m518block_=Instances.newBlock();
m518block_.setWidth(W7);
m518block_.setHeight(H6);
m518block_.setTileFileName(F_CITY_ROAD_PT_15_9_TXT);
m518block_.setType(EnvironmentType.ROAD);
m518objectMapPointBlock_.addEntry(new Point((short)15,(short)9),m518block_);
m518block_=Instances.newBlock();
m518block_.setWidth(W4);
m518block_.setHeight(H4);
m518block_.setTileFileName(F_CITY_NOTHING_PT_0_0_TXT);
m518block_.setType(EnvironmentType.NOTHING);
m518objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m518block_);
m518block_=Instances.newBlock();
m518block_.setWidth(W6);
m518block_.setHeight(H4);
m518block_.setTileFileName(F_CITY_ROAD_GRASS_PT_9_15_TXT);
m518block_.setType(EnvironmentType.ROAD);
m518objectMapPointBlock_.addEntry(new Point((short)9,(short)15),m518block_);
m518block_=Instances.newBlock();
m518block_.setWidth(W4);
m518block_.setHeight(H6);
m518block_.setTileFileName(F_CITY_ROAD_GRASS_PT_22_9_TXT);
m518block_.setType(EnvironmentType.ROAD);
m518objectMapPointBlock_.addEntry(new Point((short)22,(short)9),m518block_);
m518block_=Instances.newBlock();
m518block_.setWidth(W4);
m518block_.setHeight(H4);
m518block_.setTileFileName(F_CITY_NOTHING_PT_0_15_TXT);
m518block_.setType(EnvironmentType.NOTHING);
m518objectMapPointBlock_.addEntry(new Point((short)0,(short)15),m518block_);
m518block_=Instances.newBlock();
m518block_.setWidth(W5);
m518block_.setHeight(H4);
m518block_.setTileFileName(F_CITY_NOTHING_PT_4_0_TXT);
m518block_.setType(EnvironmentType.NOTHING);
m518objectMapPointBlock_.addEntry(new Point((short)4,(short)0),m518block_);
m518block_=Instances.newBlock();
m518block_.setWidth(W4);
m518block_.setHeight(H5);
m518block_.setTileFileName(F_CITY_NOTHING_PT_22_4_TXT);
m518block_.setType(EnvironmentType.NOTHING);
m518objectMapPointBlock_.addEntry(new Point((short)22,(short)4),m518block_);
m518block_=Instances.newBlock();
m518block_.setWidth(W7);
m518block_.setHeight(H4);
m518block_.setTileFileName(F_CITY_NOTHING_PT_15_15_TXT);
m518block_.setType(EnvironmentType.NOTHING);
m518objectMapPointBlock_.addEntry(new Point((short)15,(short)15),m518block_);
m518block_=Instances.newBlock();
m518block_.setWidth(W7);
m518block_.setHeight(H5);
m518block_.setTileFileName(F_NOTHING_GYM_TXT);
m518block_.setType(EnvironmentType.NOTHING);
m518objectMapPointBlock_.addEntry(new Point((short)15,(short)4),m518block_);
m518levelOutdoor_.setBlocks(m518objectMapPointBlock_);
return m518levelOutdoor_;
}
public static LevelRoad p1(){
LevelRoad m519levelRoad_ = Instances.newLevelRoad();
 CustList<AreaApparition> m519custListAreaApparition_=new  CustList<AreaApparition>(new CollCapacity(8));
m519custListAreaApparition_.add(Ar.p1l0a0());
m519custListAreaApparition_.add(Ar.p1l0a1());
m519custListAreaApparition_.add(Ar.p1l0a2());
m519custListAreaApparition_.add(Ar.p1l0a3());
m519custListAreaApparition_.add(Ar.p1l0a4());
m519custListAreaApparition_.add(Ar.p1l0a5());
m519custListAreaApparition_.add(Ar.p1l0a6());
m519custListAreaApparition_.add(Ar.p1l0a7());
m519levelRoad_.setWildPokemonAreas(m519custListAreaApparition_);
PointsCharacterInRoadCave m519objectMapPointCharacterInRoadCave_=new PointsCharacterInRoadCave(new CollCapacity(2));
m519objectMapPointCharacterInRoadCave_.addEntry(new Point((short)9,(short)9),TrBase.p1l0t0());
m519objectMapPointCharacterInRoadCave_.addEntry(new Point((short)4,(short)9),TrBase.p1l0t1());
m519levelRoad_.setCharacters(m519objectMapPointCharacterInRoadCave_);
PointsBlock m519objectMapPointBlock_=new PointsBlock(new CollCapacity(17));
Block m519block_=Instances.newBlock();
m519block_.setWidth(W2);
m519block_.setHeight(H1);
m519block_.setTileFileName(F_ROAD_GRASS_2_1_TXT);
m519block_.setType(EnvironmentType.GRASS);
m519objectMapPointBlock_.addEntry(new Point((short)4,(short)6),m519block_);
m519block_=Instances.newBlock();
m519block_.setWidth(W2);
m519block_.setHeight(H2);
m519block_.setIndexApparition(N7);
m519block_.setTileFileName(F_GRASS_2_2_TXT);
m519block_.setType(EnvironmentType.GRASS);
m519objectMapPointBlock_.addEntry(new Point((short)8,(short)0),m519block_);
m519block_=Instances.newBlock();
m519block_.setWidth(W2);
m519block_.setHeight(H1);
m519block_.setTileFileName(F_ROAD_GRASS_2_1_TXT);
m519block_.setType(EnvironmentType.GRASS);
m519objectMapPointBlock_.addEntry(new Point((short)8,(short)9),m519block_);
m519block_=Instances.newBlock();
m519block_.setWidth(W2);
m519block_.setHeight(H2);
m519block_.setIndexApparition(N3);
m519block_.setTileFileName(F_GRASS_2_2_TXT);
m519block_.setType(EnvironmentType.GRASS);
m519objectMapPointBlock_.addEntry(new Point((short)8,(short)7),m519block_);
m519block_=Instances.newBlock();
m519block_.setWidth(W2);
m519block_.setHeight(H2);
m519block_.setIndexApparition(N6);
m519block_.setTileFileName(F_GRASS_2_2_TXT);
m519block_.setType(EnvironmentType.GRASS);
m519objectMapPointBlock_.addEntry(new Point((short)4,(short)0),m519block_);
m519block_=Instances.newBlock();
m519block_.setWidth(W2);
m519block_.setHeight(H2);
m519block_.setIndexApparition(N2);
m519block_.setTileFileName(F_GRASS_2_2_TXT);
m519block_.setType(EnvironmentType.GRASS);
m519objectMapPointBlock_.addEntry(new Point((short)4,(short)7),m519block_);
m519block_=Instances.newBlock();
m519block_.setWidth(W2);
m519block_.setHeight(H12);
m519block_.setTileFileName(F_ROAD_VERT_TXT);
m519block_.setType(EnvironmentType.ROAD);
m519objectMapPointBlock_.addEntry(new Point((short)6,(short)0),m519block_);
m519block_=Instances.newBlock();
m519block_.setWidth(W2);
m519block_.setHeight(H2);
m519block_.setIndexApparition(N1);
m519block_.setTileFileName(F_GRASS_2_2_TXT);
m519block_.setType(EnvironmentType.GRASS);
m519objectMapPointBlock_.addEntry(new Point((short)8,(short)10),m519block_);
m519block_=Instances.newBlock();
m519block_.setWidth(W4);
m519block_.setHeight(H12);
m519block_.setTileFileName(F_ROAD_LEFT_BORDER_TXT);
m519block_.setType(EnvironmentType.NOTHING);
m519objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m519block_);
m519block_=Instances.newBlock();
m519block_.setWidth(W4);
m519block_.setHeight(H12);
m519block_.setTileFileName(F_ROAD_RIGHT_BORDER_TXT);
m519block_.setType(EnvironmentType.NOTHING);
m519objectMapPointBlock_.addEntry(new Point((short)10,(short)0),m519block_);
m519block_=Instances.newBlock();
m519block_.setWidth(W2);
m519block_.setHeight(H2);
m519block_.setTileFileName(F_ROAD_GRASS_2_2_TXT);
m519block_.setType(EnvironmentType.GRASS);
m519objectMapPointBlock_.addEntry(new Point((short)4,(short)2),m519block_);
m519block_=Instances.newBlock();
m519block_.setWidth(W2);
m519block_.setHeight(H2);
m519block_.setIndexApparition(N0);
m519block_.setTileFileName(F_GRASS_2_2_TXT);
m519block_.setType(EnvironmentType.GRASS);
m519objectMapPointBlock_.addEntry(new Point((short)4,(short)10),m519block_);
m519block_=Instances.newBlock();
m519block_.setWidth(W2);
m519block_.setHeight(H2);
m519block_.setIndexApparition(N5);
m519block_.setTileFileName(F_GRASS_2_2_TXT);
m519block_.setType(EnvironmentType.GRASS);
m519objectMapPointBlock_.addEntry(new Point((short)8,(short)4),m519block_);
m519block_=Instances.newBlock();
m519block_.setWidth(W2);
m519block_.setHeight(H2);
m519block_.setIndexApparition(N4);
m519block_.setTileFileName(F_GRASS_2_2_TXT);
m519block_.setType(EnvironmentType.GRASS);
m519objectMapPointBlock_.addEntry(new Point((short)4,(short)4),m519block_);
m519block_=Instances.newBlock();
m519block_.setWidth(W2);
m519block_.setHeight(H1);
m519block_.setTileFileName(F_ROAD_GRASS_2_1_TXT);
m519block_.setType(EnvironmentType.GRASS);
m519objectMapPointBlock_.addEntry(new Point((short)8,(short)6),m519block_);
m519block_=Instances.newBlock();
m519block_.setWidth(W2);
m519block_.setHeight(H1);
m519block_.setTileFileName(F_ROAD_GRASS_2_1_TXT);
m519block_.setType(EnvironmentType.GRASS);
m519objectMapPointBlock_.addEntry(new Point((short)4,(short)9),m519block_);
m519block_=Instances.newBlock();
m519block_.setWidth(W2);
m519block_.setHeight(H2);
m519block_.setTileFileName(F_ROAD_GRASS_2_2_TXT);
m519block_.setType(EnvironmentType.GRASS);
m519objectMapPointBlock_.addEntry(new Point((short)8,(short)2),m519block_);
m519levelRoad_.setBlocks(m519objectMapPointBlock_);
return m519levelRoad_;
}
public static LevelIndoorGym p2(){
LevelIndoorGym m520levelIndoorGym_=Instances.newLevelIndoorGym();
PointsGymTrainer m520objectMapPointGymTrainer_=new PointsGymTrainer(new CollCapacity(2));
m520objectMapPointGymTrainer_.addEntry(new Point((short)8,(short)8),TrGym.p2t0());
m520objectMapPointGymTrainer_.addEntry(new Point((short)2,(short)8),TrGym.p2t1());
m520levelIndoorGym_.setGymTrainers(m520objectMapPointGymTrainer_);
m520levelIndoorGym_.setGymLeaderCoords(new Point((short)4,(short)0));
m520levelIndoorGym_.setGymLeader(TrGym.p2());
PointsBlock m520objectMapPointBlock_=new PointsBlock(new CollCapacity(1));
Block m520block_=Instances.newBlock();
m520block_.setWidth(W10);
m520block_.setHeight(H10);
m520block_.setTileFileName(F_BUILDING_10_10_TXT);
m520block_.setType(EnvironmentType.BUILDING);
m520objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m520block_);
m520levelIndoorGym_.setBlocks(m520objectMapPointBlock_);
return m520levelIndoorGym_;
}
public static LevelIndoorPokemonCenter pc2(){
LevelIndoorPokemonCenter m521levelIndoorPokemonCenter_=Instances.newLevelIndoorPokemonCenter();
PointsPerson m521objectMapPointPerson_=new PointsPerson(new CollCapacity(3));
Seller m521seller_=Instances.newSeller();
m521seller_.setSell(SellType.MOVE);
m521seller_.setImageMiniFileName(F_SELLER_M_TXT);
m521objectMapPointPerson_.addEntry(new Point((short)9,(short)3),m521seller_);
m521seller_=Instances.newSeller();
m521seller_.setSell(SellType.ITEM);
m521seller_.setItems(new StringList(I_POKE_BALL,I_POTION));
m521seller_.setImageMiniFileName(F_SELLER_F_TXT);
m521objectMapPointPerson_.addEntry(new Point((short)9,(short)5),m521seller_);
GerantPokemon m521gerantPokemon_=Instances.newGerantPokemon();
m521gerantPokemon_.setGerance(GeranceType.HEAL);
m521gerantPokemon_.setImageMiniFileName(F_BREEDER_F_TXT);
m521objectMapPointPerson_.addEntry(new Point((short)0,(short)5),m521gerantPokemon_);
m521levelIndoorPokemonCenter_.setGerants(m521objectMapPointPerson_);
m521levelIndoorPokemonCenter_.setStorageCoords(new Point((short)0,(short)8));
PointsBlock m521objectMapPointBlock_=new PointsBlock(new CollCapacity(1));
Block m521block_=Instances.newBlock();
m521block_.setWidth(W10);
m521block_.setHeight(H10);
m521block_.setTileFileName(F_BUILDING_INSIDE_TXT);
m521block_.setType(EnvironmentType.BUILDING);
m521objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m521block_);
m521levelIndoorPokemonCenter_.setBlocks(m521objectMapPointBlock_);
return m521levelIndoorPokemonCenter_;
}
public static LevelOutdoor po2(){
LevelOutdoor m522levelOutdoor_=Instances.newLevelOutdoor();
PointsBlock m522objectMapPointBlock_=new PointsBlock(new CollCapacity(19));
Block m522block_=Instances.newBlock();
m522block_.setWidth(W6);
m522block_.setHeight(H4);
m522block_.setTileFileName(F_CITY_ROAD_GRASS_PT_9_0_TXT);
m522block_.setType(EnvironmentType.ROAD);
m522objectMapPointBlock_.addEntry(new Point((short)9,(short)0),m522block_);
m522block_=Instances.newBlock();
m522block_.setWidth(W6);
m522block_.setHeight(H11);
m522block_.setTileFileName(F_CITY_ROAD_PT_9_4_TXT);
m522block_.setType(EnvironmentType.ROAD);
m522objectMapPointBlock_.addEntry(new Point((short)9,(short)4),m522block_);
m522block_=Instances.newBlock();
m522block_.setWidth(W7);
m522block_.setHeight(H5);
m522block_.setTileFileName(F_NOTHING_GYM_TXT);
m522block_.setType(EnvironmentType.NOTHING);
m522objectMapPointBlock_.addEntry(new Point((short)15,(short)4),m522block_);
m522block_=Instances.newBlock();
m522block_.setWidth(W5);
m522block_.setHeight(H4);
m522block_.setTileFileName(F_CITY_NOTHING_PT_4_0_TXT);
m522block_.setType(EnvironmentType.NOTHING);
m522objectMapPointBlock_.addEntry(new Point((short)4,(short)0),m522block_);
m522block_=Instances.newBlock();
m522block_.setWidth(W4);
m522block_.setHeight(H4);
m522block_.setTileFileName(F_CITY_NOTHING_PT_22_15_TXT);
m522block_.setType(EnvironmentType.NOTHING);
m522objectMapPointBlock_.addEntry(new Point((short)22,(short)15),m522block_);
m522block_=Instances.newBlock();
m522block_.setWidth(W4);
m522block_.setHeight(H5);
m522block_.setTileFileName(F_CITY_NOTHING_PT_22_4_TXT);
m522block_.setType(EnvironmentType.NOTHING);
m522objectMapPointBlock_.addEntry(new Point((short)22,(short)4),m522block_);
m522block_=Instances.newBlock();
m522block_.setWidth(W5);
m522block_.setHeight(H7);
m522block_.setTileFileName(F_CITY_ROAD_PT_4_8_TXT);
m522block_.setType(EnvironmentType.ROAD);
m522objectMapPointBlock_.addEntry(new Point((short)4,(short)8),m522block_);
m522block_=Instances.newBlock();
m522block_.setWidth(W5);
m522block_.setHeight(H4);
m522block_.setTileFileName(F_NOTHING_PK_CENTER_TXT);
m522block_.setType(EnvironmentType.NOTHING);
m522objectMapPointBlock_.addEntry(new Point((short)4,(short)4),m522block_);
m522block_=Instances.newBlock();
m522block_.setWidth(W5);
m522block_.setHeight(H4);
m522block_.setTileFileName(F_CITY_NOTHING_PT_4_15_TXT);
m522block_.setType(EnvironmentType.NOTHING);
m522objectMapPointBlock_.addEntry(new Point((short)4,(short)15),m522block_);
m522block_=Instances.newBlock();
m522block_.setWidth(W4);
m522block_.setHeight(H4);
m522block_.setTileFileName(F_CITY_NOTHING_PT_0_15_TXT);
m522block_.setType(EnvironmentType.NOTHING);
m522objectMapPointBlock_.addEntry(new Point((short)0,(short)15),m522block_);
m522block_=Instances.newBlock();
m522block_.setWidth(W4);
m522block_.setHeight(H6);
m522block_.setTileFileName(F_CITY_ROAD_GRASS_PT_22_9_TXT);
m522block_.setType(EnvironmentType.ROAD);
m522objectMapPointBlock_.addEntry(new Point((short)22,(short)9),m522block_);
m522block_=Instances.newBlock();
m522block_.setWidth(W7);
m522block_.setHeight(H4);
m522block_.setTileFileName(F_CITY_NOTHING_PT_15_15_TXT);
m522block_.setType(EnvironmentType.NOTHING);
m522objectMapPointBlock_.addEntry(new Point((short)15,(short)15),m522block_);
m522block_=Instances.newBlock();
m522block_.setWidth(W7);
m522block_.setHeight(H6);
m522block_.setTileFileName(F_CITY_ROAD_PT_15_9_TXT);
m522block_.setType(EnvironmentType.ROAD);
m522objectMapPointBlock_.addEntry(new Point((short)15,(short)9),m522block_);
m522block_=Instances.newBlock();
m522block_.setWidth(W4);
m522block_.setHeight(H5);
m522block_.setTileFileName(F_CITY_NOTHING_PT_0_4_TXT);
m522block_.setType(EnvironmentType.NOTHING);
m522objectMapPointBlock_.addEntry(new Point((short)0,(short)4),m522block_);
m522block_=Instances.newBlock();
m522block_.setWidth(W4);
m522block_.setHeight(H4);
m522block_.setTileFileName(F_CITY_NOTHING_PT_22_0_TXT);
m522block_.setType(EnvironmentType.NOTHING);
m522objectMapPointBlock_.addEntry(new Point((short)22,(short)0),m522block_);
m522block_=Instances.newBlock();
m522block_.setWidth(W7);
m522block_.setHeight(H4);
m522block_.setTileFileName(F_CITY_NOTHING_PT_15_0_TXT);
m522block_.setType(EnvironmentType.NOTHING);
m522objectMapPointBlock_.addEntry(new Point((short)15,(short)0),m522block_);
m522block_=Instances.newBlock();
m522block_.setWidth(W6);
m522block_.setHeight(H4);
m522block_.setTileFileName(F_CITY_ROAD_GRASS_PT_9_15_TXT);
m522block_.setType(EnvironmentType.ROAD);
m522objectMapPointBlock_.addEntry(new Point((short)9,(short)15),m522block_);
m522block_=Instances.newBlock();
m522block_.setWidth(W4);
m522block_.setHeight(H6);
m522block_.setTileFileName(F_CITY_ROAD_GRASS_PT_0_9_TXT);
m522block_.setType(EnvironmentType.ROAD);
m522objectMapPointBlock_.addEntry(new Point((short)0,(short)9),m522block_);
m522block_=Instances.newBlock();
m522block_.setWidth(W4);
m522block_.setHeight(H4);
m522block_.setTileFileName(F_CITY_NOTHING_PT_0_0_TXT);
m522block_.setType(EnvironmentType.NOTHING);
m522objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m522block_);
m522levelOutdoor_.setBlocks(m522objectMapPointBlock_);
return m522levelOutdoor_;
}
public static LevelRoad p3(){
LevelRoad m523levelRoad_ = Instances.newLevelRoad();
 CustList<AreaApparition> m523custListAreaApparition_=new  CustList<AreaApparition>(new CollCapacity(8));
m523custListAreaApparition_.add(Ar.p3l0a0());
m523custListAreaApparition_.add(Ar.p3l0a1());
m523custListAreaApparition_.add(Ar.p3l0a2());
m523custListAreaApparition_.add(Ar.p3l0a3());
m523custListAreaApparition_.add(Ar.p3l0a4());
m523custListAreaApparition_.add(Ar.p3l0a5());
m523custListAreaApparition_.add(Ar.p3l0a6());
m523custListAreaApparition_.add(Ar.p3l0a7());
m523levelRoad_.setWildPokemonAreas(m523custListAreaApparition_);
PointsCharacterInRoadCave m523objectMapPointCharacterInRoadCave_=new PointsCharacterInRoadCave(new CollCapacity(2));
m523objectMapPointCharacterInRoadCave_.addEntry(new Point((short)2,(short)4),TrBase.p3l0t0());
m523objectMapPointCharacterInRoadCave_.addEntry(new Point((short)2,(short)9),TrBase.p3l0t1());
m523levelRoad_.setCharacters(m523objectMapPointCharacterInRoadCave_);
PointsBlock m523objectMapPointBlock_=new PointsBlock(new CollCapacity(17));
Block m523block_=Instances.newBlock();
m523block_.setWidth(W2);
m523block_.setHeight(H2);
m523block_.setTileFileName(F_ROAD_GRASS_2_2_TXT);
m523block_.setType(EnvironmentType.GRASS);
m523objectMapPointBlock_.addEntry(new Point((short)2,(short)4),m523block_);
m523block_=Instances.newBlock();
m523block_.setWidth(W2);
m523block_.setHeight(H2);
m523block_.setIndexApparition(N2);
m523block_.setTileFileName(F_GRASS_2_2_TXT);
m523block_.setType(EnvironmentType.GRASS);
m523objectMapPointBlock_.addEntry(new Point((short)4,(short)4),m523block_);
m523block_=Instances.newBlock();
m523block_.setWidth(W12);
m523block_.setHeight(H2);
m523block_.setTileFileName(F_ROAD_HORIZ_TXT);
m523block_.setType(EnvironmentType.ROAD);
m523objectMapPointBlock_.addEntry(new Point((short)0,(short)6),m523block_);
m523block_=Instances.newBlock();
m523block_.setWidth(W2);
m523block_.setHeight(H2);
m523block_.setIndexApparition(N7);
m523block_.setTileFileName(F_GRASS_2_2_TXT);
m523block_.setType(EnvironmentType.GRASS);
m523objectMapPointBlock_.addEntry(new Point((short)10,(short)8),m523block_);
m523block_=Instances.newBlock();
m523block_.setWidth(W2);
m523block_.setHeight(H2);
m523block_.setIndexApparition(N1);
m523block_.setTileFileName(F_GRASS_2_2_TXT);
m523block_.setType(EnvironmentType.GRASS);
m523objectMapPointBlock_.addEntry(new Point((short)0,(short)8),m523block_);
m523block_=Instances.newBlock();
m523block_.setWidth(W2);
m523block_.setHeight(H2);
m523block_.setIndexApparition(N0);
m523block_.setTileFileName(F_GRASS_2_2_TXT);
m523block_.setType(EnvironmentType.GRASS);
m523objectMapPointBlock_.addEntry(new Point((short)0,(short)4),m523block_);
m523block_=Instances.newBlock();
m523block_.setWidth(W2);
m523block_.setHeight(H2);
m523block_.setIndexApparition(N4);
m523block_.setTileFileName(F_GRASS_2_2_TXT);
m523block_.setType(EnvironmentType.GRASS);
m523objectMapPointBlock_.addEntry(new Point((short)7,(short)4),m523block_);
m523block_=Instances.newBlock();
m523block_.setWidth(W12);
m523block_.setHeight(H4);
m523block_.setTileFileName(F_ROAD_TOP_BORDER_TXT);
m523block_.setType(EnvironmentType.NOTHING);
m523objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m523block_);
m523block_=Instances.newBlock();
m523block_.setWidth(W2);
m523block_.setHeight(H2);
m523block_.setTileFileName(F_ROAD_GRASS_2_2_TXT);
m523block_.setType(EnvironmentType.GRASS);
m523objectMapPointBlock_.addEntry(new Point((short)2,(short)8),m523block_);
m523block_=Instances.newBlock();
m523block_.setWidth(W1);
m523block_.setHeight(H2);
m523block_.setTileFileName(F_ROAD_GRASS_1_2_TXT);
m523block_.setType(EnvironmentType.GRASS);
m523objectMapPointBlock_.addEntry(new Point((short)9,(short)8),m523block_);
m523block_=Instances.newBlock();
m523block_.setWidth(W2);
m523block_.setHeight(H2);
m523block_.setIndexApparition(N5);
m523block_.setTileFileName(F_GRASS_2_2_TXT);
m523block_.setType(EnvironmentType.GRASS);
m523objectMapPointBlock_.addEntry(new Point((short)7,(short)8),m523block_);
m523block_=Instances.newBlock();
m523block_.setWidth(W1);
m523block_.setHeight(H2);
m523block_.setTileFileName(F_ROAD_GRASS_1_2_TXT);
m523block_.setType(EnvironmentType.GRASS);
m523objectMapPointBlock_.addEntry(new Point((short)6,(short)4),m523block_);
m523block_=Instances.newBlock();
m523block_.setWidth(W1);
m523block_.setHeight(H2);
m523block_.setTileFileName(F_ROAD_GRASS_1_2_TXT);
m523block_.setType(EnvironmentType.GRASS);
m523objectMapPointBlock_.addEntry(new Point((short)6,(short)8),m523block_);
m523block_=Instances.newBlock();
m523block_.setWidth(W1);
m523block_.setHeight(H2);
m523block_.setTileFileName(F_ROAD_GRASS_1_2_TXT);
m523block_.setType(EnvironmentType.GRASS);
m523objectMapPointBlock_.addEntry(new Point((short)9,(short)4),m523block_);
m523block_=Instances.newBlock();
m523block_.setWidth(W2);
m523block_.setHeight(H2);
m523block_.setIndexApparition(N3);
m523block_.setTileFileName(F_GRASS_2_2_TXT);
m523block_.setType(EnvironmentType.GRASS);
m523objectMapPointBlock_.addEntry(new Point((short)4,(short)8),m523block_);
m523block_=Instances.newBlock();
m523block_.setWidth(W2);
m523block_.setHeight(H2);
m523block_.setIndexApparition(N6);
m523block_.setTileFileName(F_GRASS_2_2_TXT);
m523block_.setType(EnvironmentType.GRASS);
m523objectMapPointBlock_.addEntry(new Point((short)10,(short)4),m523block_);
m523block_=Instances.newBlock();
m523block_.setWidth(W12);
m523block_.setHeight(H4);
m523block_.setTileFileName(F_ROAD_BOTTOM_BORDER_TXT);
m523block_.setType(EnvironmentType.NOTHING);
m523objectMapPointBlock_.addEntry(new Point((short)0,(short)10),m523block_);
m523levelRoad_.setBlocks(m523objectMapPointBlock_);
return m523levelRoad_;
}
public static LevelIndoorPokemonCenter pc4(){
LevelIndoorPokemonCenter m524levelIndoorPokemonCenter_=Instances.newLevelIndoorPokemonCenter();
PointsPerson m524objectMapPointPerson_=new PointsPerson(new CollCapacity(3));
Seller m524seller_=Instances.newSeller();
m524seller_.setSell(SellType.MOVE);
m524seller_.setImageMiniFileName(F_SELLER_M_TXT);
m524objectMapPointPerson_.addEntry(new Point((short)9,(short)3),m524seller_);
GerantPokemon m524gerantPokemon_=Instances.newGerantPokemon();
m524gerantPokemon_.setGerance(GeranceType.HEAL);
m524gerantPokemon_.setImageMiniFileName(F_BREEDER_F_TXT);
m524objectMapPointPerson_.addEntry(new Point((short)0,(short)5),m524gerantPokemon_);
m524seller_=Instances.newSeller();
m524seller_.setSell(SellType.ITEM);
m524seller_.setItems(new StringList(I_POKE_BALL,I_POTION));
m524seller_.setImageMiniFileName(F_SELLER_F_TXT);
m524objectMapPointPerson_.addEntry(new Point((short)9,(short)5),m524seller_);
m524levelIndoorPokemonCenter_.setGerants(m524objectMapPointPerson_);
m524levelIndoorPokemonCenter_.setStorageCoords(new Point((short)0,(short)8));
PointsBlock m524objectMapPointBlock_=new PointsBlock(new CollCapacity(1));
Block m524block_=Instances.newBlock();
m524block_.setWidth(W10);
m524block_.setHeight(H10);
m524block_.setTileFileName(F_BUILDING_INSIDE_TXT);
m524block_.setType(EnvironmentType.BUILDING);
m524objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m524block_);
m524levelIndoorPokemonCenter_.setBlocks(m524objectMapPointBlock_);
return m524levelIndoorPokemonCenter_;
}
public static LevelIndoorGym p4(){
LevelIndoorGym m525levelIndoorGym_=Instances.newLevelIndoorGym();
PointsGymTrainer m525objectMapPointGymTrainer_=new PointsGymTrainer(new CollCapacity(2));
m525objectMapPointGymTrainer_.addEntry(new Point((short)8,(short)8),TrGym.p4t0());
m525objectMapPointGymTrainer_.addEntry(new Point((short)2,(short)8),TrGym.p4t1());
m525levelIndoorGym_.setGymTrainers(m525objectMapPointGymTrainer_);
m525levelIndoorGym_.setGymLeaderCoords(new Point((short)4,(short)0));
m525levelIndoorGym_.setGymLeader(TrGym.p4());
PointsBlock m525objectMapPointBlock_=new PointsBlock(new CollCapacity(1));
Block m525block_=Instances.newBlock();
m525block_.setWidth(W10);
m525block_.setHeight(H10);
m525block_.setTileFileName(F_BUILDING_10_10_TXT);
m525block_.setType(EnvironmentType.BUILDING);
m525objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m525block_);
m525levelIndoorGym_.setBlocks(m525objectMapPointBlock_);
return m525levelIndoorGym_;
}
public static LevelOutdoor po4(){
LevelOutdoor m526levelOutdoor_=Instances.newLevelOutdoor();
PointsBlock m526objectMapPointBlock_=new PointsBlock(new CollCapacity(19));
Block m526block_=Instances.newBlock();
m526block_.setWidth(W7);
m526block_.setHeight(H4);
m526block_.setTileFileName(F_CITY_NOTHING_PT_15_0_TXT);
m526block_.setType(EnvironmentType.NOTHING);
m526objectMapPointBlock_.addEntry(new Point((short)15,(short)0),m526block_);
m526block_=Instances.newBlock();
m526block_.setWidth(W4);
m526block_.setHeight(H4);
m526block_.setTileFileName(F_CITY_NOTHING_PT_22_0_TXT);
m526block_.setType(EnvironmentType.NOTHING);
m526objectMapPointBlock_.addEntry(new Point((short)22,(short)0),m526block_);
m526block_=Instances.newBlock();
m526block_.setWidth(W5);
m526block_.setHeight(H4);
m526block_.setTileFileName(F_NOTHING_PK_CENTER_TXT);
m526block_.setType(EnvironmentType.NOTHING);
m526objectMapPointBlock_.addEntry(new Point((short)4,(short)4),m526block_);
m526block_=Instances.newBlock();
m526block_.setWidth(W4);
m526block_.setHeight(H6);
m526block_.setTileFileName(F_CITY_ROAD_GRASS_PT_0_9_TXT);
m526block_.setType(EnvironmentType.ROAD);
m526objectMapPointBlock_.addEntry(new Point((short)0,(short)9),m526block_);
m526block_=Instances.newBlock();
m526block_.setWidth(W4);
m526block_.setHeight(H5);
m526block_.setTileFileName(F_CITY_NOTHING_PT_22_4_TXT);
m526block_.setType(EnvironmentType.NOTHING);
m526objectMapPointBlock_.addEntry(new Point((short)22,(short)4),m526block_);
m526block_=Instances.newBlock();
m526block_.setWidth(W4);
m526block_.setHeight(H5);
m526block_.setTileFileName(F_CITY_NOTHING_PT_0_4_TXT);
m526block_.setType(EnvironmentType.NOTHING);
m526objectMapPointBlock_.addEntry(new Point((short)0,(short)4),m526block_);
m526block_=Instances.newBlock();
m526block_.setWidth(W4);
m526block_.setHeight(H4);
m526block_.setTileFileName(F_CITY_NOTHING_PT_0_0_TXT);
m526block_.setType(EnvironmentType.NOTHING);
m526objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m526block_);
m526block_=Instances.newBlock();
m526block_.setWidth(W5);
m526block_.setHeight(H7);
m526block_.setTileFileName(F_CITY_ROAD_PT_4_8_TXT);
m526block_.setType(EnvironmentType.ROAD);
m526objectMapPointBlock_.addEntry(new Point((short)4,(short)8),m526block_);
m526block_=Instances.newBlock();
m526block_.setWidth(W7);
m526block_.setHeight(H6);
m526block_.setTileFileName(F_CITY_ROAD_PT_15_9_TXT);
m526block_.setType(EnvironmentType.ROAD);
m526objectMapPointBlock_.addEntry(new Point((short)15,(short)9),m526block_);
m526block_=Instances.newBlock();
m526block_.setWidth(W7);
m526block_.setHeight(H4);
m526block_.setTileFileName(F_CITY_NOTHING_PT_15_15_TXT);
m526block_.setType(EnvironmentType.NOTHING);
m526objectMapPointBlock_.addEntry(new Point((short)15,(short)15),m526block_);
m526block_=Instances.newBlock();
m526block_.setWidth(W6);
m526block_.setHeight(H4);
m526block_.setTileFileName(F_CITY_ROAD_GRASS_PT_9_0_TXT);
m526block_.setType(EnvironmentType.ROAD);
m526objectMapPointBlock_.addEntry(new Point((short)9,(short)0),m526block_);
m526block_=Instances.newBlock();
m526block_.setWidth(W6);
m526block_.setHeight(H11);
m526block_.setTileFileName(F_CITY_ROAD_PT_9_4_TXT);
m526block_.setType(EnvironmentType.ROAD);
m526objectMapPointBlock_.addEntry(new Point((short)9,(short)4),m526block_);
m526block_=Instances.newBlock();
m526block_.setWidth(W4);
m526block_.setHeight(H4);
m526block_.setTileFileName(F_CITY_NOTHING_PT_0_15_TXT);
m526block_.setType(EnvironmentType.NOTHING);
m526objectMapPointBlock_.addEntry(new Point((short)0,(short)15),m526block_);
m526block_=Instances.newBlock();
m526block_.setWidth(W6);
m526block_.setHeight(H4);
m526block_.setTileFileName(F_CITY_ROAD_GRASS_PT_9_15_TXT);
m526block_.setType(EnvironmentType.ROAD);
m526objectMapPointBlock_.addEntry(new Point((short)9,(short)15),m526block_);
m526block_=Instances.newBlock();
m526block_.setWidth(W4);
m526block_.setHeight(H4);
m526block_.setTileFileName(F_CITY_NOTHING_PT_22_15_TXT);
m526block_.setType(EnvironmentType.NOTHING);
m526objectMapPointBlock_.addEntry(new Point((short)22,(short)15),m526block_);
m526block_=Instances.newBlock();
m526block_.setWidth(W4);
m526block_.setHeight(H6);
m526block_.setTileFileName(F_CITY_ROAD_GRASS_PT_22_9_TXT);
m526block_.setType(EnvironmentType.ROAD);
m526objectMapPointBlock_.addEntry(new Point((short)22,(short)9),m526block_);
m526block_=Instances.newBlock();
m526block_.setWidth(W5);
m526block_.setHeight(H4);
m526block_.setTileFileName(F_CITY_NOTHING_PT_4_0_TXT);
m526block_.setType(EnvironmentType.NOTHING);
m526objectMapPointBlock_.addEntry(new Point((short)4,(short)0),m526block_);
m526block_=Instances.newBlock();
m526block_.setWidth(W7);
m526block_.setHeight(H5);
m526block_.setTileFileName(F_NOTHING_GYM_TXT);
m526block_.setType(EnvironmentType.NOTHING);
m526objectMapPointBlock_.addEntry(new Point((short)15,(short)4),m526block_);
m526block_=Instances.newBlock();
m526block_.setWidth(W5);
m526block_.setHeight(H4);
m526block_.setTileFileName(F_CITY_NOTHING_PT_4_15_TXT);
m526block_.setType(EnvironmentType.NOTHING);
m526objectMapPointBlock_.addEntry(new Point((short)4,(short)15),m526block_);
m526levelOutdoor_.setBlocks(m526objectMapPointBlock_);
return m526levelOutdoor_;
}
public static LevelRoad p5(){
LevelRoad m527levelRoad_ = Instances.newLevelRoad();
 CustList<AreaApparition> m527custListAreaApparition_=new  CustList<AreaApparition>(new CollCapacity(2));
m527custListAreaApparition_.add(Ar.p5l0a0());
m527custListAreaApparition_.add(Ar.p5l0a1());
m527levelRoad_.setWildPokemonAreas(m527custListAreaApparition_);
PointsBlock m527objectMapPointBlock_=new PointsBlock(new CollCapacity(11));
Block m527block_=Instances.newBlock();
m527block_.setWidth(W7);
m527block_.setHeight(H1);
m527block_.setTileFileName(F_BOTTOM_BOUND_7_1_TXT);
m527block_.setType(EnvironmentType.NOTHING);
m527objectMapPointBlock_.addEntry(new Point((short)0,(short)6),m527block_);
m527block_=Instances.newBlock();
m527block_.setWidth(W4);
m527block_.setHeight(H6);
m527block_.setTileFileName(F_ROAD_LEFT_BORDER_HALF_TXT);
m527block_.setType(EnvironmentType.NOTHING);
m527objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m527block_);
m527block_=Instances.newBlock();
m527block_.setWidth(W1);
m527block_.setHeight(H1);
m527block_.setTileFileName(F_EMPTY_TXT);
m527block_.setType(EnvironmentType.ROAD);
m527objectMapPointBlock_.addEntry(new Point((short)7,(short)6),m527block_);
m527block_=Instances.newBlock();
m527block_.setWidth(W6);
m527block_.setHeight(H2);
m527block_.setTileFileName(F_ROAD_6_2_TXT);
m527block_.setType(EnvironmentType.ROAD);
m527objectMapPointBlock_.addEntry(new Point((short)4,(short)4),m527block_);
m527block_=Instances.newBlock();
m527block_.setWidth(W14);
m527block_.setHeight(H3);
m527block_.setTileFileName(F_BOTTOM_BOUND_14_3_TXT);
m527block_.setType(EnvironmentType.NOTHING);
m527objectMapPointBlock_.addEntry(new Point((short)0,(short)7),m527block_);
m527block_=Instances.newBlock();
m527block_.setWidth(W6);
m527block_.setHeight(H1);
m527block_.setTileFileName(F_BOTTOM_BOUND_6_1_TXT);
m527block_.setType(EnvironmentType.NOTHING);
m527objectMapPointBlock_.addEntry(new Point((short)8,(short)6),m527block_);
m527block_=Instances.newBlock();
m527block_.setWidth(W4);
m527block_.setHeight(H6);
m527block_.setTileFileName(F_ROAD_RIGHT_BORDER_HALF_TXT);
m527block_.setType(EnvironmentType.NOTHING);
m527objectMapPointBlock_.addEntry(new Point((short)10,(short)0),m527block_);
m527block_=Instances.newBlock();
m527block_.setWidth(W2);
m527block_.setHeight(H2);
m527block_.setIndexApparition(N1);
m527block_.setTileFileName(F_GRASS_2_2_TXT);
m527block_.setType(EnvironmentType.GRASS);
m527objectMapPointBlock_.addEntry(new Point((short)8,(short)0),m527block_);
m527block_=Instances.newBlock();
m527block_.setWidth(W2);
m527block_.setHeight(H2);
m527block_.setIndexApparition(N0);
m527block_.setTileFileName(F_GRASS_2_2_TXT);
m527block_.setType(EnvironmentType.GRASS);
m527objectMapPointBlock_.addEntry(new Point((short)4,(short)0),m527block_);
m527block_=Instances.newBlock();
m527block_.setWidth(W2);
m527block_.setHeight(H2);
m527block_.setTileFileName(F_ROAD_GRASS_2_2_TXT);
m527block_.setType(EnvironmentType.GRASS);
m527objectMapPointBlock_.addEntry(new Point((short)6,(short)0),m527block_);
m527block_=Instances.newBlock();
m527block_.setWidth(W6);
m527block_.setHeight(H2);
m527block_.setTileFileName(F_ROAD_GRASS_6_2_TXT);
m527block_.setType(EnvironmentType.GRASS);
m527objectMapPointBlock_.addEntry(new Point((short)4,(short)2),m527block_);
m527levelRoad_.setBlocks(m527objectMapPointBlock_);
return m527levelRoad_;
}
public static LevelCave p6l0(){
LevelCave m528levelCave_ = Instances.newLevelCave();
PointsLink m528objectMapPointLink_=new PointsLink(new CollCapacity(2));
m528objectMapPointLink_.addEntry(new Point((short)5,(short)17),LvUt.newLink(F_UP_CAVE_TXT,LvUt.newCoords(6,1,new Point((short)5,(short)17)),null));
m528objectMapPointLink_.addEntry(new Point((short)5,(short)6),LvUt.newLink(F_UP_CAVE_TXT,LvUt.newCoords(6,1,new Point((short)5,(short)6)),null));
m528levelCave_.setLinksOtherLevels(m528objectMapPointLink_);
 CustList<AreaApparition> m528custListAreaApparition_=new  CustList<AreaApparition>(new CollCapacity(1));
m528custListAreaApparition_.add(Ar.p6l0a0());
m528levelCave_.setWildPokemonAreas(m528custListAreaApparition_);
PointsBlock m528objectMapPointBlock_=new PointsBlock(new CollCapacity(7));
Block m528block_=Instances.newBlock();
m528block_.setWidth(W4);
m528block_.setHeight(H30);
m528block_.setTileFileName(F_NOTHING_LEFT_CAVE_4_30_TXT);
m528block_.setType(EnvironmentType.NOTHING);
m528objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m528block_);
m528block_=Instances.newBlock();
m528block_.setWidth(W4);
m528block_.setHeight(H30);
m528block_.setTileFileName(F_NOTHING_RIGHT_CAVE_4_30_TXT);
m528block_.setType(EnvironmentType.NOTHING);
m528objectMapPointBlock_.addEntry(new Point((short)14,(short)0),m528block_);
m528block_=Instances.newBlock();
m528block_.setWidth(W10);
m528block_.setHeight(H4);
m528block_.setTileFileName(F_NOTHING_BOTTOM_CAVE_10_4_TXT);
m528block_.setType(EnvironmentType.NOTHING);
m528objectMapPointBlock_.addEntry(new Point((short)4,(short)26),m528block_);
m528block_=Instances.newBlock();
m528block_.setWidth(W10);
m528block_.setHeight(H10);
m528block_.setIndexApparition(N0);
m528block_.setTileFileName(F_ROCK_10_10_TXT);
m528block_.setType(EnvironmentType.ROCK);
m528objectMapPointBlock_.addEntry(new Point((short)4,(short)4),m528block_);
m528block_=Instances.newBlock();
m528block_.setWidth(W10);
m528block_.setHeight(H2);
m528block_.setTileFileName(F_NOTHING_CAVE_10_2_TXT);
m528block_.setType(EnvironmentType.NOTHING);
m528objectMapPointBlock_.addEntry(new Point((short)4,(short)14),m528block_);
m528block_=Instances.newBlock();
m528block_.setWidth(W10);
m528block_.setHeight(H4);
m528block_.setTileFileName(F_NOTHING_TOP_CAVE_10_4_TXT);
m528block_.setType(EnvironmentType.NOTHING);
m528objectMapPointBlock_.addEntry(new Point((short)4,(short)0),m528block_);
m528block_=Instances.newBlock();
m528block_.setWidth(W10);
m528block_.setHeight(H10);
m528block_.setIndexApparition(N0);
m528block_.setTileFileName(F_ROCK_10_10_TXT);
m528block_.setType(EnvironmentType.ROCK);
m528objectMapPointBlock_.addEntry(new Point((short)4,(short)16),m528block_);
m528levelCave_.setBlocks(m528objectMapPointBlock_);
return m528levelCave_;
}
public static LevelCave p6l1(){
LevelCave m529levelCave_ = Instances.newLevelCave();
PointsLink m529objectMapPointLink_=new PointsLink(new CollCapacity(2));
m529objectMapPointLink_.addEntry(new Point((short)5,(short)6),LvUt.newLink(F_DOWN_CAVE_TXT,LvUt.newCoords(6,0,new Point((short)5,(short)6)),null));
m529objectMapPointLink_.addEntry(new Point((short)5,(short)17),LvUt.newLink(F_DOWN_CAVE_TXT,LvUt.newCoords(6,0,new Point((short)5,(short)17)),null));
m529levelCave_.setLinksOtherLevels(m529objectMapPointLink_);
 CustList<AreaApparition> m529custListAreaApparition_=new  CustList<AreaApparition>(new CollCapacity(2));
m529custListAreaApparition_.add(Ar.p6l1a0());
m529custListAreaApparition_.add(Ar.p6l1a1());
m529levelCave_.setWildPokemonAreas(m529custListAreaApparition_);
PointsBlock m529objectMapPointBlock_=new PointsBlock(new CollCapacity(7));
Block m529block_=Instances.newBlock();
m529block_.setWidth(W10);
m529block_.setHeight(H2);
m529block_.setIndexApparition(N1);
m529block_.setTileFileName(F_WATER_10_2_TXT);
m529block_.setType(EnvironmentType.WATER);
m529objectMapPointBlock_.addEntry(new Point((short)4,(short)14),m529block_);
m529block_=Instances.newBlock();
m529block_.setWidth(W10);
m529block_.setHeight(H10);
m529block_.setIndexApparition(N0);
m529block_.setTileFileName(F_ROCK_10_10_TXT);
m529block_.setType(EnvironmentType.ROCK);
m529objectMapPointBlock_.addEntry(new Point((short)4,(short)4),m529block_);
m529block_=Instances.newBlock();
m529block_.setWidth(W4);
m529block_.setHeight(H30);
m529block_.setTileFileName(F_NOTHING_LEFT_CAVE_4_30_TXT);
m529block_.setType(EnvironmentType.NOTHING);
m529objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m529block_);
m529block_=Instances.newBlock();
m529block_.setWidth(W4);
m529block_.setHeight(H30);
m529block_.setTileFileName(F_NOTHING_RIGHT_CAVE_4_30_TXT);
m529block_.setType(EnvironmentType.NOTHING);
m529objectMapPointBlock_.addEntry(new Point((short)14,(short)0),m529block_);
m529block_=Instances.newBlock();
m529block_.setWidth(W10);
m529block_.setHeight(H4);
m529block_.setTileFileName(F_NOTHING_TOP_CAVE_10_4_TXT);
m529block_.setType(EnvironmentType.NOTHING);
m529objectMapPointBlock_.addEntry(new Point((short)4,(short)0),m529block_);
m529block_=Instances.newBlock();
m529block_.setWidth(W10);
m529block_.setHeight(H4);
m529block_.setTileFileName(F_NOTHING_BOTTOM_CAVE_10_4_TXT);
m529block_.setType(EnvironmentType.NOTHING);
m529objectMapPointBlock_.addEntry(new Point((short)4,(short)26),m529block_);
m529block_=Instances.newBlock();
m529block_.setWidth(W10);
m529block_.setHeight(H10);
m529block_.setIndexApparition(N0);
m529block_.setTileFileName(F_ROCK_10_10_TXT);
m529block_.setType(EnvironmentType.ROCK);
m529objectMapPointBlock_.addEntry(new Point((short)4,(short)16),m529block_);
m529levelCave_.setBlocks(m529objectMapPointBlock_);
return m529levelCave_;
}
public static LevelRoad p7(){
LevelRoad m530levelRoad_ = Instances.newLevelRoad();
 CustList<AreaApparition> m530custListAreaApparition_=new  CustList<AreaApparition>(new CollCapacity(1));
m530custListAreaApparition_.add(Ar.p7l0a0());
m530levelRoad_.setWildPokemonAreas(m530custListAreaApparition_);
PointsBlock m530objectMapPointBlock_=new PointsBlock(new CollCapacity(8));
Block m530block_=Instances.newBlock();
m530block_.setWidth(W6);
m530block_.setHeight(H3);
m530block_.setTileFileName(F_ROAD_GRASS_6_3_TXT);
m530block_.setType(EnvironmentType.GRASS);
m530objectMapPointBlock_.addEntry(new Point((short)4,(short)4),m530block_);
m530block_=Instances.newBlock();
m530block_.setWidth(W4);
m530block_.setHeight(H6);
m530block_.setTileFileName(F_ROAD_RIGHT_BORDER_HALF_TXT);
m530block_.setType(EnvironmentType.NOTHING);
m530objectMapPointBlock_.addEntry(new Point((short)10,(short)4),m530block_);
m530block_=Instances.newBlock();
m530block_.setWidth(W4);
m530block_.setHeight(H6);
m530block_.setTileFileName(F_ROAD_LEFT_BORDER_HALF_TXT);
m530block_.setType(EnvironmentType.NOTHING);
m530objectMapPointBlock_.addEntry(new Point((short)0,(short)4),m530block_);
m530block_=Instances.newBlock();
m530block_.setWidth(W1);
m530block_.setHeight(H1);
m530block_.setTileFileName(F_EMPTY_TXT);
m530block_.setType(EnvironmentType.ROAD);
m530objectMapPointBlock_.addEntry(new Point((short)6,(short)3),m530block_);
m530block_=Instances.newBlock();
m530block_.setWidth(W14);
m530block_.setHeight(H3);
m530block_.setTileFileName(F_TOP_BOUND_14_3_TXT);
m530block_.setType(EnvironmentType.NOTHING);
m530objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m530block_);
m530block_=Instances.newBlock();
m530block_.setWidth(W7);
m530block_.setHeight(H1);
m530block_.setTileFileName(F_TOP_BOUND_7_1_TXT);
m530block_.setType(EnvironmentType.NOTHING);
m530objectMapPointBlock_.addEntry(new Point((short)7,(short)3),m530block_);
m530block_=Instances.newBlock();
m530block_.setWidth(W6);
m530block_.setHeight(H1);
m530block_.setTileFileName(F_TOP_BOUND_6_1_TXT);
m530block_.setType(EnvironmentType.NOTHING);
m530objectMapPointBlock_.addEntry(new Point((short)0,(short)3),m530block_);
m530block_=Instances.newBlock();
m530block_.setWidth(W6);
m530block_.setHeight(H3);
m530block_.setIndexApparition(N0);
m530block_.setTileFileName(F_GRASS_6_3_TXT);
m530block_.setType(EnvironmentType.GRASS);
m530objectMapPointBlock_.addEntry(new Point((short)4,(short)7),m530block_);
m530levelRoad_.setBlocks(m530objectMapPointBlock_);
return m530levelRoad_;
}
public static LevelIndoorPokemonCenter pc8(){
LevelIndoorPokemonCenter m531levelIndoorPokemonCenter_=Instances.newLevelIndoorPokemonCenter();
PointsPerson m531objectMapPointPerson_=new PointsPerson(new CollCapacity(4));
GerantPokemon m531gerantPokemon_=Instances.newGerantPokemon();
m531gerantPokemon_.setGerance(GeranceType.HEAL);
m531gerantPokemon_.setImageMiniFileName(F_BREEDER_F_TXT);
m531objectMapPointPerson_.addEntry(new Point((short)0,(short)5),m531gerantPokemon_);
Seller m531seller_=Instances.newSeller();
m531seller_.setSell(SellType.ITEM);
m531seller_.setItems(new StringList(I_SUPER_BALL,I_POTION));
m531seller_.setImageMiniFileName(F_SELLER_F_TXT);
m531objectMapPointPerson_.addEntry(new Point((short)9,(short)5),m531seller_);
m531seller_=Instances.newSeller();
m531seller_.setSell(SellType.MOVE);
m531seller_.setImageMiniFileName(F_SELLER_M_TXT);
m531objectMapPointPerson_.addEntry(new Point((short)9,(short)3),m531seller_);
m531seller_=Instances.newSeller();
m531seller_.setSell(SellType.TM);
Shorts m531shorts_=new Shorts(new CollCapacity(5));
m531shorts_.add((short)1);
m531shorts_.add((short)2);
m531shorts_.add((short)3);
m531shorts_.add((short)4);
m531shorts_.add((short)5);
m531seller_.setTm(m531shorts_);
m531seller_.setImageMiniFileName(F_SELLER_F_TXT);
m531objectMapPointPerson_.addEntry(new Point((short)9,(short)4),m531seller_);
m531levelIndoorPokemonCenter_.setGerants(m531objectMapPointPerson_);
m531levelIndoorPokemonCenter_.setStorageCoords(new Point((short)0,(short)8));
PointsBlock m531objectMapPointBlock_=new PointsBlock(new CollCapacity(1));
Block m531block_=Instances.newBlock();
m531block_.setWidth(W10);
m531block_.setHeight(H10);
m531block_.setTileFileName(F_BUILDING_INSIDE_TXT);
m531block_.setType(EnvironmentType.BUILDING);
m531objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m531block_);
m531levelIndoorPokemonCenter_.setBlocks(m531objectMapPointBlock_);
return m531levelIndoorPokemonCenter_;
}
public static LevelOutdoor po8(){
LevelOutdoor m532levelOutdoor_=Instances.newLevelOutdoor();
PointsBlock m532objectMapPointBlock_=new PointsBlock(new CollCapacity(19));
Block m532block_=Instances.newBlock();
m532block_.setWidth(W5);
m532block_.setHeight(H7);
m532block_.setTileFileName(F_CITY_ROAD_PT_4_8_TXT);
m532block_.setType(EnvironmentType.ROAD);
m532objectMapPointBlock_.addEntry(new Point((short)4,(short)8),m532block_);
m532block_=Instances.newBlock();
m532block_.setWidth(W4);
m532block_.setHeight(H5);
m532block_.setTileFileName(F_CITY_NOTHING_PT_0_4_TXT);
m532block_.setType(EnvironmentType.NOTHING);
m532objectMapPointBlock_.addEntry(new Point((short)0,(short)4),m532block_);
m532block_=Instances.newBlock();
m532block_.setWidth(W4);
m532block_.setHeight(H4);
m532block_.setTileFileName(F_CITY_NOTHING_PT_0_0_TXT);
m532block_.setType(EnvironmentType.NOTHING);
m532objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m532block_);
m532block_=Instances.newBlock();
m532block_.setWidth(W6);
m532block_.setHeight(H4);
m532block_.setTileFileName(F_CITY_ROAD_GRASS_PT_9_0_TXT);
m532block_.setType(EnvironmentType.ROAD);
m532objectMapPointBlock_.addEntry(new Point((short)9,(short)0),m532block_);
m532block_=Instances.newBlock();
m532block_.setWidth(W4);
m532block_.setHeight(H4);
m532block_.setTileFileName(F_CITY_NOTHING_PT_0_15_TXT);
m532block_.setType(EnvironmentType.NOTHING);
m532objectMapPointBlock_.addEntry(new Point((short)0,(short)15),m532block_);
m532block_=Instances.newBlock();
m532block_.setWidth(W6);
m532block_.setHeight(H11);
m532block_.setTileFileName(F_CITY_ROAD_PT_9_4_TXT);
m532block_.setType(EnvironmentType.ROAD);
m532objectMapPointBlock_.addEntry(new Point((short)9,(short)4),m532block_);
m532block_=Instances.newBlock();
m532block_.setWidth(W7);
m532block_.setHeight(H6);
m532block_.setTileFileName(F_CITY_ROAD_PT_15_9_TXT);
m532block_.setType(EnvironmentType.ROAD);
m532objectMapPointBlock_.addEntry(new Point((short)15,(short)9),m532block_);
m532block_=Instances.newBlock();
m532block_.setWidth(W7);
m532block_.setHeight(H4);
m532block_.setTileFileName(F_CITY_NOTHING_PT_15_0_TXT);
m532block_.setType(EnvironmentType.NOTHING);
m532objectMapPointBlock_.addEntry(new Point((short)15,(short)0),m532block_);
m532block_=Instances.newBlock();
m532block_.setWidth(W4);
m532block_.setHeight(H4);
m532block_.setTileFileName(F_CITY_NOTHING_PT_22_0_TXT);
m532block_.setType(EnvironmentType.NOTHING);
m532objectMapPointBlock_.addEntry(new Point((short)22,(short)0),m532block_);
m532block_=Instances.newBlock();
m532block_.setWidth(W4);
m532block_.setHeight(H5);
m532block_.setTileFileName(F_CITY_NOTHING_PT_22_4_TXT);
m532block_.setType(EnvironmentType.NOTHING);
m532objectMapPointBlock_.addEntry(new Point((short)22,(short)4),m532block_);
m532block_=Instances.newBlock();
m532block_.setWidth(W4);
m532block_.setHeight(H6);
m532block_.setTileFileName(F_CITY_ROAD_GRASS_PT_0_9_TXT);
m532block_.setType(EnvironmentType.ROAD);
m532objectMapPointBlock_.addEntry(new Point((short)0,(short)9),m532block_);
m532block_=Instances.newBlock();
m532block_.setWidth(W5);
m532block_.setHeight(H4);
m532block_.setTileFileName(F_CITY_NOTHING_PT_4_15_TXT);
m532block_.setType(EnvironmentType.NOTHING);
m532objectMapPointBlock_.addEntry(new Point((short)4,(short)15),m532block_);
m532block_=Instances.newBlock();
m532block_.setWidth(W4);
m532block_.setHeight(H6);
m532block_.setTileFileName(F_CITY_ROAD_GRASS_PT_22_9_TXT);
m532block_.setType(EnvironmentType.ROAD);
m532objectMapPointBlock_.addEntry(new Point((short)22,(short)9),m532block_);
m532block_=Instances.newBlock();
m532block_.setWidth(W6);
m532block_.setHeight(H4);
m532block_.setTileFileName(F_CITY_ROAD_GRASS_PT_9_15_TXT);
m532block_.setType(EnvironmentType.ROAD);
m532objectMapPointBlock_.addEntry(new Point((short)9,(short)15),m532block_);
m532block_=Instances.newBlock();
m532block_.setWidth(W7);
m532block_.setHeight(H5);
m532block_.setTileFileName(F_NOTHING_GYM_TXT);
m532block_.setType(EnvironmentType.NOTHING);
m532objectMapPointBlock_.addEntry(new Point((short)15,(short)4),m532block_);
m532block_=Instances.newBlock();
m532block_.setWidth(W7);
m532block_.setHeight(H4);
m532block_.setTileFileName(F_CITY_NOTHING_PT_15_15_TXT);
m532block_.setType(EnvironmentType.NOTHING);
m532objectMapPointBlock_.addEntry(new Point((short)15,(short)15),m532block_);
m532block_=Instances.newBlock();
m532block_.setWidth(W4);
m532block_.setHeight(H4);
m532block_.setTileFileName(F_CITY_NOTHING_PT_22_15_TXT);
m532block_.setType(EnvironmentType.NOTHING);
m532objectMapPointBlock_.addEntry(new Point((short)22,(short)15),m532block_);
m532block_=Instances.newBlock();
m532block_.setWidth(W5);
m532block_.setHeight(H4);
m532block_.setTileFileName(F_NOTHING_PK_CENTER_TXT);
m532block_.setType(EnvironmentType.NOTHING);
m532objectMapPointBlock_.addEntry(new Point((short)4,(short)4),m532block_);
m532block_=Instances.newBlock();
m532block_.setWidth(W5);
m532block_.setHeight(H4);
m532block_.setTileFileName(F_CITY_NOTHING_PT_4_0_TXT);
m532block_.setType(EnvironmentType.NOTHING);
m532objectMapPointBlock_.addEntry(new Point((short)4,(short)0),m532block_);
m532levelOutdoor_.setBlocks(m532objectMapPointBlock_);
return m532levelOutdoor_;
}
public static LevelRoad p9(){
LevelRoad m533levelRoad_ = Instances.newLevelRoad();
 CustList<AreaApparition> m533custListAreaApparition_=new  CustList<AreaApparition>(new CollCapacity(1));
m533custListAreaApparition_.add(Ar.p9l0a0());
m533levelRoad_.setWildPokemonAreas(m533custListAreaApparition_);
PointsDualFight m533objectMapPointDualFight_=new PointsDualFight(new CollCapacity(1));
m533objectMapPointDualFight_.addEntry(new Point((short)9,(short)7),TrDual.p9l0d0());
m533levelRoad_.setDualFights(m533objectMapPointDualFight_);
PointsBlock m533objectMapPointBlock_=new PointsBlock(new CollCapacity(4));
Block m533block_=Instances.newBlock();
m533block_.setWidth(W12);
m533block_.setHeight(H4);
m533block_.setTileFileName(F_ROAD_BOTTOM_BORDER_TXT);
m533block_.setType(EnvironmentType.NOTHING);
m533objectMapPointBlock_.addEntry(new Point((short)0,(short)10),m533block_);
m533block_=Instances.newBlock();
m533block_.setWidth(W12);
m533block_.setHeight(H4);
m533block_.setTileFileName(F_ROAD_TOP_BORDER_TXT);
m533block_.setType(EnvironmentType.NOTHING);
m533objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m533block_);
m533block_=Instances.newBlock();
m533block_.setWidth(W9);
m533block_.setHeight(H6);
m533block_.setTileFileName(F_ROAD_GRASS_9_6_TXT);
m533block_.setType(EnvironmentType.ROAD);
m533objectMapPointBlock_.addEntry(new Point((short)0,(short)4),m533block_);
m533block_=Instances.newBlock();
m533block_.setWidth(W3);
m533block_.setHeight(H6);
m533block_.setIndexApparition(N0);
m533block_.setTileFileName(F_GRASS_3_6_TXT);
m533block_.setType(EnvironmentType.GRASS);
m533objectMapPointBlock_.addEntry(new Point((short)9,(short)4),m533block_);
m533levelRoad_.setBlocks(m533objectMapPointBlock_);
return m533levelRoad_;
}
public static LevelLeague p10t0(){
LevelLeague m534levelLeague_=Instances.newLevelLeague();
m534levelLeague_.setTrainerCoords(new Point((short)4,(short)4));
m534levelLeague_.setTrainer(TrLeague.p10t0());
m534levelLeague_.setAccessPoint(new Point((short)4,(short)0));
m534levelLeague_.setNextLevelTarget(new Point((short)4,(short)9));
m534levelLeague_.setFileName(F_LINK_LEAGUE_LEVELS_TXT);
PointsBlock m534objectMapPointBlock_=new PointsBlock(new CollCapacity(1));
Block m534block_=Instances.newBlock();
m534block_.setWidth(W10);
m534block_.setHeight(H10);
m534block_.setTileFileName(F_BUILDING_10_10_TXT);
m534block_.setType(EnvironmentType.BUILDING);
m534objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m534block_);
m534levelLeague_.setBlocks(m534objectMapPointBlock_);
return m534levelLeague_;
}
public static LevelLeague p10t1(){
LevelLeague m535levelLeague_=Instances.newLevelLeague();
m535levelLeague_.setTrainerCoords(new Point((short)4,(short)4));
m535levelLeague_.setTrainer(TrLeague.p10t1());
m535levelLeague_.setAccessPoint(new Point((short)4,(short)0));
m535levelLeague_.setNextLevelTarget(new Point((short)4,(short)9));
m535levelLeague_.setFileName(F_LINK_LEAGUE_LEVELS_TXT);
PointsBlock m535objectMapPointBlock_=new PointsBlock(new CollCapacity(1));
Block m535block_=Instances.newBlock();
m535block_.setWidth(W10);
m535block_.setHeight(H10);
m535block_.setTileFileName(F_BUILDING_10_10_TXT);
m535block_.setType(EnvironmentType.BUILDING);
m535objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m535block_);
m535levelLeague_.setBlocks(m535objectMapPointBlock_);
return m535levelLeague_;
}
public static LevelRoad p11(){
LevelRoad m536levelRoad_ = Instances.newLevelRoad();
 CustList<AreaApparition> m536custListAreaApparition_=new  CustList<AreaApparition>(new CollCapacity(1));
m536custListAreaApparition_.add(Ar.p11l0a0());
m536levelRoad_.setWildPokemonAreas(m536custListAreaApparition_);
PointsWildPk m536objectMapPointWildPk_=new PointsWildPk(new CollCapacity(22));
m536objectMapPointWildPk_.addEntry(new Point((short)6,(short)9),Le.p11l0w0());
m536objectMapPointWildPk_.addEntry(new Point((short)8,(short)9),Le.p11l0w1());
m536objectMapPointWildPk_.addEntry(new Point((short)2,(short)4),Le.p11l0w2());
m536objectMapPointWildPk_.addEntry(new Point((short)8,(short)4),Le.p11l0w3());
m536objectMapPointWildPk_.addEntry(new Point((short)5,(short)9),Le.p11l0w4());
m536objectMapPointWildPk_.addEntry(new Point((short)9,(short)4),Le.p11l0w5());
m536objectMapPointWildPk_.addEntry(new Point((short)0,(short)9),Le.p11l0w6());
m536objectMapPointWildPk_.addEntry(new Point((short)5,(short)4),Le.p11l0w7());
m536objectMapPointWildPk_.addEntry(new Point((short)0,(short)4),Le.p11l0w8());
m536objectMapPointWildPk_.addEntry(new Point((short)2,(short)9),Le.p11l0w9());
m536objectMapPointWildPk_.addEntry(new Point((short)4,(short)9),Le.p11l0w10());
m536objectMapPointWildPk_.addEntry(new Point((short)3,(short)4),Le.p11l0w11());
m536objectMapPointWildPk_.addEntry(new Point((short)1,(short)9),Le.p11l0w12());
m536objectMapPointWildPk_.addEntry(new Point((short)1,(short)4),Le.p11l0w13());
m536objectMapPointWildPk_.addEntry(new Point((short)4,(short)4),Le.p11l0w14());
m536objectMapPointWildPk_.addEntry(new Point((short)10,(short)4),Le.p11l0w15());
m536objectMapPointWildPk_.addEntry(new Point((short)3,(short)9),Le.p11l0w16());
m536objectMapPointWildPk_.addEntry(new Point((short)7,(short)9),Le.p11l0w17());
m536objectMapPointWildPk_.addEntry(new Point((short)10,(short)9),Le.p11l0w18());
m536objectMapPointWildPk_.addEntry(new Point((short)9,(short)9),Le.p11l0w19());
m536objectMapPointWildPk_.addEntry(new Point((short)6,(short)4),Le.p11l0w20());
m536objectMapPointWildPk_.addEntry(new Point((short)7,(short)4),Le.p11l0w21());
m536levelRoad_.setLegendaryPks(m536objectMapPointWildPk_);
PointsBlock m536objectMapPointBlock_=new PointsBlock(new CollCapacity(4));
Block m536block_=Instances.newBlock();
m536block_.setWidth(W12);
m536block_.setHeight(H4);
m536block_.setTileFileName(F_ROAD_TOP_BORDER_TXT);
m536block_.setType(EnvironmentType.NOTHING);
m536objectMapPointBlock_.addEntry(new Point((short)0,(short)0),m536block_);
m536block_=Instances.newBlock();
m536block_.setWidth(W9);
m536block_.setHeight(H6);
m536block_.setTileFileName(F_ROAD_GRASS_9_6_TXT);
m536block_.setType(EnvironmentType.ROAD);
m536objectMapPointBlock_.addEntry(new Point((short)0,(short)4),m536block_);
m536block_=Instances.newBlock();
m536block_.setWidth(W3);
m536block_.setHeight(H6);
m536block_.setIndexApparition(N0);
m536block_.setTileFileName(F_GRASS_3_6_TXT);
m536block_.setType(EnvironmentType.GRASS);
m536objectMapPointBlock_.addEntry(new Point((short)9,(short)4),m536block_);
m536block_=Instances.newBlock();
m536block_.setWidth(W12);
m536block_.setHeight(H4);
m536block_.setTileFileName(F_ROAD_BOTTOM_BORDER_TXT);
m536block_.setType(EnvironmentType.NOTHING);
m536objectMapPointBlock_.addEntry(new Point((short)0,(short)10),m536block_);
m536levelRoad_.setBlocks(m536objectMapPointBlock_);
return m536levelRoad_;
}
}
