package code.scripts.confs;

import code.sml.*;
import code.util.CollCapacity;
import code.util.StringMap;

public final class HelpScriptConfPages {
    private static final String AFFICHAGE="affichage";
    private static final String AIDE="aide";
    private static final String AIDE_AU_JEU="aide_au_jeu";
    private static final String AIDE_GENERALE="aide_generale";
    private static final String ANNONCES="annonces";
    private static final String ARRET_MULTI="arret_multi";
    private static final String BELOTE="belote";
    private static final String CARTES_UTILISEES="cartes_utilisees";
    private static final String CHANGER_JEU="changer_jeu";
    private static final String CHARGER="charger";
    private static final String CHIEN="chien";
    private static final String CINQ_JOUEURS="cinq_joueurs";
    private static final String CONSEIL="conseil";
    private static final String CONTRAT="contrat";
    private static final String DISTRIBUTION="distribution";
    private static final String EDITER="editer";
    private static final String EN="en";
    private static final String ENTRAINEMENT="entrainement";
    private static final String EQUIPES="equipes";
    private static final String FICHIER="fichier";
    private static final String FIN_DE_LA_PARTIE="fin_de_la_partie";
    private static final String FIN_DE_PARTIE_DIFFERENTE="fin_de_partie_differente";
    private static final String FIN_PARTIE="fin_partie";
    private static final String FR="fr";
    private static final String INTERACTION="interaction";
    private static final String JEUX="jeux";
    private static final String JEU_DES_CARTES="jeu_des_cartes";
    private static final String JEU_DE_CHACUN_POUR_SOI="jeu_de_chacun_pour_soi";
    private static final String JEU_DE_MISERE="jeu_de_misere";
    private static final String JOUEURS="joueurs";
    private static final String LANCEMENT="lancement";
    private static final String LANGUE="langue";
    private static final String LOGICIEL="logiciel";
    private static final String MAINS_PLIS="mains_plis";
    private static final String MENUS="menus";
    private static final String NOUVELLES_ANNONCES="nouvelles_annonces";
    private static final String ORDRE_DES_CARTES="ordre_des_cartes";
    private static final String PARAMETRES="parametres";
    private static final String PARTIE="partie";
    private static final String PAUSE="pause";
    private static final String POSITION="position";
    private static final String PRESIDENT="president";
    private static final String P_0="0";
    private static final String P_1="1";
    private static final String P_2="2";
    private static final String P_3="3";
    private static final String P_4="4";
    private static final String P_5="5";
    private static final String P_6="6";
    private static final String P_7="7";
    private static final String P_8="8";
    private static final String QUATRE_JOUEURS_REP="quatre_joueurs_rep";
    private static final String QUITTER="quitter";
    private static final String SAUVEGARDER="sauvegarder";
    private static final String SIMULATION="simulation";
    private static final String SIX_JOUEURS="six_joueurs";
    private static final String SURCONTRAT="surcontrat";
    private static final String TAROT="tarot";
    private static final String TEMPORISATION="temporisation";
    private static final String TEXTE="texte";
    private static final String TROIS_JOUEURS="trois_joueurs";
    private static final String T_0="t_0";
    private static final String T_10="t_10";
    private static final String T_11="t_11";
    private static final String T_12="t_12";
    private static final String T_13="t_13";
    private static final String T_14="t_14";
    private static final String T_15="t_15";
    private static final String T_16="t_16";
    private static final String T_17="t_17";
    private static final String T_18="t_18";
    private static final String T_19="t_19";
    private static final String T_1="t_1";
    private static final String T_20="t_20";
    private static final String T_21="t_21";
    private static final String T_22="t_22";
    private static final String T_23="t_23";
    private static final String T_24="t_24";
    private static final String T_25="t_25";
    private static final String T_26="t_26";
    private static final String T_27="t_27";
    private static final String T_28="t_28";
    private static final String T_29="t_29";
    private static final String T_2="t_2";
    private static final String T_30="t_30";
    private static final String T_31="t_31";
    private static final String T_32="t_32";
    private static final String T_33="t_33";
    private static final String T_34="t_34";
    private static final String T_35="t_35";
    private static final String T_36="t_36";
    private static final String T_37="t_37";
    private static final String T_38="t_38";
    private static final String T_39="t_39";
    private static final String T_3="t_3";
    private static final String T_40="t_40";
    private static final String T_41="t_41";
    private static final String T_42="t_42";
    private static final String T_43="t_43";
    private static final String T_44="t_44";
    private static final String T_45="t_45";
    private static final String T_46="t_46";
    private static final String T_47="t_47";
    private static final String T_48="t_48";
    private static final String T_49="t_49";
    private static final String T_4="t_4";
    private static final String T_50="t_50";
    private static final String T_51="t_51";
    private static final String T_52="t_52";
    private static final String T_53="t_53";
    private static final String T_54="t_54";
    private static final String T_55="t_55";
    private static final String T_56="t_56";
    private static final String T_57="t_57";
    private static final String T_58="t_58";
    private static final String T_59="t_59";
    private static final String T_5="t_5";
    private static final String T_60="t_60";
    private static final String T_61="t_61";
    private static final String T_62="t_62";
    private static final String T_63="t_63";
    private static final String T_64="t_64";
    private static final String T_65="t_65";
    private static final String T_66="t_66";
    private static final String T_67="t_67";
    private static final String T_68="t_68";
    private static final String T_69="t_69";
    private static final String T_6="t_6";
    private static final String T_70="t_70";
    private static final String T_7="t_7";
    private static final String T_8="t_8";
    private static final String T_9="t_9";
    private static final String VARIANTES="variantes";
    private HelpScriptConfPages(){
    }
    public static StringMap<FullDocument> infoLg(){
        StringMap<FullDocument> map_ = new StringMap<FullDocument>();
        map_.addEntry(EN, info(en()));
        map_.addEntry(FR, info(fr()));
        return map_;
    }

    public static FullDocument info(StringMap<String> _ms) {
        FullDocument doc_ = DocumentBuilder.newXmlDocument(4);
        Element elt0_ = info(doc_, AIDE_GENERALE, P_0, _ms.getVal(T_0));
        Element elt1_ = info(doc_, LOGICIEL, P_0, _ms.getVal(T_1));
        Element elt2_ = info(doc_, MENUS, P_0, _ms.getVal(T_2));
        Element elt3_ = info(doc_, FICHIER, P_0, _ms.getVal(T_3));
        Element elt4_ = info(doc_, CHARGER, P_0, _ms.getVal(T_4));
        elt3_.appendChild(elt4_);
        Element elt5_ = info(doc_, SAUVEGARDER, P_1, _ms.getVal(T_5));
        elt3_.appendChild(elt5_);
        Element elt6_ = info(doc_, CHANGER_JEU, P_2, _ms.getVal(T_6));
        elt3_.appendChild(elt6_);
        Element elt7_ = info(doc_, QUITTER, P_3, _ms.getVal(T_7));
        elt3_.appendChild(elt7_);
        elt2_.appendChild(elt3_);
        Element elt8_ = info(doc_, PARTIE, P_1, _ms.getVal(T_8));
        Element elt9_ = info(doc_, CONSEIL, P_0, _ms.getVal(T_9));
        elt8_.appendChild(elt9_);
        Element elt10_ = info(doc_, PAUSE, P_1, _ms.getVal(T_10));
        elt8_.appendChild(elt10_);
        Element elt11_ = info(doc_, AIDE_AU_JEU, P_2, _ms.getVal(T_11));
        elt8_.appendChild(elt11_);
        Element elt12_ = info(doc_, MAINS_PLIS, P_3, _ms.getVal(T_12));
        elt8_.appendChild(elt12_);
        Element elt13_ = info(doc_, EQUIPES, P_4, _ms.getVal(T_13));
        elt8_.appendChild(elt13_);
        Element elt14_ = info(doc_, EDITER, P_5, _ms.getVal(T_14));
        Element elt15_ = info(doc_, BELOTE, P_0, _ms.getVal(T_15));
        elt14_.appendChild(elt15_);
        Element elt16_ = info(doc_, TAROT, P_1, _ms.getVal(T_16));
        elt14_.appendChild(elt16_);
        elt8_.appendChild(elt14_);
        Element elt17_ = info(doc_, SIMULATION, P_6, _ms.getVal(T_17));
        Element elt18_ = info(doc_, BELOTE, P_0, _ms.getVal(T_18));
        elt17_.appendChild(elt18_);
        Element elt19_ = info(doc_, TAROT, P_1, _ms.getVal(T_19));
        elt17_.appendChild(elt19_);
        elt8_.appendChild(elt17_);
        Element elt20_ = info(doc_, ENTRAINEMENT, P_7, _ms.getVal(T_20));
        elt8_.appendChild(elt20_);
        Element elt21_ = info(doc_, ARRET_MULTI, P_8, _ms.getVal(T_21));
        elt8_.appendChild(elt21_);
        elt2_.appendChild(elt8_);
        Element elt22_ = info(doc_, PARAMETRES, P_2, _ms.getVal(T_22));
        Element elt23_ = info(doc_, BELOTE, P_0, _ms.getVal(T_23));
        elt22_.appendChild(elt23_);
        Element elt24_ = info(doc_, TAROT, P_1, _ms.getVal(T_24));
        elt22_.appendChild(elt24_);
        Element elt25_ = info(doc_, JOUEURS, P_2, _ms.getVal(T_25));
        elt22_.appendChild(elt25_);
        Element elt26_ = info(doc_, LANCEMENT, P_3, _ms.getVal(T_26));
        elt22_.appendChild(elt26_);
        Element elt27_ = info(doc_, TEMPORISATION, P_4, _ms.getVal(T_27));
        elt22_.appendChild(elt27_);
        Element elt28_ = info(doc_, INTERACTION, P_5, _ms.getVal(T_28));
        elt22_.appendChild(elt28_);
        Element elt29_ = info(doc_, LANGUE, P_6, _ms.getVal(T_29));
        elt22_.appendChild(elt29_);
        Element elt30_ = info(doc_, AFFICHAGE, P_7, _ms.getVal(T_30));
        Element elt31_ = info(doc_, BELOTE, P_0, _ms.getVal(T_31));
        elt30_.appendChild(elt31_);
        Element elt32_ = info(doc_, TAROT, P_1, _ms.getVal(T_32));
        elt30_.appendChild(elt32_);
        elt22_.appendChild(elt30_);
        elt2_.appendChild(elt22_);
        Element elt33_ = info(doc_, AIDE, P_3, _ms.getVal(T_33));
        Element elt34_ = info(doc_, AIDE_GENERALE, P_0, _ms.getVal(T_34));
        elt33_.appendChild(elt34_);
        elt2_.appendChild(elt33_);
        elt1_.appendChild(elt2_);
        Element elt35_ = info(doc_, FIN_PARTIE, P_1, _ms.getVal(T_35));
        elt1_.appendChild(elt35_);
        elt0_.appendChild(elt1_);
        Element elt36_ = info(doc_, JEUX, P_1, _ms.getVal(T_36));
        Element elt37_ = info(doc_, BELOTE, P_0, _ms.getVal(T_37));
        Element elt38_ = info(doc_, CARTES_UTILISEES, P_0, _ms.getVal(T_38));
        elt37_.appendChild(elt38_);
        Element elt39_ = info(doc_, ORDRE_DES_CARTES, P_1, _ms.getVal(T_39));
        elt37_.appendChild(elt39_);
        Element elt40_ = info(doc_, DISTRIBUTION, P_2, _ms.getVal(T_40));
        elt37_.appendChild(elt40_);
        Element elt41_ = info(doc_, CONTRAT, P_3, _ms.getVal(T_41));
        elt37_.appendChild(elt41_);
        Element elt42_ = info(doc_, ANNONCES, P_4, _ms.getVal(T_42));
        elt37_.appendChild(elt42_);
        Element elt43_ = info(doc_, JEU_DES_CARTES, P_5, _ms.getVal(T_43));
        elt37_.appendChild(elt43_);
        Element elt44_ = info(doc_, FIN_DE_LA_PARTIE, P_6, _ms.getVal(T_44));
        elt37_.appendChild(elt44_);
        Element elt45_ = info(doc_, VARIANTES, P_7, _ms.getVal(T_45));
        Element elt46_ = info(doc_, SURCONTRAT, P_0, _ms.getVal(T_46));
        elt45_.appendChild(elt46_);
        Element elt47_ = info(doc_, FIN_DE_PARTIE_DIFFERENTE, P_1, _ms.getVal(T_47));
        elt45_.appendChild(elt47_);
        elt37_.appendChild(elt45_);
        elt36_.appendChild(elt37_);
        Element elt48_ = info(doc_, PRESIDENT, P_1, _ms.getVal(T_48));
        Element elt49_ = info(doc_, CARTES_UTILISEES, P_0, _ms.getVal(T_49));
        elt48_.appendChild(elt49_);
        Element elt50_ = info(doc_, ORDRE_DES_CARTES, P_1, _ms.getVal(T_50));
        elt48_.appendChild(elt50_);
        Element elt51_ = info(doc_, DISTRIBUTION, P_2, _ms.getVal(T_51));
        elt48_.appendChild(elt51_);
        Element elt52_ = info(doc_, JEU_DES_CARTES, P_3, _ms.getVal(T_52));
        elt48_.appendChild(elt52_);
        Element elt53_ = info(doc_, VARIANTES, P_4, _ms.getVal(T_53));
        elt48_.appendChild(elt53_);
        elt36_.appendChild(elt48_);
        Element elt54_ = info(doc_, TAROT, P_2, _ms.getVal(T_54));
        Element elt55_ = info(doc_, CARTES_UTILISEES, P_0, _ms.getVal(T_55));
        elt54_.appendChild(elt55_);
        Element elt56_ = info(doc_, ORDRE_DES_CARTES, P_1, _ms.getVal(T_56));
        elt54_.appendChild(elt56_);
        Element elt57_ = info(doc_, DISTRIBUTION, P_2, _ms.getVal(T_57));
        elt54_.appendChild(elt57_);
        Element elt58_ = info(doc_, CONTRAT, P_3, _ms.getVal(T_58));
        elt54_.appendChild(elt58_);
        Element elt59_ = info(doc_, CHIEN, P_4, _ms.getVal(T_59));
        elt54_.appendChild(elt59_);
        Element elt60_ = info(doc_, ANNONCES, P_5, _ms.getVal(T_60));
        elt54_.appendChild(elt60_);
        Element elt61_ = info(doc_, JEU_DES_CARTES, P_6, _ms.getVal(T_61));
        elt54_.appendChild(elt61_);
        Element elt62_ = info(doc_, FIN_DE_LA_PARTIE, P_7, _ms.getVal(T_62));
        elt54_.appendChild(elt62_);
        Element elt63_ = info(doc_, VARIANTES, P_8, _ms.getVal(T_63));
        Element elt64_ = info(doc_, TROIS_JOUEURS, P_0, _ms.getVal(T_64));
        elt63_.appendChild(elt64_);
        Element elt65_ = info(doc_, QUATRE_JOUEURS_REP, P_1, _ms.getVal(T_65));
        elt63_.appendChild(elt65_);
        Element elt66_ = info(doc_, CINQ_JOUEURS, P_2, _ms.getVal(T_66));
        elt63_.appendChild(elt66_);
        Element elt67_ = info(doc_, SIX_JOUEURS, P_3, _ms.getVal(T_67));
        elt63_.appendChild(elt67_);
        Element elt68_ = info(doc_, NOUVELLES_ANNONCES, P_4, _ms.getVal(T_68));
        elt63_.appendChild(elt68_);
        Element elt69_ = info(doc_, JEU_DE_MISERE, P_5, _ms.getVal(T_69));
        elt63_.appendChild(elt69_);
        Element elt70_ = info(doc_, JEU_DE_CHACUN_POUR_SOI, P_6, _ms.getVal(T_70));
        elt63_.appendChild(elt70_);
        elt54_.appendChild(elt63_);
        elt36_.appendChild(elt54_);
        elt0_.appendChild(elt36_);
        doc_.appendChild(elt0_);
        return doc_;
    }


    private static Element info(Document _doc, String _tag, String _one, String _two) {
        Element element_ = _doc.createElement(_tag);
        NamedNodeMap attributes_ = element_.getAttributes();
        attributes_.add(CoreDocument.createAttribute(POSITION,_one));
        attributes_.add(CoreDocument.createAttribute(TEXTE,_two));
        return element_;
    }
    static StringMap<String> en(){
        StringMap<String> e=new StringMap<String>(new CollCapacity(71));
        e.addEntry(T_0,"General help");
        e.addEntry(T_1,"Software");
        e.addEntry(T_2,"Menus");
        e.addEntry(T_3,"File");
        e.addEntry(T_4,"Load a game");
        e.addEntry(T_5,"Save a game");
        e.addEntry(T_6,"Change game");
        e.addEntry(T_7,"Quit");
        e.addEntry(T_8,"Game");
        e.addEntry(T_9,"Advise");
        e.addEntry(T_10,"Pause");
        e.addEntry(T_11,"Help for deal");
        e.addEntry(T_12,"Tricks and hands");
        e.addEntry(T_13,"Teams");
        e.addEntry(T_14,"Edit");
        e.addEntry(T_15,"Belote");
        e.addEntry(T_16,"Tarot");
        e.addEntry(T_17,"Demo");
        e.addEntry(T_18,"Belote");
        e.addEntry(T_19,"Tarot");
        e.addEntry(T_20,"Tarot training");
        e.addEntry(T_21,"Stop playing by network");
        e.addEntry(T_22,"Parameters");
        e.addEntry(T_23,"Belote");
        e.addEntry(T_24,"Tarot");
        e.addEntry(T_25,"Players");
        e.addEntry(T_26,"Launching option");
        e.addEntry(T_27,"Timing for playing");
        e.addEntry(T_28,"Interacting with cards");
        e.addEntry(T_29,"Language");
        e.addEntry(T_30,"Displaying");
        e.addEntry(T_31,"Belote");
        e.addEntry(T_32,"Tarot");
        e.addEntry(T_33,"Help");
        e.addEntry(T_34,"General help");
        e.addEntry(T_35,"End of deal");
        e.addEntry(T_36,"Games");
        e.addEntry(T_37,"Belote");
        e.addEntry(T_38,"Used cards");
        e.addEntry(T_39,"Order of cards");
        e.addEntry(T_40,"Dealing");
        e.addEntry(T_41,"Bid");
        e.addEntry(T_42,"Declaring");
        e.addEntry(T_43,"Playing cards");
        e.addEntry(T_44,"End of deal");
        e.addEntry(T_45,"Variants");
        e.addEntry(T_46,"Surcontrat");
        e.addEntry(T_47,"Different end of game");
        e.addEntry(T_48,"President");
        e.addEntry(T_49,"Used cards");
        e.addEntry(T_50,"Order of cards");
        e.addEntry(T_51,"Dealing");
        e.addEntry(T_52,"Playing cards");
        e.addEntry(T_53,"Variants");
        e.addEntry(T_54,"Tarot");
        e.addEntry(T_55,"Used cards");
        e.addEntry(T_56,"Order of cards");
        e.addEntry(T_57,"Dealing");
        e.addEntry(T_58,"Bid");
        e.addEntry(T_59,"Dog");
        e.addEntry(T_60,"Declaring");
        e.addEntry(T_61,"Playing cards");
        e.addEntry(T_62,"End of deal");
        e.addEntry(T_63,"Variants");
        e.addEntry(T_64,"3 players");
        e.addEntry(T_65,"4 players (repartition)");
        e.addEntry(T_66,"5 players");
        e.addEntry(T_67,"6 players");
        e.addEntry(T_68,"New declaring");
        e.addEntry(T_69,"Discard game");
        e.addEntry(T_70,"One for one game");
        return e;

    }

    static StringMap<String> fr(){
        StringMap<String> f=new StringMap<String>(new CollCapacity(71));
        f.addEntry(T_0,"Aide g&#233;n&#233;rale");
        f.addEntry(T_1,"Logiciel");
        f.addEntry(T_2,"Menus");
        f.addEntry(T_3,"Fichier");
        f.addEntry(T_4,"Charger une partie");
        f.addEntry(T_5,"Sauvegarder une partie");
        f.addEntry(T_6,"Changer de jeu");
        f.addEntry(T_7,"Quitter");
        f.addEntry(T_8,"Partie");
        f.addEntry(T_9,"Conseil");
        f.addEntry(T_10,"Pause");
        f.addEntry(T_11,"Aide au jeu");
        f.addEntry(T_12,"Mains et plis");
        f.addEntry(T_13,"Equipes");
        f.addEntry(T_14,"Editer");
        f.addEntry(T_15,"Belote");
        f.addEntry(T_16,"Tarot");
        f.addEntry(T_17,"Demo");
        f.addEntry(T_18,"Belote");
        f.addEntry(T_19,"Tarot");
        f.addEntry(T_20,"Entra&#238;nement");
        f.addEntry(T_21,"Arr&#234;ter de jouer en r&#233;seau");
        f.addEntry(T_22,"Param&#232;tres");
        f.addEntry(T_23,"Belote");
        f.addEntry(T_24,"Tarot");
        f.addEntry(T_25,"Joueurs");
        f.addEntry(T_26,"Option de lancement");
        f.addEntry(T_27,"Temporisation du jeu");
        f.addEntry(T_28,"Interaction avec les cartes");
        f.addEntry(T_29,"Langue");
        f.addEntry(T_30,"Affichage");
        f.addEntry(T_31,"Belote");
        f.addEntry(T_32,"Tarot");
        f.addEntry(T_33,"Aide");
        f.addEntry(T_34,"Aide g&#233;n&#233;rale");
        f.addEntry(T_35,"Fin de partie");
        f.addEntry(T_36,"Jeux");
        f.addEntry(T_37,"Belote");
        f.addEntry(T_38,"Cartes utilis&#233;es");
        f.addEntry(T_39,"Ordre des cartes");
        f.addEntry(T_40,"Distribution");
        f.addEntry(T_41,"Contrat");
        f.addEntry(T_42,"Annonces");
        f.addEntry(T_43,"Jeu des cartes");
        f.addEntry(T_44,"Fin de la partie");
        f.addEntry(T_45,"Variantes");
        f.addEntry(T_46,"Surcontrat");
        f.addEntry(T_47,"Fin de partie diff&#233;rente");
        f.addEntry(T_48,"Pr&#233;sident");
        f.addEntry(T_49,"Cartes utilis&#233;es");
        f.addEntry(T_50,"Ordre des cartes");
        f.addEntry(T_51,"Distribution");
        f.addEntry(T_52,"Jeu des cartes");
        f.addEntry(T_53,"Variantes");
        f.addEntry(T_54,"Tarot");
        f.addEntry(T_55,"Cartes utilis&#233;es");
        f.addEntry(T_56,"Ordre des cartes");
        f.addEntry(T_57,"Distribution");
        f.addEntry(T_58,"Contrat");
        f.addEntry(T_59,"Chien");
        f.addEntry(T_60,"Annonces");
        f.addEntry(T_61,"Jeu des cartes");
        f.addEntry(T_62,"Fin de la partie");
        f.addEntry(T_63,"Variantes");
        f.addEntry(T_64,"3 joueurs");
        f.addEntry(T_65,"4 joueurs (r&#233;partition)");
        f.addEntry(T_66,"5 joueurs");
        f.addEntry(T_67,"6 joueurs");
        f.addEntry(T_68,"Nouvelles annonces");
        f.addEntry(T_69,"Jeu de mis&#232;re");
        f.addEntry(T_70,"Jeu de chacun pour soi");
        return f;

    }

}

