package code.scripts.pages.cards;
import code.bean.*;
import code.sml.util.*;
public final class HelpCards41 extends AbsHelpCards {
public void format(IntBeanBuilderHelperCommon _i, TranslationsLg _lg) {
formatMessage(_i,_lg,MessagesHelpCards.AIDE_GENERALE_LOGICIEL_MENUS_FICHIER_SAUVEGARDER,MessagesHelpCards41.M_41_0);
formatMessage(_i,_lg,MessagesHelpCards.AIDE_GENERALE_LOGICIEL_MENUS_FICHIER_SAUVEGARDER,MessagesHelpCards41.M_41_1);
formatMessage(_i,_lg,MessagesHelpCards.AIDE_GENERALE_LOGICIEL_MENUS_FICHIER_SAUVEGARDER,MessagesHelpCards41.M_41_2);
formatMessage(_i,_lg,MessagesHelpCards.AIDE_GENERALE_LOGICIEL_MENUS_FICHIER_SAUVEGARDER,MessagesHelpCards41.M_41_3);
formatMessage(_i,_lg,MessagesHelpCards.AIDE_GENERALE_LOGICIEL_MENUS_FICHIER_SAUVEGARDER,MessagesHelpCards41.M_41_4);
formatMessage(_i,_lg,MessagesHelpCards.AIDE_GENERALE_LOGICIEL_MENUS_FICHIER_SAUVEGARDER,MessagesHelpCards41.M_41_5);
_i.getOrderedLists().add(0);
elementOrd(_i,_lg,MessagesHelpCards.AIDE_GENERALE_LOGICIEL_MENUS_FICHIER_SAUVEGARDER,MessagesHelpCards41.M_41_6);
elementOrd(_i,_lg,MessagesHelpCards.AIDE_GENERALE_LOGICIEL_MENUS_FICHIER_SAUVEGARDER,MessagesHelpCards41.M_41_7);
elementOrd(_i,_lg,MessagesHelpCards.AIDE_GENERALE_LOGICIEL_MENUS_FICHIER_SAUVEGARDER,MessagesHelpCards41.M_41_8);
_i.getOrderedLists().removeQuicklyLast();
formatMessage(_i,_lg,MessagesHelpCards.AIDE_GENERALE_LOGICIEL_MENUS_FICHIER_SAUVEGARDER,MessagesHelpCards41.M_41_9);
formatMessage(_i,_lg,MessagesHelpCards.AIDE_GENERALE_LOGICIEL_MENUS_FICHIER_SAUVEGARDER,MessagesHelpCards41.M_41_10);
formatMessage(_i,_lg,MessagesHelpCards.AIDE_GENERALE_LOGICIEL_MENUS_FICHIER_SAUVEGARDER,MessagesHelpCards41.M_41_11);
formatMessage(_i,_lg,MessagesHelpCards.AIDE_GENERALE_LOGICIEL_MENUS_FICHIER_SAUVEGARDER,MessagesHelpCards41.M_41_12);
formatMessage(_i,_lg,MessagesHelpCards.AIDE_GENERALE_LOGICIEL_MENUS_FICHIER_SAUVEGARDER,MessagesHelpCards41.M_41_13);
formatMessage(_i,_lg,MessagesHelpCards.AIDE_GENERALE_LOGICIEL_MENUS_FICHIER_SAUVEGARDER,MessagesHelpCards41.M_41_14);
}
}
