package code.scripts.pages.cards;
import code.bean.*;
import code.sml.util.*;
public final class HelpCards7 extends AbsHelpCards {
public void format(IntBeanBuilderHelperCommon _i, TranslationsLg _lg) {
formatMessage(_i,_lg,MessagesHelpCards.AIDE_GENERALE_JEUX_BELOTE_VARIANTES_FIN_DE_PARTIE_DIFFERENTE,MessagesHelpCards7.M_7_0);
formatMessage(_i,_lg,MessagesHelpCards.AIDE_GENERALE_JEUX_BELOTE_VARIANTES_FIN_DE_PARTIE_DIFFERENTE,MessagesHelpCards7.M_7_1);
formatMessage(_i,_lg,MessagesHelpCards.AIDE_GENERALE_JEUX_BELOTE_VARIANTES_FIN_DE_PARTIE_DIFFERENTE,MessagesHelpCards7.M_7_2);
_i.getOrderedLists().add(0);
elementOrd(_i,_lg,MessagesHelpCards.AIDE_GENERALE_JEUX_BELOTE_VARIANTES_FIN_DE_PARTIE_DIFFERENTE,MessagesHelpCards7.M_7_3);
formatMessage(_i,_lg,1,MessagesHelpCards.AIDE_GENERALE_JEUX_BELOTE_VARIANTES_FIN_DE_PARTIE_DIFFERENTE,MessagesHelpCards7.M_7_4);
formatMessage(_i,_lg,1,MessagesHelpCards.AIDE_GENERALE_JEUX_BELOTE_VARIANTES_FIN_DE_PARTIE_DIFFERENTE,MessagesHelpCards7.M_7_5);
formatMessage(_i,_lg,1,MessagesHelpCards.AIDE_GENERALE_JEUX_BELOTE_VARIANTES_FIN_DE_PARTIE_DIFFERENTE,MessagesHelpCards7.M_7_6);
formatMessage(_i,_lg,1,MessagesHelpCards.AIDE_GENERALE_JEUX_BELOTE_VARIANTES_FIN_DE_PARTIE_DIFFERENTE,MessagesHelpCards7.M_7_7);
elementOrd(_i,_lg,MessagesHelpCards.AIDE_GENERALE_JEUX_BELOTE_VARIANTES_FIN_DE_PARTIE_DIFFERENTE,MessagesHelpCards7.M_7_8);
formatMessage(_i,_lg,1,MessagesHelpCards.AIDE_GENERALE_JEUX_BELOTE_VARIANTES_FIN_DE_PARTIE_DIFFERENTE,MessagesHelpCards7.M_7_9);
formatMessage(_i,_lg,1,MessagesHelpCards.AIDE_GENERALE_JEUX_BELOTE_VARIANTES_FIN_DE_PARTIE_DIFFERENTE,MessagesHelpCards7.M_7_10);
formatMessage(_i,_lg,1,MessagesHelpCards.AIDE_GENERALE_JEUX_BELOTE_VARIANTES_FIN_DE_PARTIE_DIFFERENTE,MessagesHelpCards7.M_7_11);
elementOrd(_i,_lg,MessagesHelpCards.AIDE_GENERALE_JEUX_BELOTE_VARIANTES_FIN_DE_PARTIE_DIFFERENTE,MessagesHelpCards7.M_7_12);
formatMessage(_i,_lg,1,MessagesHelpCards.AIDE_GENERALE_JEUX_BELOTE_VARIANTES_FIN_DE_PARTIE_DIFFERENTE,MessagesHelpCards7.M_7_13);
formatMessage(_i,_lg,1,MessagesHelpCards.AIDE_GENERALE_JEUX_BELOTE_VARIANTES_FIN_DE_PARTIE_DIFFERENTE,MessagesHelpCards7.M_7_14);
formatMessage(_i,_lg,1,MessagesHelpCards.AIDE_GENERALE_JEUX_BELOTE_VARIANTES_FIN_DE_PARTIE_DIFFERENTE,MessagesHelpCards7.M_7_15);
_i.getOrderedLists().removeQuicklyLast();
}
}
