package code.scripts.confs;

import cards.consts.*;
import code.bean.nat.NatDualConfigurationContext;
import code.scripts.imgs.cards.*;
import code.util.*;

public final class HelpScriptPagesImgs {
    private HelpScriptPagesImgs() {
    }
    public static StringMap<NatDualConfigurationContext> ct(){
        StringMap<NatDualConfigurationContext> m = new StringMap<NatDualConfigurationContext>(new CollCapacity(71));
        m.addEntry("aide_generale",initAnaData("aide_generale"));
        m.addEntry("aide_generale/logiciel",initAnaData("aide_generale/logiciel"));
        m.addEntry("aide_generale/jeux",initAnaData("aide_generale/jeux"));
        m.addEntry("aide_generale/logiciel/menus",initAnaData("aide_generale/logiciel/menus"));
        m.addEntry("aide_generale/logiciel/fin_partie",initAnaData("aide_generale/logiciel/fin_partie"));
        m.addEntry("aide_generale/jeux/belote",initAnaData("aide_generale/jeux/belote"));
        m.addEntry("aide_generale/jeux/president",initAnaData("aide_generale/jeux/president"));
        m.addEntry("aide_generale/jeux/tarot",initAnaData("aide_generale/jeux/tarot"));
        m.addEntry("aide_generale/logiciel/menus/fichier",initAnaData("aide_generale/logiciel/menus/fichier"));
        m.addEntry("aide_generale/logiciel/menus/partie",initAnaData("aide_generale/logiciel/menus/partie"));
        m.addEntry("aide_generale/logiciel/menus/parametres",initAnaData("aide_generale/logiciel/menus/parametres"));
        m.addEntry("aide_generale/logiciel/menus/aide",initAnaData("aide_generale/logiciel/menus/aide"));
        m.addEntry("aide_generale/jeux/belote/cartes_utilisees",initAnaData("aide_generale/jeux/belote/cartes_utilisees"));
        m.addEntry("aide_generale/jeux/belote/ordre_des_cartes",initAnaData("aide_generale/jeux/belote/ordre_des_cartes"));
        m.addEntry("aide_generale/jeux/belote/distribution",initAnaData("aide_generale/jeux/belote/distribution"));
        m.addEntry("aide_generale/jeux/belote/contrat",initAnaData("aide_generale/jeux/belote/contrat"));
        m.addEntry("aide_generale/jeux/belote/annonces",initAnaData("aide_generale/jeux/belote/annonces"));
        m.addEntry("aide_generale/jeux/belote/jeu_des_cartes",initAnaData("aide_generale/jeux/belote/jeu_des_cartes"));
        m.addEntry("aide_generale/jeux/belote/fin_de_la_partie",initAnaData("aide_generale/jeux/belote/fin_de_la_partie"));
        m.addEntry("aide_generale/jeux/belote/variantes",initAnaData("aide_generale/jeux/belote/variantes"));
        m.addEntry("aide_generale/jeux/president/cartes_utilisees",initAnaData("aide_generale/jeux/president/cartes_utilisees"));
        m.addEntry("aide_generale/jeux/president/ordre_des_cartes",initAnaData("aide_generale/jeux/president/ordre_des_cartes"));
        m.addEntry("aide_generale/jeux/president/distribution",initAnaData("aide_generale/jeux/president/distribution"));
        m.addEntry("aide_generale/jeux/president/jeu_des_cartes",initAnaData("aide_generale/jeux/president/jeu_des_cartes"));
        m.addEntry("aide_generale/jeux/president/variantes",initAnaData("aide_generale/jeux/president/variantes"));
        m.addEntry("aide_generale/jeux/tarot/cartes_utilisees",initAnaData("aide_generale/jeux/tarot/cartes_utilisees"));
        m.addEntry("aide_generale/jeux/tarot/ordre_des_cartes",initAnaData("aide_generale/jeux/tarot/ordre_des_cartes"));
        m.addEntry("aide_generale/jeux/tarot/distribution",initAnaData("aide_generale/jeux/tarot/distribution"));
        m.addEntry("aide_generale/jeux/tarot/contrat",initAnaData("aide_generale/jeux/tarot/contrat"));
        m.addEntry("aide_generale/jeux/tarot/chien",initAnaData("aide_generale/jeux/tarot/chien"));
        m.addEntry("aide_generale/jeux/tarot/annonces",initAnaData("aide_generale/jeux/tarot/annonces"));
        m.addEntry("aide_generale/jeux/tarot/jeu_des_cartes",initAnaData("aide_generale/jeux/tarot/jeu_des_cartes"));
        m.addEntry("aide_generale/jeux/tarot/fin_de_la_partie",initAnaData("aide_generale/jeux/tarot/fin_de_la_partie"));
        m.addEntry("aide_generale/jeux/tarot/variantes",initAnaData("aide_generale/jeux/tarot/variantes"));
        m.addEntry("aide_generale/logiciel/menus/fichier/charger",initAnaData("aide_generale/logiciel/menus/fichier/charger"));
        m.addEntry("aide_generale/logiciel/menus/fichier/sauvegarder",initAnaData("aide_generale/logiciel/menus/fichier/sauvegarder"));
        m.addEntry("aide_generale/logiciel/menus/fichier/changer_jeu",initAnaData("aide_generale/logiciel/menus/fichier/changer_jeu"));
        m.addEntry("aide_generale/logiciel/menus/fichier/quitter",initAnaData("aide_generale/logiciel/menus/fichier/quitter"));
        m.addEntry("aide_generale/logiciel/menus/partie/conseil",initAnaData("aide_generale/logiciel/menus/partie/conseil"));
        m.addEntry("aide_generale/logiciel/menus/partie/pause",initAnaData("aide_generale/logiciel/menus/partie/pause"));
        m.addEntry("aide_generale/logiciel/menus/partie/aide_au_jeu",initAnaData("aide_generale/logiciel/menus/partie/aide_au_jeu"));
        m.addEntry("aide_generale/logiciel/menus/partie/mains_plis",initAnaData("aide_generale/logiciel/menus/partie/mains_plis"));
        m.addEntry("aide_generale/logiciel/menus/partie/equipes",initAnaData("aide_generale/logiciel/menus/partie/equipes"));
        m.addEntry("aide_generale/logiciel/menus/partie/editer",initAnaData("aide_generale/logiciel/menus/partie/editer"));
        m.addEntry("aide_generale/logiciel/menus/partie/simulation",initAnaData("aide_generale/logiciel/menus/partie/simulation"));
        m.addEntry("aide_generale/logiciel/menus/partie/entrainement",initAnaData("aide_generale/logiciel/menus/partie/entrainement"));
        m.addEntry("aide_generale/logiciel/menus/partie/arret_multi",initAnaData("aide_generale/logiciel/menus/partie/arret_multi"));
        m.addEntry("aide_generale/logiciel/menus/parametres/belote",initAnaData("aide_generale/logiciel/menus/parametres/belote"));
        m.addEntry("aide_generale/logiciel/menus/parametres/tarot",initAnaData("aide_generale/logiciel/menus/parametres/tarot"));
        m.addEntry("aide_generale/logiciel/menus/parametres/joueurs",initAnaData("aide_generale/logiciel/menus/parametres/joueurs"));
        m.addEntry("aide_generale/logiciel/menus/parametres/lancement",initAnaData("aide_generale/logiciel/menus/parametres/lancement"));
        m.addEntry("aide_generale/logiciel/menus/parametres/temporisation",initAnaData("aide_generale/logiciel/menus/parametres/temporisation"));
        m.addEntry("aide_generale/logiciel/menus/parametres/interaction",initAnaData("aide_generale/logiciel/menus/parametres/interaction"));
        m.addEntry("aide_generale/logiciel/menus/parametres/langue",initAnaData("aide_generale/logiciel/menus/parametres/langue"));
        m.addEntry("aide_generale/logiciel/menus/parametres/affichage",initAnaData("aide_generale/logiciel/menus/parametres/affichage"));
        m.addEntry("aide_generale/logiciel/menus/aide/aide_generale",initAnaData("aide_generale/logiciel/menus/aide/aide_generale"));
        m.addEntry("aide_generale/jeux/belote/variantes/surcontrat",initAnaData("aide_generale/jeux/belote/variantes/surcontrat"));
        m.addEntry("aide_generale/jeux/belote/variantes/fin_de_partie_differente",initAnaData("aide_generale/jeux/belote/variantes/fin_de_partie_differente"));
        m.addEntry("aide_generale/jeux/tarot/variantes/trois_joueurs",initAnaData("aide_generale/jeux/tarot/variantes/trois_joueurs"));
        m.addEntry("aide_generale/jeux/tarot/variantes/quatre_joueurs_rep",initAnaData("aide_generale/jeux/tarot/variantes/quatre_joueurs_rep"));
        m.addEntry("aide_generale/jeux/tarot/variantes/cinq_joueurs",initAnaData("aide_generale/jeux/tarot/variantes/cinq_joueurs"));
        m.addEntry("aide_generale/jeux/tarot/variantes/six_joueurs",initAnaData("aide_generale/jeux/tarot/variantes/six_joueurs"));
        m.addEntry("aide_generale/jeux/tarot/variantes/nouvelles_annonces",initAnaData("aide_generale/jeux/tarot/variantes/nouvelles_annonces"));
        m.addEntry("aide_generale/jeux/tarot/variantes/jeu_de_misere",initAnaData("aide_generale/jeux/tarot/variantes/jeu_de_misere"));
        m.addEntry("aide_generale/jeux/tarot/variantes/jeu_de_chacun_pour_soi",initAnaData("aide_generale/jeux/tarot/variantes/jeu_de_chacun_pour_soi"));
        m.addEntry("aide_generale/logiciel/menus/partie/editer/belote",initAnaData("aide_generale/logiciel/menus/partie/editer/belote"));
        m.addEntry("aide_generale/logiciel/menus/partie/editer/tarot",initAnaData("aide_generale/logiciel/menus/partie/editer/tarot"));
        m.addEntry("aide_generale/logiciel/menus/partie/simulation/belote",initAnaData("aide_generale/logiciel/menus/partie/simulation/belote"));
        m.addEntry("aide_generale/logiciel/menus/partie/simulation/tarot",initAnaData("aide_generale/logiciel/menus/partie/simulation/tarot"));
        m.addEntry("aide_generale/logiciel/menus/parametres/affichage/belote",initAnaData("aide_generale/logiciel/menus/parametres/affichage/belote"));
        m.addEntry("aide_generale/logiciel/menus/parametres/affichage/tarot",initAnaData("aide_generale/logiciel/menus/parametres/affichage/tarot"));
        return m;
    }
    public static NatDualConfigurationContext initAnaData(String _prop){
        NatDualConfigurationContext d = new NatDualConfigurationContext();
        d.setMessagesFolder("");
        StringMap<String> p = new StringMap<String>(new CollCapacity(1));
        p.addEntry("msg",_prop);
        d.setProperties(p);
        StringList a = new StringList(new CollCapacity(78));
        a.add(CardsInit.FOLDER+CouleurValeur.EXCUSE+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_21+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_20+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_19+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_18+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_17+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_16+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_15+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_14+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_13+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_12+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_11+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_10+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_9+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_8+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_7+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_6+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_5+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_4+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_3+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_2+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.TRUMP_1+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.HEART_KING+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.HEART_QUEEN+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.HEART_KNIGHT+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.HEART_JACK+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.HEART_10+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.HEART_9+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.HEART_8+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.HEART_7+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.HEART_6+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.HEART_5+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.HEART_4+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.HEART_3+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.HEART_2+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.HEART_1+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.SPADE_KING+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.SPADE_QUEEN+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.SPADE_KNIGHT+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.SPADE_JACK+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.SPADE_10+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.SPADE_9+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.SPADE_8+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.SPADE_7+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.SPADE_6+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.SPADE_5+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.SPADE_4+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.SPADE_3+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.SPADE_2+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.SPADE_1+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.DIAMOND_KING+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.DIAMOND_QUEEN+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.DIAMOND_KNIGHT+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.DIAMOND_JACK+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.DIAMOND_10+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.DIAMOND_9+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.DIAMOND_8+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.DIAMOND_7+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.DIAMOND_6+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.DIAMOND_5+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.DIAMOND_4+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.DIAMOND_3+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.DIAMOND_2+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.DIAMOND_1+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.CLUB_KING+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.CLUB_QUEEN+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.CLUB_KNIGHT+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.CLUB_JACK+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.CLUB_10+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.CLUB_9+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.CLUB_8+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.CLUB_7+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.CLUB_6+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.CLUB_5+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.CLUB_4+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.CLUB_3+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.CLUB_2+CardsInit.EXT);
        a.add(CardsInit.FOLDER+CouleurValeur.CLUB_1+CardsInit.EXT);
        d.setAddedFiles(a);
        return d;
    }

}
