package code.scripts.pages.aiki;
final class MesDataSimulationSimulation{
private MesDataSimulationSimulation(){}
static String en(){
String f="title=Simulation of fights\n";
f+="title_param=Simulation of fights {0}/8\n";
f+="win_pts=Difficulty of winning points\n";
f+="allow_catching_ko=Allow catching ko pokemon\n";
f+="allow_switch_places=Allow swicthing places at the front of battle at the end of round\n";
f+="win_trainer_exp=Rate of winning experience points de gain de points while a fight against a foe\n";
f+="winning_exp_pts_fight=Rate of winning experience points\n";
f+="rate_issue={0} is not a valid rate.\n";
f+="short_issue={0} is not a valid integer.\n";
f+="end_fight=End of fight if a team is ko.\n";
f+="iv_player=Iv of your pokemon\n";
f+="iv_foe=Iv of the pokemon of your foes\n";
f+="flee=Flee always possible\n";
f+="restored_moves=Healed moves of your pokemon at the end of fight\n";
f+="closing=The moves wth single target can achieve any foe\n";
f+="random_wild=Random appearing pokemon\n";
f+="skip_learn=Do not learnt the already known moves\n";
f+="rate_win_money_base=Rate of won money between winning money while a victory and winning base\n";
f+="rate_win_money_loose=Rate of lost money between loss while a defeat and winning money while a victory\n";
f+="law_choice_player=Choice of averages of damage rate for your pokemon\n";
f+="law_choice_foe=Choice of averages of damage rate for the pokemon of your foes\n";
f+="rate_damage_ev=Rate\n";
f+="rate_damage=Probability\n";
f+="no_fight=Fight number\n";
f+="cancel=Cancel\n";
f+="cancel_evo=Cancel the last evolution\n";
f+="disable_evos=Keep the moves while the simulation >>\n";
f+="select_foe_pk=Pokemon of the foe trainer\n";
f+="select_ally_pk=Pokemon of the ally trainer\n";
f+="select_pk=Select your pokemon team\n";
f+="select_pk_evos=Select the evolutions of your pokemon\n";
f+="select_sent_pk=Select your sent pokemon for each round\n";
f+="select_pk_moves=Select the moves of your pokemon for each round\n";
f+="select_pk_move_target=Select the move and the target of your pokemon for each round\n";
f+="select_pk_evos_after_fight=Select the evolutions of your pokemon after the fight\n";
f+="add=Add\n";
f+="remove=Remove\n";
f+="select=Select\n";
f+="edit=Edit\n";
f+="selected=Selected\n";
f+="name_pk=Name\n";
f+="ability_pk=Ability\n";
f+="item_pk=Item\n";
f+="level_pk=Level\n";
f+="gender_pk=Gender\n";
f+="moves_pk=Moves\n";
f+="exp_pk=Won experience\n";
f+="exp_pk_rem=Remaining experience for the next level\n";
f+="happiness_pk=Happiness\n";
f+="ev=Ev in statististics\n";
f+="heal_hp=Heal health points\n";
f+="remaining_hp=Remaining health points\n";
f+="catching_ball=Catching ball\n";
f+="multiplicity=Place on the ground\n";
f+="round=Round number\n";
f+="cancel_moves=Cancel choice of moves set\n";
f+="ally_choice=Chosen ally pokemon\n";
f+="evolution=Evolution\n";
f+="hp_rate=Remaining life rate\n";
f+="ko_player_fighters=Ko pokemon of the player\n";
f+="ko_foe_fighters=Ko pokemon ko of the foe trainer\n";
f+="not_ko_foe_fighters=Not ko front pokemon of the foe trainer\n";
f+="issue_rules=Rules issue\n";
f+="issue_rules_moves=Issue of moves choice\n";
f+="issue_rules_learn=Issue of learning moves choice or evolving\n";
f+="issue_rules_switch=Issue of switching\n";
f+="issue_random=Issue of random editing\n";
f+="issue_sending=Issue of sending\n";
f+="issue_using=Issue of using a move for a pokemon player\n";
f+="issue_too_hard=Issue of hard simulation\n";
f+="issue_after_fight=Bad choice of evolutions after the fight\n";
f+="display_comments=Display comments\n";
f+="hide_comments=Hide comments\n";
f+="free_teams=Free teams\n";
f+="multiplicity_fight=Multiplicity of the fight\n";
f+="ally_pk=Ally pokemon\n";
f+="available_moves=Available moves for pokemon player only\n";
f+="search=Search\n";
f+="cancel_item=Cancel holding item\n";
f+="env_fight=Environment of fight\n";
f+="previous_button=<<\n";
f+="next_button=>>\n";
f+="empty_foe_team=No fighter in the foe team\n";
f+="not_selected_foe=No selected foe trainer\n";
f+="not_selected_player_pk=No fighter in the player team\n";
f+="bad_choice_front_fighter=Bad choice about the position of front fighters\n";
f+="bad_choice_front_fighter_moves=Bad choice about the moves to learn and the evolutions\n";
f+="bad_choice_front_fighter_moves_targets=Bad choice about the targets\n";
f+="add_pk_player=Add\n";
f+="search_pk_player=Search pokemon\n";
f+="index=Return to the index\n";
f+="unselected_pk=No selected pokemon\n";
f+="unselected_action=No selected action\n";
f+="unselected_move=No selected move\n";
f+="validate_moves=Validate learning moves\n";
f+="validate_move_target=Validate move choice and target choice\n";
return f;
}
static String fr(){
String f="title=Simulation de combats\n";
f+="title_param=Simulation de combats {0}/8\n";
f+="win_pts=Difficult&eacute; de gain des points\n";
f+="allow_catching_ko=Autoriser la capture de pokemon ko\n";
f+="allow_switch_places=Autoriser l''&eacute;change de places sur le terrain en fin de tour\n";
f+="win_trainer_exp=Coefficient de gain de points d''exp&eacute;rience lors d''un combat contre un dresseur\n";
f+="winning_exp_pts_fight=Coefficient de gain de points d''exp&eacute;rience\n";
f+="rate_issue={0} n''est pas un taux valide.\n";
f+="short_issue={0} n''est pas un entier valide.\n";
f+="end_fight=Fin de combat si une &eacute;quipe est ko.\n";
f+="iv_player=Iv de vos pokemon\n";
f+="iv_foe=Iv des pokemon de vos adversaires\n";
f+="flee=Fuite toujours possible\n";
f+="restored_moves=Attaques de vos pokemon restaur&eacute;es &agrave; la fin du combat\n";
f+="closing=Les attaques &agrave; cible unique peuvent toucher n''importe quel adversaire\n";
f+="random_wild=Apparition des pokemon al&eacute;atoire\n";
f+="skip_learn=Ne pas apprendre les attaques d&eacute;j&agrave; connues\n";
f+="rate_win_money_base=Rapport d''argent gagn&eacute; entre le gain lors d''une victoire et la base de gain\n";
f+="rate_win_money_loose=Rapport d''argent perdu entre la perte lords d''une d&eacute;faite et le gain lors d''une victoire\n";
f+="law_choice_player=Choix de la loi de probabilit&eacute; du coefficient de d&eacute;g&acirc;ts pour vos pokemon\n";
f+="law_choice_foe=Choix de la loi de probabilit&eacute; du coefficient de d&eacute;g&acirc;ts pour les pokemon de vos adversaires\n";
f+="rate_damage_ev=Coefficient\n";
f+="rate_damage=Probabilit&eacute;\n";
f+="no_fight=Num&eacute;ro de combat\n";
f+="cancel=Annuler\n";
f+="cancel_evo=Annuler la derni&egrave;re &eacute;volution\n";
f+="disable_evos=Conserver les attaques durant la simulation >>\n";
f+="select_foe_pk=Pokemon du dresseur ennemi\n";
f+="select_ally_pk=Pokemon du dresseur alli&eacute;\n";
f+="select_pk=S&eacute;lectionnez votre &eacute;quipe de pokemon\n";
f+="select_pk_evos=S&eacute;lectionnez les &eacute;volutions de vos pokemon\n";
f+="select_sent_pk=S&eacute;lectionnez vos pokemon envoy&eacute;s pour chaque tour\n";
f+="select_pk_moves=S&eacute;lectionnez les attaques de vos pokemon pour chaque tour\n";
f+="select_pk_move_target=S&eacute;lectionnez l''attaque et la cible de vos pokemon pour chaque tour\n";
f+="select_pk_evos_after_fight=S&eacute;lectionnez les &eacute;volutions de vos pokemon apr&egrave; le combat\n";
f+="add=Ajouter\n";
f+="remove=Supprimer\n";
f+="select=S&eacute;lectionner\n";
f+="edit=&Eacute;diter\n";
f+="selected=S&eacute;lectionn&eacute;\n";
f+="name_pk=Nom\n";
f+="ability_pk=Capacit&eacute;\n";
f+="item_pk=Objet\n";
f+="level_pk=Niveau\n";
f+="gender_pk=Genre\n";
f+="moves_pk=Attaques\n";
f+="exp_pk=&Eacute;xperience gagn&eacute;e\n";
f+="exp_pk_rem=&Eacute;xperience restante pour le niveau suivant\n";
f+="happiness_pk=Bonheur\n";
f+="ev=Ev en statististiques\n";
f+="heal_hp=Soigner les points de vie\n";
f+="remaining_hp=Points de vie restants\n";
f+="catching_ball=Balle de capture\n";
f+="multiplicity=Place sur le terrain\n";
f+="round=Num&eacute;ro de tour\n";
f+="cancel_moves=Annuler le choix d''ensemble d''attaques\n";
f+="evolution=&Eacute;volution\n";
f+="ally_choice=Pokemon alli&eacute; choisi\n";
f+="hp_rate=Taux de vie restant\n";
f+="ko_player_fighters=Pokemon ko du joueur\n";
f+="ko_foe_fighters=Pokemon ko du dresseur ennemi\n";
f+="not_ko_foe_fighters=Pokemon de front non ko du dresseur ennemi\n";
f+="issue_rules=Probl&egrave;me de r&egrave;gles\n";
f+="issue_rules_moves=Probl&egrave;me de choix d''attaques\n";
f+="issue_rules_learn=Probl&egrave;me de choix d''apprentissage d''attaques ou d''&eacute;volutions\n";
f+="issue_rules_switch=Probl&egrave;me de remplacement\n";
f+="issue_random=Probl&egrave;me de tirage al&eacute;atoire\n";
f+="issue_sending=Probl&egrave;me d''envoi\n";
f+="issue_using=Probl&egrave;me d''utilisation d''une attaque pour un pokemon de joueur\n";
f+="issue_too_hard=Probl&egrave;me de simulation compliqu&eacute;e\n";
f+="issue_after_fight=Mauvais choix d''&eacute;volutions apr&egrave;s le combat\n";
f+="display_comments=Afficher les commentaires\n";
f+="hide_comments=Cacher les commentaires\n";
f+="free_teams=&Eacute;quipes libres\n";
f+="multiplicity_fight=Multiplicit&eacute; du combat\n";
f+="ally_pk=Pokemon alli&eacute;\n";
f+="available_moves=Uniquement les attaques disponibles pour le pokemon du joueur\n";
f+="search=Chercher\n";
f+="cancel_item=Annuler le port d''objet\n";
f+="env_fight=Environnement de combat\n";
f+="previous_button=<<\n";
f+="next_button=>>\n";
f+="empty_foe_team=Pas de combattant dans l''&eacute;quipe adverse\n";
f+="not_selected_foe=Pas de dresseur ennemi s&eacute;lectionn&eacute;\n";
f+="not_selected_player_pk=Pas de combattant dans l''&eacute;quipe du joueur\n";
f+="bad_choice_front_fighter=Mauvais choix sur la position des combattants de front\n";
f+="bad_choice_front_fighter_moves=Mauvais choix sur les attaques &agrave; apprendre et les &eacute;volutions\n";
f+="bad_choice_front_fighter_moves_targets=Mauvais choix sur les cibles\n";
f+="add_pk_player=Ajouter\n";
f+="search_pk_player=Rerchercher un pokemon\n";
f+="index=Revenir &agrave; l''indexe\n";
f+="unselected_pk=Aucun pokemon s&eacute;lectionn&eacute;\n";
f+="unselected_action=Aucune action s&eacute;lectionn&eacute;e\n";
f+="unselected_move=Aucune attaque s&eacute;lectionn&eacute;e\n";
f+="validate_moves=Valider l''apprentissage des attaques\n";
f+="validate_move_target=Valider le choix de l''attaque et le choix de la cible\n";
return f;
}
}
