package code.scripts.pages.aiki;
final class MesDataIndex{
private static final String C_P_15_0="Data about the current loaded game\n";
private static final String C_P_15_10="Moves combos\n";
private static final String C_P_15_11="End of round\n";
private static final String C_P_15_12="Map\n";
private static final String C_P_15_13="Solution\n";
private static final String C_P_15_14="Simulation of fights\n";
private static final String C_P_15_15="Translations\n";
private static final String C_P_15_16="Donn&eacute;es sur le jeu venant d''&ecirc;tre charg&eacute;\n";
private static final String C_P_15_17="G&eacute;n&eacute;ralit&eacute;s\n";
private static final String C_P_15_18="D&eacute;roulement d''un tour\n";
private static final String C_P_15_19="Pokedex\n";
private static final String C_P_15_1="Generalities\n";
private static final String C_P_15_20="Objets\n";
private static final String C_P_15_21="Attaques\n";
private static final String C_P_15_22="Attaques apprises\n";
private static final String C_P_15_23="Attaques non apprises\n";
private static final String C_P_15_24="Capacit&eacute;s\n";
private static final String C_P_15_25="Statuts\n";
private static final String C_P_15_26="Combinaisons d''attaques\n";
private static final String C_P_15_27="Fin de tour\n";
private static final String C_P_15_28="Cartographie\n";
private static final String C_P_15_29="Solution\n";
private static final String C_P_15_2="Round happening\n";
private static final String C_P_15_30="Simulation de combats\n";
private static final String C_P_15_31="Traductions\n";
private static final String C_P_15_3="Pokedex\n";
private static final String C_P_15_4="Items\n";
private static final String C_P_15_5="Moves\n";
private static final String C_P_15_6="Learnt moves\n";
private static final String C_P_15_7="Not learnt moves\n";
private static final String C_P_15_8="Abilities\n";
private static final String C_P_15_9="Status\n";
private static final String M_P_ABILITIES="abilities";
private static final String M_P_COMBOS="combos";
private static final String M_P_ENDROUND="endRound";
private static final String M_P_GENERAL="general";
private static final String M_P_ITEMS="items";
private static final String M_P_LANGS="langs";
private static final String M_P_LEARNTMOVES="learntMoves";
private static final String M_P_MAP="map";
private static final String M_P_MOVES="moves";
private static final String M_P_NOTLEARNTMOVES="notLearntMoves";
private static final String M_P_POKEDEX="pokedex";
private static final String M_P_ROUND="round";
private static final String M_P_SIMULATION="simulation";
private static final String M_P_SOLUTION="solution";
private static final String M_P_STATUS="status";
private static final String M_P_TITLE="title";
private static final char SEP='=';
private MesDataIndex(){}
static String en(){
String f=M_P_TITLE+SEP+C_P_15_0;
f+=M_P_GENERAL+SEP+C_P_15_1;
f+=M_P_ROUND+SEP+C_P_15_2;
f+=M_P_POKEDEX+SEP+C_P_15_3;
f+=M_P_ITEMS+SEP+C_P_15_4;
f+=M_P_MOVES+SEP+C_P_15_5;
f+=M_P_LEARNTMOVES+SEP+C_P_15_6;
f+=M_P_NOTLEARNTMOVES+SEP+C_P_15_7;
f+=M_P_ABILITIES+SEP+C_P_15_8;
f+=M_P_STATUS+SEP+C_P_15_9;
f+=M_P_COMBOS+SEP+C_P_15_10;
f+=M_P_ENDROUND+SEP+C_P_15_11;
f+=M_P_MAP+SEP+C_P_15_12;
f+=M_P_SOLUTION+SEP+C_P_15_13;
f+=M_P_SIMULATION+SEP+C_P_15_14;
f+=M_P_LANGS+SEP+C_P_15_15;
return f;
}
static String fr(){
String f=M_P_TITLE+SEP+C_P_15_16;
f+=M_P_GENERAL+SEP+C_P_15_17;
f+=M_P_ROUND+SEP+C_P_15_18;
f+=M_P_POKEDEX+SEP+C_P_15_19;
f+=M_P_ITEMS+SEP+C_P_15_20;
f+=M_P_MOVES+SEP+C_P_15_21;
f+=M_P_LEARNTMOVES+SEP+C_P_15_22;
f+=M_P_NOTLEARNTMOVES+SEP+C_P_15_23;
f+=M_P_ABILITIES+SEP+C_P_15_24;
f+=M_P_STATUS+SEP+C_P_15_25;
f+=M_P_COMBOS+SEP+C_P_15_26;
f+=M_P_ENDROUND+SEP+C_P_15_27;
f+=M_P_MAP+SEP+C_P_15_28;
f+=M_P_SOLUTION+SEP+C_P_15_29;
f+=M_P_SIMULATION+SEP+C_P_15_30;
f+=M_P_LANGS+SEP+C_P_15_31;
return f;
}
}
