package code.scripts.pages.aiki;
final class MesFightFight{
private MesFightFight(){}
static String en(){
String f="title_fight=Data about the current fight\n";
f+="title_detail_fight=Details about the current fight\n";
f+="enbaled_moves=Here is the activity of the effects of the following moves at the global fight:<br/>\n";
f+="enbaled_moves_key=Move\n";
f+="enbaled_moves_enabled=Enabled\n";
f+="enbaled_moves_nb_round=Number of rounds\n";
f+="enbaled_moves_still=Enabled while sending a fighter\n";
f+="enbaled_moves_no=-\n";
f+="enbaled_moves_enabled_y=Yes\n";
f+="enbaled_moves_enabled_n=No\n";
f+="damage_fct_choices=Here is the table of remaining health points at the minimum of the foe team et at the maximum of one of your pokemon in fonction by the moves that you have chosen.<br/>\n";
f+="damage_fct_choices_key_one=Your pokemon\n";
f+="damage_fct_choices_key_two=The chosen move\n";
f+="damage_fct_choices_key_three=A target pokemon\n";
f+="damage_fct_choices_damage=Remaining health points\n";
f+="damage_fct_choices_player=Player\n";
f+="damage_fct_choices_foe=Foe\n";
f+="sorted_fighters_fct_choices=Here is the sorted list of pokemon of front by order of using a move in function by the moves that you have chosen.<br/>\n";
f+="sorted_fighters_fct_choices_wild=Here is the sorted list of pokemon of front by order of using a move in function by the moves that you have chosen and the moves of the wild pokemon.<br/>\n";
f+="ally_choices=The choice of the moves by the ally trainer is the following one (it depends on your choice):<br/>\n";
f+="ally_choices_key=Your choice of move\n";
f+="ally_choices_key_team=Team of the target of your choice\n";
f+="ally_choices_key_place=Place of the target of your choice\n";
f+="ally_choices_key_name=Name of the target of your choice\n";
f+="ally_choices_no=No chosen target\n";
f+="ally_choices_value=Choice of move of the ally trainer\n";
f+="ally_choices_value_team=Team of the target of the choice of the ally trainer\n";
f+="ally_choices_value_place=Place of the target of the choice of the ally trainer\n";
f+="ally_choices_value_name=Name of the target of the choice of the ally trainer\n";
f+="ally_choices_foe=Foe\n";
f+="ally_choices_player=Player\n";
f+="foe_choices=The choice of the moves of the foee trainer is the following one:<br/>\n";
f+="foe_choices_key=First place of the fighter of the foe trainer\n";
f+="foe_choices_key_name=Name of the fighter of the foe trainer\n";
f+="foe_choices_value=Choice of move of the foe trainer\n";
f+="foe_choices_value_team=Team of the target of the choice of the foe trainer\n";
f+="foe_choices_value_place=Place of the target of the choice of the foe trainer\n";
f+="foe_choices_value_name=Name of the target of the choice of the foe trainer\n";
f+="foe_choices_foe=Foe\n";
f+="foe_choices_player=Player\n";
f+="foe_choices_no=-\n";
f+="mult=The multiplicity of the fight is {0}.<br/>\n";
f+="nb_rounds=The number of elapsed rounds is {0}.<br/>\n";
f+="nb_flee_attempts=The number of attempts of flee is {0}.<br/>\n";
f+="win_money=The won money is {0}.<br/>\n";
f+="yours=Your team\n";
f+="foes=Foe team\n";
f+="refresh=Refresh\n";
f+="go_detail=See details of calculation of damage and speed\n";
return f;
}
static String fr(){
String f="title_fight=Donn&eacute;es sur le combat courant\n";
f+="title_detail_fight=D&eacute;tails sur le combat courant\n";
f+="enbaled_moves=Voici l''activit&eacute; des effets des attaques suivantes &agrave; l''&eacute;chelle globale:<br/>\n";
f+="enbaled_moves_key=Attaque\n";
f+="enbaled_moves_enabled=Actif\n";
f+="enbaled_moves_nb_round=Nombre de tours\n";
f+="enbaled_moves_still=Activ&eacute; lors de l''entr&eacute;e d''un combattant\n";
f+="enbaled_moves_no=-\n";
f+="enbaled_moves_enabled_y=Oui\n";
f+="enbaled_moves_enabled_n=Non\n";
f+="damage_fct_choices=Voici le tableau des points de vie restants au minimum de l''&eacute;quipe ennemie et au maximum de un de vos pokemon en fonction des attaques que vous avez choisies.<br/>\n";
f+="damage_fct_choices_key_one=Votre pokemon\n";
f+="damage_fct_choices_key_two=L''attaque choisie\n";
f+="damage_fct_choices_key_three=Un pokemon cible\n";
f+="damage_fct_choices_damage=Points de vie restants\n";
f+="damage_fct_choices_player=Joueur\n";
f+="damage_fct_choices_foe=Ennemi\n";
f+="sorted_fighters_fct_choices=Voici la liste des pokemon de front ordonn&eacute;e au niveau de l''ordre d''attaque en fonction des attaques que vous avez choisies.<br/>\n";
f+="sorted_fighters_fct_choices_wild=Voici la liste des pokemon de front ordonn&eacute;e au niveau de l''ordre d''attaque en fonction des attaques que vous avez choisies et de celles du pokemon sauvage.<br/>\n";
f+="ally_choices=Le choix des attaques par le dresseur alli&eacute; est le suivant (il d&eacute;pend de votre choix):<br/>\n";
f+="ally_choices_key=Votre choix d''attaque\n";
f+="ally_choices_key_team=Equipe de la cible de votre choix\n";
f+="ally_choices_key_place=Place de la cible de votre choix\n";
f+="ally_choices_key_name=Nom de la cible de votre choix\n";
f+="ally_choices_no=Pas de cible choisie\n";
f+="ally_choices_value=Choix d''attaque du dresseur alli&eacute;\n";
f+="ally_choices_value_team=Equipe de la cible du choix du dresseur alli&eacute;\n";
f+="ally_choices_value_place=Place de la cible du choix du dresseur alli&eacute;\n";
f+="ally_choices_value_name=Nom de la cible du choix du dresseur alli&eacute;\n";
f+="ally_choices_foe=Ennemi\n";
f+="ally_choices_player=Joueur\n";
f+="foe_choices=Le choix des attaques par le dresseur ennemi est le suivant:<br/>\n";
f+="foe_choices_key=Place initiale du combattant du dresseur ennemi\n";
f+="foe_choices_key_name=Nom du combattant du dresseur ennemi\n";
f+="foe_choices_value=Choix d''attaque du dresseur ennemi\n";
f+="foe_choices_value_team=Equipe de la cible du choix du dresseur ennemi\n";
f+="foe_choices_value_place=Place de la cible du choix du dresseur ennemi\n";
f+="foe_choices_value_name=Nom de la cible du choix du dresseur ennemi\n";
f+="foe_choices_foe=Ennemi\n";
f+="foe_choices_player=Joueur\n";
f+="foe_choices_no=-\n";
f+="mult=La mulitiplicit&eacute; du combat est {0}.<br/>\n";
f+="nb_rounds=Le nombre de tours &eacute;coul&eacute;s est de {0}.<br/>\n";
f+="nb_flee_attempts=Le nombre de tentatives de fuites est de {0}.<br/>\n";
f+="win_money=L''argent gagn&eacute; vaut {0}.<br/>\n";
f+="yours=Votre &eacute;quipe\n";
f+="foes=Equipe ennemi\n";
f+="refresh=Rafra&icirc;chir\n";
f+="go_detail=Voir les d&eacute;tails des calculs de d&eacute;g&acirc;ts et de vitesses\n";
return f;
}
}
