package code.scripts.pages.aiki;
import code.sml.*;
import code.util.*;
import code.util.ints.*;
final class PageDataMovesEffectsEffcounterattack{
private PageDataMovesEffectsEffcounterattack(){}
static Document build(){
FullDocument doc_ = DocumentBuilder.newXmlDocument(4);
build(doc_);
return doc_;
}
static void build(Document _doc){
Element elt0_=el(_doc,"html");
CustList<Attr> attrs0_=al(2);
attrs0_.add(at("xmlns:c","javahtml"));
attrs0_.add(at("c:bean","eff_counterattack"));
at(elt0_,attrs0_);
Element elt1_=el(_doc,"head");
Element elt2_=el(_doc,"link");
CustList<Attr> attrs1_=al(3);
attrs1_.add(at("href","web/css/moves.css"));
attrs1_.add(at("rel","stylesheet"));
attrs1_.add(at("type","text/css"));
at(elt2_,attrs1_);
ad(elt1_,elt2_);
ad(elt0_,elt1_);
Element elt3_=el(_doc,"body");
build0(elt3_,_doc);
ad(elt0_,elt3_);
_doc.appendChild(elt0_);
}
static void build0(Element _body,Document _doc){
Element elt0_=el(_doc,"p");
Element elt1_=el(_doc,"c:message");
CustList<Attr> attrs0_=al(1);
attrs0_.add(at("value","msg_effcounterattack,effect"));
at(elt1_,attrs0_);
ad(elt0_,elt1_);
Element elt2_=el(_doc,"c:import");
CustList<Attr> attrs1_=al(1);
attrs1_.add(at("page","{effectBean}"));
at(elt2_,attrs1_);
Element elt3_=el(_doc,"c:package");
CustList<Attr> attrs2_=al(1);
attrs2_.add(at("name","aiki.beans.moves.effects"));
at(elt3_,attrs2_);
Element elt4_=el(_doc,"c:class");
CustList<Attr> attrs3_=al(1);
attrs3_.add(at("name","EffectBean"));
at(elt4_,attrs3_);
Element elt5_=el(_doc,"c:field");
CustList<Attr> attrs4_=al(1);
attrs4_.add(at("prepare","$intern.index=index"));
at(elt5_,attrs4_);
ad(elt4_,elt5_);
Element elt6_=el(_doc,"c:field");
CustList<Attr> attrs5_=al(1);
attrs5_.add(at("prepare","$intern.move=move"));
at(elt6_,attrs5_);
ad(elt4_,elt6_);
ad(elt3_,elt4_);
ad(elt2_,elt3_);
ad(elt0_,elt2_);
Element elt7_=el(_doc,"c:if");
CustList<Attr> attrs6_=al(1);
attrs6_.add(at("condition","!sufferingDamageTypes.isEmpty()"));
at(elt7_,attrs6_);
Element elt8_=el(_doc,"c:message");
CustList<Attr> attrs7_=al(1);
attrs7_.add(at("value","msg_effcounterattack,suffering_types"));
at(elt8_,attrs7_);
Element elt9_=el(_doc,"param");
CustList<Attr> attrs8_=al(1);
attrs8_.add(at("value","move"));
at(elt9_,attrs8_);
ad(elt8_,elt9_);
ad(elt7_,elt8_);
Element elt10_=el(_doc,"table");
Element elt11_=el(_doc,"thead");
Element elt12_=el(_doc,"tr");
Element elt13_=el(_doc,"th");
Element elt14_=el(_doc,"c:message");
CustList<Attr> attrs9_=al(1);
attrs9_.add(at("value","msg_effcounterattack,suffering_types_t"));
at(elt14_,attrs9_);
ad(elt13_,elt14_);
ad(elt12_,elt13_);
Element elt15_=el(_doc,"th");
Element elt16_=el(_doc,"c:message");
CustList<Attr> attrs10_=al(1);
attrs10_.add(at("value","msg_effcounterattack,suffering_types_hp"));
at(elt16_,attrs10_);
ad(elt15_,elt16_);
ad(elt12_,elt15_);
ad(elt11_,elt12_);
ad(elt10_,elt11_);
Element elt17_=el(_doc,"tbody");
Element elt18_=el(_doc,"c:for");
CustList<Attr> attrs11_=al(5);
attrs11_.add(at("key","c"));
attrs11_.add(at("map","sufferingDamageTypes"));
attrs11_.add(at("value","r"));
attrs11_.add(at("keyClassName","java.lang.Object"));
attrs11_.add(at("varClassName","r"));
at(elt18_,attrs11_);
Element elt19_=el(_doc,"tr");
Element elt20_=el(_doc,"td");
Text txt0_=tx(_doc,"{getTrSufferingDamageTypes(([c]))}");
ad(elt20_,txt0_);
ad(elt19_,elt20_);
Element elt21_=el(_doc,"td");
Text txt1_=tx(_doc,"{r}");
ad(elt21_,txt1_);
ad(elt19_,elt21_);
ad(elt18_,elt19_);
ad(elt17_,elt18_);
ad(elt10_,elt17_);
ad(elt7_,elt10_);
Element elt22_=el(_doc,"br");
ad(elt7_,elt22_);
ad(elt0_,elt7_);
Element elt23_=el(_doc,"c:if");
CustList<Attr> attrs12_=al(1);
attrs12_.add(at("condition","!droppedStatDirectMove.isEmpty()"));
at(elt23_,attrs12_);
Element elt24_=el(_doc,"c:message");
CustList<Attr> attrs13_=al(1);
attrs13_.add(at("value","msg_effcounterattack,dropped_stat"));
at(elt24_,attrs13_);
Element elt25_=el(_doc,"param");
CustList<Attr> attrs14_=al(1);
attrs14_.add(at("value","move"));
at(elt25_,attrs14_);
ad(elt24_,elt25_);
ad(elt23_,elt24_);
Element elt26_=el(_doc,"table");
Element elt27_=el(_doc,"thead");
Element elt28_=el(_doc,"tr");
Element elt29_=el(_doc,"th");
Element elt30_=el(_doc,"c:message");
CustList<Attr> attrs15_=al(1);
attrs15_.add(at("value","msg_effcounterattack,dropped_stat_s"));
at(elt30_,attrs15_);
ad(elt29_,elt30_);
ad(elt28_,elt29_);
Element elt31_=el(_doc,"th");
Element elt32_=el(_doc,"c:message");
CustList<Attr> attrs16_=al(1);
attrs16_.add(at("value","msg_effcounterattack,dropped_stat_v"));
at(elt32_,attrs16_);
ad(elt31_,elt32_);
ad(elt28_,elt31_);
ad(elt27_,elt28_);
ad(elt26_,elt27_);
Element elt33_=el(_doc,"tbody");
Element elt34_=el(_doc,"c:for");
CustList<Attr> attrs17_=al(5);
attrs17_.add(at("key","c"));
attrs17_.add(at("map","droppedStatDirectMove"));
attrs17_.add(at("value","r"));
attrs17_.add(at("keyClassName","java.lang.Object"));
attrs17_.add(at("varClassName","java.lang.Byte"));
at(elt34_,attrs17_);
Element elt35_=el(_doc,"tr");
Element elt36_=el(_doc,"td");
Text txt2_=tx(_doc,"{getTrDroppedStatDirectMove(([c]))}");
ad(elt36_,txt2_);
ad(elt35_,elt36_);
Element elt37_=el(_doc,"td");
Text txt3_=tx(_doc,"{r}");
ad(elt37_,txt3_);
ad(elt35_,elt37_);
ad(elt34_,elt35_);
ad(elt33_,elt34_);
ad(elt26_,elt33_);
ad(elt23_,elt26_);
Element elt38_=el(_doc,"br");
ad(elt23_,elt38_);
ad(elt0_,elt23_);
Element elt39_=el(_doc,"c:if");
CustList<Attr> attrs18_=al(1);
attrs18_.add(at("condition","!sufferingDamageDirectMove.isZero()"));
at(elt39_,attrs18_);
Element elt40_=el(_doc,"c:message");
CustList<Attr> attrs19_=al(1);
attrs19_.add(at("value","msg_effcounterattack,suffering_direct"));
at(elt40_,attrs19_);
Element elt41_=el(_doc,"param");
CustList<Attr> attrs20_=al(1);
attrs20_.add(at("value","move"));
at(elt41_,attrs20_);
ad(elt40_,elt41_);
Element elt42_=el(_doc,"param");
CustList<Attr> attrs21_=al(1);
attrs21_.add(at("value","sufferingDamageDirectMove"));
at(elt42_,attrs21_);
ad(elt40_,elt42_);
ad(elt39_,elt40_);
ad(elt0_,elt39_);
Element elt43_=el(_doc,"c:if");
CustList<Attr> attrs22_=al(1);
attrs22_.add(at("condition","!reasonsProtect.isEmpty()"));
at(elt43_,attrs22_);
Element elt44_=el(_doc,"p");
Element elt45_=el(_doc,"c:message");
CustList<Attr> attrs23_=al(1);
attrs23_.add(at("value","msg_effcounterattack,fail_protect"));
at(elt45_,attrs23_);
Element elt46_=el(_doc,"param");
CustList<Attr> attrs24_=al(1);
attrs24_.add(at("value","move"));
at(elt46_,attrs24_);
ad(elt45_,elt46_);
ad(elt44_,elt45_);
Element elt47_=el(_doc,"ul");
Element elt48_=el(_doc,"c:for");
CustList<Attr> attrs25_=al(3);
attrs25_.add(at("list","reasonsProtect"));
attrs25_.add(at("var","r"));
attrs25_.add(at("className","java.lang.String"));
at(elt48_,attrs25_);
Element elt49_=el(_doc,"li");
Text txt4_=tx(_doc,"{r}");
ad(elt49_,txt4_);
ad(elt48_,elt49_);
ad(elt47_,elt48_);
ad(elt44_,elt47_);
Element elt50_=el(_doc,"br");
ad(elt44_,elt50_);
ad(elt43_,elt44_);
ad(elt0_,elt43_);
Element elt51_=el(_doc,"c:if");
CustList<Attr> attrs26_=al(1);
attrs26_.add(at("condition","!reasonsCounter.isEmpty()"));
at(elt51_,attrs26_);
Element elt52_=el(_doc,"p");
Element elt53_=el(_doc,"c:message");
CustList<Attr> attrs27_=al(1);
attrs27_.add(at("value","msg_effcounterattack,counter_protect"));
at(elt53_,attrs27_);
Element elt54_=el(_doc,"param");
CustList<Attr> attrs28_=al(1);
attrs28_.add(at("value","move"));
at(elt54_,attrs28_);
ad(elt53_,elt54_);
ad(elt52_,elt53_);
Element elt55_=el(_doc,"ul");
Element elt56_=el(_doc,"c:for");
CustList<Attr> attrs29_=al(3);
attrs29_.add(at("list","reasonsCounter"));
attrs29_.add(at("var","r"));
attrs29_.add(at("className","java.lang.String"));
at(elt56_,attrs29_);
Element elt57_=el(_doc,"li");
Text txt5_=tx(_doc,"{r}");
ad(elt57_,txt5_);
ad(elt56_,elt57_);
ad(elt55_,elt56_);
ad(elt52_,elt55_);
Element elt58_=el(_doc,"br");
ad(elt52_,elt58_);
ad(elt51_,elt52_);
ad(elt0_,elt51_);
Element elt59_=el(_doc,"c:if");
CustList<Attr> attrs30_=al(1);
attrs30_.add(at("condition","!getMapVarsFailCounter().isEmpty()"));
at(elt59_,attrs30_);
Element elt60_=el(_doc,"ul");
Element elt61_=el(_doc,"c:for");
CustList<Attr> attrs31_=al(5);
attrs31_.add(at("key","c"));
attrs31_.add(at("map","getMapVarsFailCounter()"));
attrs31_.add(at("value","r"));
attrs31_.add(at("keyClassName","java.lang.String"));
attrs31_.add(at("varClassName","java.lang.String"));
at(elt61_,attrs31_);
Element elt62_=el(_doc,"li");
Text txt6_=tx(_doc,"{c} :");
ad(elt62_,txt6_);
Element elt63_=el(_doc,"c:message");
CustList<Attr> attrs32_=al(2);
attrs32_.add(at("quoted",""));
attrs32_.add(at("value","msg_effcounterattack,formula"));
at(elt63_,attrs32_);
Element elt64_=el(_doc,"param");
CustList<Attr> attrs33_=al(1);
attrs33_.add(at("value","r"));
at(elt64_,attrs33_);
ad(elt63_,elt64_);
ad(elt62_,elt63_);
ad(elt61_,elt62_);
ad(elt60_,elt61_);
ad(elt59_,elt60_);
ad(elt0_,elt59_);
ad(_body,elt0_);
}
static Attr at(String _name,String _value){
return CoreDocument.createAttribute(_name,_value);
}
static void at(Element _elt,CustList<Attr> _ls){
_elt.setAttributes(new NamedNodeMap(_ls));
}
static CustList<Attr> al(int _len){
return new CustList<Attr>(new CollCapacity(_len));
}
static Text tx(Document _doc,String _value){
return _doc.createEscapedTextNode(_value);
}
static Element el(Document _doc,String _value){
return _doc.createElement(_value);
}
static void ad(Element _elt,Node _value){
_elt.appendChild(_value);
}
}
