package aiki.sml.imgs;
import code.util.*;
import aiki.db.*;
import aiki.sml.init.*;
public final class ImgMap extends CstIgame{
private ImgMap(){}
public static StringMap<ImageArrayBaseSixtyFour> im(String _base){
StringMap<ImageArrayBaseSixtyFour> i = new StringMap<ImageArrayBaseSixtyFour>(53);
i.addEntry(F_BOTTOM_BOUND_14_3_TXT,ImageArrayBaseSixtyFour.instance(ImgMap2.i2(),_base));
i.addEntry(F_BOTTOM_BOUND_6_1_TXT,ImageArrayBaseSixtyFour.instance(ImgMap3.i3(),_base));
i.addEntry(F_BOTTOM_BOUND_7_1_TXT,ImageArrayBaseSixtyFour.instance(ImgMap4.i4(),_base));
i.addEntry(F_BUILDING_10_10_TXT,ImageArrayBaseSixtyFour.instance(ImgMap5.i5(),_base));
i.addEntry(F_BUILDING_INSIDE_TXT,ImageArrayBaseSixtyFour.instance(ImgMap6.i6(),_base));
i.addEntry(F_CITY_NOTHING_PT_0_0_TXT,ImageArrayBaseSixtyFour.instance(ImgMap7.i7(),_base));
i.addEntry(F_CITY_NOTHING_PT_0_15_TXT,ImageArrayBaseSixtyFour.instance(ImgMap8.i8(),_base));
i.addEntry(F_CITY_NOTHING_PT_0_4_TXT,ImageArrayBaseSixtyFour.instance(ImgMap9.i9(),_base));
i.addEntry(F_CITY_NOTHING_PT_15_0_TXT,ImageArrayBaseSixtyFour.instance(ImgMap11.i11(),_base));
i.addEntry(F_CITY_NOTHING_PT_15_15_TXT,ImageArrayBaseSixtyFour.instance(ImgMap12.i12(),_base));
i.addEntry(F_CITY_NOTHING_PT_22_0_TXT,ImageArrayBaseSixtyFour.instance(ImgMap13.i13(),_base));
i.addEntry(F_CITY_NOTHING_PT_22_15_TXT,ImageArrayBaseSixtyFour.instance(ImgMap14.i14(),_base));
i.addEntry(F_CITY_NOTHING_PT_22_4_TXT,ImageArrayBaseSixtyFour.instance(ImgMap15.i15(),_base));
i.addEntry(F_CITY_NOTHING_PT_4_0_TXT,ImageArrayBaseSixtyFour.instance(ImgMap17.i17(),_base));
i.addEntry(F_CITY_NOTHING_PT_4_15_TXT,ImageArrayBaseSixtyFour.instance(ImgMap18.i18(),_base));
i.addEntry(F_CITY_ROAD_GRASS_PT_0_9_TXT,ImageArrayBaseSixtyFour.instance(ImgMap21.i21(),_base));
i.addEntry(F_CITY_ROAD_GRASS_PT_22_9_TXT,ImageArrayBaseSixtyFour.instance(ImgMap22.i22(),_base));
i.addEntry(F_CITY_ROAD_GRASS_PT_9_0_TXT,ImageArrayBaseSixtyFour.instance(ImgMap23.i23(),_base));
i.addEntry(F_CITY_ROAD_GRASS_PT_9_15_TXT,ImageArrayBaseSixtyFour.instance(ImgMap24.i24(),_base));
i.addEntry(F_CITY_ROAD_PT_15_9_TXT,ImageArrayBaseSixtyFour.instance(ImgMap25.i25(),_base));
i.addEntry(F_CITY_ROAD_PT_4_8_TXT,ImageArrayBaseSixtyFour.instance(ImgMap26.i26(),_base));
i.addEntry(F_CITY_ROAD_PT_9_4_TXT,ImageArrayBaseSixtyFour.instance(ImgMap27.i27(),_base));
i.addEntry(F_EMPTY_TXT,ImageArrayBaseSixtyFour.instance(ImgMap28.i28(),_base));
i.addEntry(F_GRASS_2_2_TXT,ImageArrayBaseSixtyFour.instance(ImgMap29.i29(),_base));
i.addEntry(F_GRASS_3_6_TXT,ImageArrayBaseSixtyFour.instance(ImgMap30.i30(),_base));
i.addEntry(F_GRASS_6_3_TXT,ImageArrayBaseSixtyFour.instance(ImgMap31.i31(),_base));
i.addEntry(F_NOTHING_BOTTOM_CAVE_10_4_TXT,ImageArrayBaseSixtyFour.instance(ImgMap32.i32(),_base));
i.addEntry(F_NOTHING_CAVE_10_2_TXT,ImageArrayBaseSixtyFour.instance(ImgMap33.i33(),_base));
i.addEntry(F_NOTHING_GYM_TXT,ImageArrayBaseSixtyFour.instance(ImgMap34.i34(),_base));
i.addEntry(F_NOTHING_LEFT_CAVE_4_30_TXT,ImageArrayBaseSixtyFour.instance(ImgMap35.i35(),_base));
i.addEntry(F_NOTHING_PK_CENTER_TXT,ImageArrayBaseSixtyFour.instance(ImgMap36.i36(),_base));
i.addEntry(F_NOTHING_RIGHT_CAVE_4_30_TXT,ImageArrayBaseSixtyFour.instance(ImgMap37.i37(),_base));
i.addEntry(F_NOTHING_TOP_CAVE_10_4_TXT,ImageArrayBaseSixtyFour.instance(ImgMap38.i38(),_base));
i.addEntry(F_ROAD_6_2_TXT,ImageArrayBaseSixtyFour.instance(ImgMap39.i39(),_base));
i.addEntry(F_ROAD_BOTTOM_BORDER_TXT,ImageArrayBaseSixtyFour.instance(ImgMap40.i40(),_base));
i.addEntry(F_ROAD_GRASS_1_2_TXT,ImageArrayBaseSixtyFour.instance(ImgMap41.i41(),_base));
i.addEntry(F_ROAD_GRASS_2_1_TXT,ImageArrayBaseSixtyFour.instance(ImgMap42.i42(),_base));
i.addEntry(F_ROAD_GRASS_2_2_TXT,ImageArrayBaseSixtyFour.instance(ImgMap43.i43(),_base));
i.addEntry(F_ROAD_GRASS_6_2_TXT,ImageArrayBaseSixtyFour.instance(ImgMap44.i44(),_base));
i.addEntry(F_ROAD_GRASS_6_3_TXT,ImageArrayBaseSixtyFour.instance(ImgMap45.i45(),_base));
i.addEntry(F_ROAD_GRASS_9_6_TXT,ImageArrayBaseSixtyFour.instance(ImgMap46.i46(),_base));
i.addEntry(F_ROAD_HORIZ_TXT,ImageArrayBaseSixtyFour.instance(ImgMap47.i47(),_base));
i.addEntry(F_ROAD_LEFT_BORDER_TXT,ImageArrayBaseSixtyFour.instance(ImgMap48.i48(),_base));
i.addEntry(F_ROAD_LEFT_BORDER_HALF_TXT,ImageArrayBaseSixtyFour.instance(ImgMap49.i49(),_base));
i.addEntry(F_ROAD_RIGHT_BORDER_TXT,ImageArrayBaseSixtyFour.instance(ImgMap50.i50(),_base));
i.addEntry(F_ROAD_RIGHT_BORDER_HALF_TXT,ImageArrayBaseSixtyFour.instance(ImgMap51.i51(),_base));
i.addEntry(F_ROAD_TOP_BORDER_TXT,ImageArrayBaseSixtyFour.instance(ImgMap53.i53(),_base));
i.addEntry(F_ROAD_VERT_TXT,ImageArrayBaseSixtyFour.instance(ImgMap54.i54(),_base));
i.addEntry(F_ROCK_10_10_TXT,ImageArrayBaseSixtyFour.instance(ImgMap55.i55(),_base));
i.addEntry(F_TOP_BOUND_14_3_TXT,ImageArrayBaseSixtyFour.instance(ImgMap57.i57(),_base));
i.addEntry(F_TOP_BOUND_6_1_TXT,ImageArrayBaseSixtyFour.instance(ImgMap58.i58(),_base));
i.addEntry(F_TOP_BOUND_7_1_TXT,ImageArrayBaseSixtyFour.instance(ImgMap59.i59(),_base));
i.addEntry(F_WATER_10_2_TXT,ImageArrayBaseSixtyFour.instance(ImgMap60.i60(),_base));
return i;
}
}
