package code.network;

import cards.gui.containers.*;
import cards.tarot.*;
import cards.tarot.enumerations.CardTarot;
import code.util.*;

public abstract class TarotSampleFirstDealNetAbs implements IntFirstDealTarot {
    @Override
    public GameTarot deal(ContainerTarot _container) {
        return null;
    }
    public static CustList<HandTarot> dealFourPlayers() {
        CustList<HandTarot> ls_ = new CustList<HandTarot>();
        HandTarot h_ = new HandTarot();
        h_.ajouter(CardTarot.HEART_1);
        h_.ajouter(CardTarot.HEART_KING);
        h_.ajouter(CardTarot.TRUMP_19);
        h_.ajouter(CardTarot.TRUMP_13);
        h_.ajouter(CardTarot.TRUMP_8);
        h_.ajouter(CardTarot.TRUMP_3);
        h_.ajouter(CardTarot.SPADE_JACK);
        h_.ajouter(CardTarot.SPADE_8);
        h_.ajouter(CardTarot.SPADE_5);
        h_.ajouter(CardTarot.SPADE_3);
        h_.ajouter(CardTarot.DIAMOND_QUEEN);
        h_.ajouter(CardTarot.DIAMOND_6);
        h_.ajouter(CardTarot.DIAMOND_4);
        h_.ajouter(CardTarot.DIAMOND_1);
        h_.ajouter(CardTarot.CLUB_KNIGHT);
        h_.ajouter(CardTarot.CLUB_5);
        h_.ajouter(CardTarot.CLUB_4);
        h_.ajouter(CardTarot.CLUB_1);
        ls_.add(h_);
        h_ = new HandTarot();
        h_.ajouter(CardTarot.HEART_2);
        h_.ajouter(CardTarot.HEART_QUEEN);
        h_.ajouter(CardTarot.TRUMP_18);
        h_.ajouter(CardTarot.TRUMP_12);
        h_.ajouter(CardTarot.TRUMP_7);
        h_.ajouter(CardTarot.TRUMP_2);
        h_.ajouter(CardTarot.SPADE_KNIGHT);
        h_.ajouter(CardTarot.SPADE_7);
        h_.ajouter(CardTarot.SPADE_4);
        h_.ajouter(CardTarot.SPADE_2);
        h_.ajouter(CardTarot.DIAMOND_KING);
        h_.ajouter(CardTarot.DIAMOND_5);
        h_.ajouter(CardTarot.DIAMOND_3);
        h_.ajouter(CardTarot.DIAMOND_2);
        h_.ajouter(CardTarot.CLUB_JACK);
        h_.ajouter(CardTarot.CLUB_6);
        h_.ajouter(CardTarot.CLUB_3);
        h_.ajouter(CardTarot.CLUB_2);
        ls_.add(h_);
        h_ = new HandTarot();
        h_.ajouter(CardTarot.HEART_KNIGHT);
        h_.ajouter(CardTarot.HEART_5);
        h_.ajouter(CardTarot.HEART_4);
        h_.ajouter(CardTarot.HEART_3);
        h_.ajouter(CardTarot.TRUMP_17);
        h_.ajouter(CardTarot.TRUMP_11);
        h_.ajouter(CardTarot.TRUMP_6);
        h_.ajouter(CardTarot.TRUMP_1);
        h_.ajouter(CardTarot.SPADE_QUEEN);
        h_.ajouter(CardTarot.SPADE_1);
        h_.ajouter(CardTarot.DIAMOND_KNIGHT);
        h_.ajouter(CardTarot.DIAMOND_9);
        h_.ajouter(CardTarot.DIAMOND_8);
        h_.ajouter(CardTarot.DIAMOND_7);
        h_.ajouter(CardTarot.CLUB_KING);
        h_.ajouter(CardTarot.CLUB_9);
        h_.ajouter(CardTarot.CLUB_8);
        h_.ajouter(CardTarot.CLUB_7);
        ls_.add(h_);
        h_ = new HandTarot();
        h_.ajouter(CardTarot.HEART_JACK);
        h_.ajouter(CardTarot.HEART_10);
        h_.ajouter(CardTarot.HEART_9);
        h_.ajouter(CardTarot.HEART_8);
        h_.ajouter(CardTarot.HEART_7);
        h_.ajouter(CardTarot.HEART_6);
        h_.ajouter(CardTarot.TRUMP_21);
        h_.ajouter(CardTarot.TRUMP_20);
        h_.ajouter(CardTarot.TRUMP_16);
        h_.ajouter(CardTarot.TRUMP_10);
        h_.ajouter(CardTarot.TRUMP_5);
        h_.ajouter(CardTarot.EXCUSE);
        h_.ajouter(CardTarot.SPADE_KING);
        h_.ajouter(CardTarot.SPADE_6);
        h_.ajouter(CardTarot.DIAMOND_JACK);
        h_.ajouter(CardTarot.DIAMOND_10);
        h_.ajouter(CardTarot.CLUB_QUEEN);
        h_.ajouter(CardTarot.CLUB_10);
        ls_.add(h_);
        h_ = new HandTarot();
        h_.ajouter(CardTarot.TRUMP_15);
        h_.ajouter(CardTarot.TRUMP_14);
        h_.ajouter(CardTarot.TRUMP_9);
        h_.ajouter(CardTarot.TRUMP_4);
        h_.ajouter(CardTarot.SPADE_10);
        h_.ajouter(CardTarot.SPADE_9);
        ls_.add(h_);
        return ls_;
    }
    public static CustList<HandTarot> dealThreePlayers() {
        CustList<HandTarot> ls_ = new CustList<HandTarot>();
        HandTarot h_ = new HandTarot();
        h_.ajouter(CardTarot.EXCUSE);
        h_.ajouter(CardTarot.TRUMP_19);
        h_.ajouter(CardTarot.TRUMP_18);
        h_.ajouter(CardTarot.TRUMP_17);
        h_.ajouter(CardTarot.TRUMP_16);
        h_.ajouter(CardTarot.TRUMP_15);
        h_.ajouter(CardTarot.TRUMP_14);
        h_.ajouter(CardTarot.TRUMP_13);
        h_.ajouter(CardTarot.TRUMP_12);
        h_.ajouter(CardTarot.TRUMP_11);
        h_.ajouter(CardTarot.TRUMP_10);
        h_.ajouter(CardTarot.TRUMP_9);
        h_.ajouter(CardTarot.TRUMP_8);
        h_.ajouter(CardTarot.TRUMP_7);
        h_.ajouter(CardTarot.TRUMP_6);
        h_.ajouter(CardTarot.TRUMP_5);
        h_.ajouter(CardTarot.TRUMP_4);
        h_.ajouter(CardTarot.TRUMP_3);
        h_.ajouter(CardTarot.TRUMP_2);
        h_.ajouter(CardTarot.TRUMP_1);
        h_.ajouter(CardTarot.HEART_KING);
        h_.ajouter(CardTarot.SPADE_KING);
        h_.ajouter(CardTarot.DIAMOND_KING);
        h_.ajouter(CardTarot.CLUB_KING);
        ls_.add(h_);
        h_ = new HandTarot();
        h_.ajouter(CardTarot.HEART_QUEEN);
        h_.ajouter(CardTarot.HEART_10);
        h_.ajouter(CardTarot.HEART_8);
        h_.ajouter(CardTarot.HEART_6);
        h_.ajouter(CardTarot.HEART_5);
        h_.ajouter(CardTarot.HEART_1);
        h_.ajouter(CardTarot.SPADE_QUEEN);
        h_.ajouter(CardTarot.SPADE_10);
        h_.ajouter(CardTarot.SPADE_8);
        h_.ajouter(CardTarot.SPADE_6);
        h_.ajouter(CardTarot.SPADE_5);
        h_.ajouter(CardTarot.SPADE_1);
        h_.ajouter(CardTarot.DIAMOND_QUEEN);
        h_.ajouter(CardTarot.DIAMOND_10);
        h_.ajouter(CardTarot.DIAMOND_8);
        h_.ajouter(CardTarot.DIAMOND_6);
        h_.ajouter(CardTarot.DIAMOND_5);
        h_.ajouter(CardTarot.DIAMOND_1);
        h_.ajouter(CardTarot.CLUB_QUEEN);
        h_.ajouter(CardTarot.CLUB_10);
        h_.ajouter(CardTarot.CLUB_8);
        h_.ajouter(CardTarot.CLUB_6);
        h_.ajouter(CardTarot.CLUB_5);
        h_.ajouter(CardTarot.CLUB_1);
        ls_.add(h_);
        h_ = new HandTarot();
        h_.ajouter(CardTarot.HEART_KNIGHT);
        h_.ajouter(CardTarot.HEART_JACK);
        h_.ajouter(CardTarot.HEART_9);
        h_.ajouter(CardTarot.HEART_4);
        h_.ajouter(CardTarot.HEART_3);
        h_.ajouter(CardTarot.HEART_2);
        h_.ajouter(CardTarot.SPADE_KNIGHT);
        h_.ajouter(CardTarot.SPADE_JACK);
        h_.ajouter(CardTarot.SPADE_9);
        h_.ajouter(CardTarot.SPADE_4);
        h_.ajouter(CardTarot.SPADE_3);
        h_.ajouter(CardTarot.SPADE_2);
        h_.ajouter(CardTarot.DIAMOND_KNIGHT);
        h_.ajouter(CardTarot.DIAMOND_JACK);
        h_.ajouter(CardTarot.DIAMOND_9);
        h_.ajouter(CardTarot.DIAMOND_4);
        h_.ajouter(CardTarot.DIAMOND_3);
        h_.ajouter(CardTarot.DIAMOND_2);
        h_.ajouter(CardTarot.CLUB_KNIGHT);
        h_.ajouter(CardTarot.CLUB_JACK);
        h_.ajouter(CardTarot.CLUB_9);
        h_.ajouter(CardTarot.CLUB_4);
        h_.ajouter(CardTarot.CLUB_3);
        h_.ajouter(CardTarot.CLUB_2);
        ls_.add(h_);
        h_ = new HandTarot();
        h_.ajouter(CardTarot.TRUMP_21);
        h_.ajouter(CardTarot.TRUMP_20);
        h_.ajouter(CardTarot.HEART_7);
        h_.ajouter(CardTarot.SPADE_7);
        h_.ajouter(CardTarot.DIAMOND_7);
        h_.ajouter(CardTarot.CLUB_7);
        ls_.add(h_);
        return ls_;
    }
}
