package cards.belote;

import cards.belote.enumerations.BidBelote;
import cards.belote.enumerations.CardBelote;
import cards.consts.Suit;
import code.util.CustList;
import org.junit.Test;

public final class GameBeloteProgTrickTest extends CommonGameBelote {
    @Test
    public void enCours1Test() {
        RulesBelote r_ = new RulesBelote();
        byte d_ = 2;
        CustList<BidBeloteSuit> bids_ = new CustList<BidBeloteSuit>();
        BidBeloteSuit b_ = new BidBeloteSuit();
        b_.setSuit(Suit.HEART);
        b_.setEnchere(BidBelote.SUIT);
        bids_.add(b_);
        HandBelote h_ = new HandBelote();
        h_.ajouter(CardBelote.HEART_KING);
        h_.ajouter(CardBelote.HEART_7);
        h_.ajouter(CardBelote.CLUB_KING);
        h_.ajouter(CardBelote.CLUB_8);
        h_.ajouter(CardBelote.CLUB_7);
        h_.ajouter(CardBelote.DIAMOND_1);
        h_.ajouter(CardBelote.DIAMOND_KING);
        h_.ajouter(CardBelote.DIAMOND_JACK);
        HandBelote last_ = new HandBelote();
        last_.ajouter(CardBelote.HEART_JACK);
        CustList<TrickBelote> trs_ = new CustList<TrickBelote>();
        TrickBelote pr_ = new TrickBelote(r_.getRepartition().getNextPlayer(d_));
        pr_.ajouter(CardBelote.CLUB_1);
        pr_.ajouter(CardBelote.CLUB_QUEEN);
        pr_.ajouter(CardBelote.CLUB_JACK);
        DealBelote deal_ = new DealBelote(new CustList<HandBelote>(),d_);
        deal_.getDeal().add(create(CardBelote.HEART_9,CardBelote.HEART_1,CardBelote.HEART_10,CardBelote.HEART_QUEEN,CardBelote.HEART_8,CardBelote.SPADE_1,CardBelote.SPADE_10));
        deal_.getDeal().add(create(CardBelote.SPADE_KING,CardBelote.SPADE_QUEEN,CardBelote.SPADE_JACK,CardBelote.SPADE_9,CardBelote.SPADE_8,CardBelote.SPADE_7,CardBelote.DIAMOND_10));
        deal_.getDeal().add(create(CardBelote.HEART_KING,CardBelote.HEART_7,CardBelote.DIAMOND_1,CardBelote.DIAMOND_KING,CardBelote.DIAMOND_JACK,CardBelote.CLUB_KING,CardBelote.CLUB_8,CardBelote.CLUB_7));
        deal_.getDeal().add(create(CardBelote.HEART_JACK,CardBelote.DIAMOND_QUEEN,CardBelote.DIAMOND_9,CardBelote.DIAMOND_8,CardBelote.DIAMOND_7,CardBelote.CLUB_10,CardBelote.CLUB_9));
        deal_.getDeal().add(create(CardBelote.HEART_JACK,CardBelote.DIAMOND_QUEEN,CardBelote.DIAMOND_9,CardBelote.HEART_9,CardBelote.HEART_1,CardBelote.HEART_10,CardBelote.SPADE_KING,CardBelote.SPADE_QUEEN,CardBelote.SPADE_JACK,CardBelote.HEART_KING,CardBelote.HEART_7,CardBelote.DIAMOND_1));
        GameBelote g_ = newGameBeloteWithourDecl(r_, trs_, pr_, d_, bids_, deal_);
        GameBeloteTeamsRelation team_ = g_.getTeamsRelation();
        GameBeloteTrickInfo info_ = newGameBeloteTrickInfo(g_);
        GameBeloteProgTrick gt_ = newGameBeloteProgTrickDeal(g_, info_, team_, h_);
        assertSame(CardBelote.CLUB_7, gt_.enCours());
    }
    @Test
    public void enCours2Test() {
        RulesBelote r_ = new RulesBelote();
        r_.setSousCoupeAdv(false);
        byte d_ = 2;
        CustList<BidBeloteSuit> bids_ = new CustList<BidBeloteSuit>();
        BidBeloteSuit b_ = new BidBeloteSuit();
        b_.setSuit(Suit.HEART);
        b_.setEnchere(BidBelote.SUIT);
        bids_.add(b_);
        HandBelote h_ = new HandBelote();
        h_.ajouter(CardBelote.SPADE_7);
        h_.ajouter(CardBelote.HEART_QUEEN);
        h_.ajouter(CardBelote.SPADE_KING);
        h_.ajouter(CardBelote.SPADE_8);
        h_.ajouter(CardBelote.HEART_8);
        h_.ajouter(CardBelote.DIAMOND_1);
        h_.ajouter(CardBelote.DIAMOND_KING);
        h_.ajouter(CardBelote.DIAMOND_JACK);
        HandBelote last_ = new HandBelote();
        last_.ajouter(CardBelote.HEART_7);
        CustList<TrickBelote> trs_ = new CustList<TrickBelote>();
        TrickBelote pr_ = new TrickBelote(r_.getRepartition().getNextPlayer(d_));
        pr_.ajouter(CardBelote.CLUB_10);
        pr_.ajouter(CardBelote.HEART_1);
        DealBelote deal_ = new DealBelote(new CustList<HandBelote>(),d_);
        deal_.getDeal().add(create(CardBelote.HEART_JACK,CardBelote.HEART_9,CardBelote.HEART_10,CardBelote.HEART_KING,CardBelote.SPADE_1,CardBelote.SPADE_10,CardBelote.SPADE_QUEEN));
        deal_.getDeal().add(create(CardBelote.HEART_QUEEN,CardBelote.HEART_8,CardBelote.SPADE_KING,CardBelote.SPADE_8,CardBelote.SPADE_7,CardBelote.DIAMOND_1,CardBelote.DIAMOND_KING,CardBelote.DIAMOND_JACK));
        deal_.getDeal().add(create(CardBelote.SPADE_JACK,CardBelote.SPADE_9,CardBelote.DIAMOND_10,CardBelote.DIAMOND_QUEEN,CardBelote.DIAMOND_9,CardBelote.DIAMOND_8,CardBelote.DIAMOND_7,CardBelote.CLUB_1));
        deal_.getDeal().add(create(CardBelote.HEART_7,CardBelote.CLUB_KING,CardBelote.CLUB_QUEEN,CardBelote.CLUB_JACK,CardBelote.CLUB_9,CardBelote.CLUB_8,CardBelote.CLUB_7));
        deal_.getDeal().add(create(CardBelote.HEART_7,CardBelote.CLUB_KING,CardBelote.CLUB_QUEEN,CardBelote.HEART_JACK,CardBelote.HEART_9,CardBelote.HEART_10,CardBelote.HEART_QUEEN,CardBelote.HEART_8,CardBelote.SPADE_KING,CardBelote.SPADE_JACK,CardBelote.SPADE_9,CardBelote.DIAMOND_10));
        GameBelote g_ = newGameBeloteWithourDecl(r_, trs_, pr_, d_, bids_, deal_);
        GameBeloteTeamsRelation team_ = g_.getTeamsRelation();
        GameBeloteTrickInfo info_ = newGameBeloteTrickInfo(g_);
        GameBeloteProgTrick gt_ = newGameBeloteProgTrickDeal(g_, info_, team_, h_);
        assertSame(CardBelote.SPADE_7, gt_.enCours());
    }
    @Test
    public void enCours3Test() {
        RulesBelote r_ = new RulesBelote();
        byte d_ = 2;
        CustList<BidBeloteSuit> bids_ = new CustList<BidBeloteSuit>();
        BidBeloteSuit b_ = new BidBeloteSuit();
        b_.setSuit(Suit.HEART);
        b_.setEnchere(BidBelote.SUIT);
        bids_.add(b_);
        HandBelote h_ = new HandBelote();
        h_.ajouter(CardBelote.SPADE_1);
        h_.ajouter(CardBelote.SPADE_7);
        h_.ajouter(CardBelote.SPADE_8);
        h_.ajouter(CardBelote.SPADE_JACK);
        h_.ajouter(CardBelote.DIAMOND_QUEEN);
        h_.ajouter(CardBelote.DIAMOND_1);
        h_.ajouter(CardBelote.DIAMOND_KING);
        h_.ajouter(CardBelote.DIAMOND_JACK);
        HandBelote last_ = new HandBelote();
        last_.ajouter(CardBelote.HEART_JACK);
        CustList<TrickBelote> trs_ = new CustList<TrickBelote>();
        TrickBelote pr_ = new TrickBelote(r_.getRepartition().getNextPlayer(d_));
        pr_.ajouter(CardBelote.CLUB_1);
        pr_.ajouter(CardBelote.CLUB_QUEEN);
        pr_.ajouter(CardBelote.CLUB_JACK);
        DealBelote deal_ = new DealBelote(new CustList<HandBelote>(),d_);
        deal_.getDeal().add(create(CardBelote.HEART_9,CardBelote.HEART_1,CardBelote.HEART_10,CardBelote.HEART_KING,CardBelote.HEART_QUEEN,CardBelote.HEART_8,CardBelote.HEART_7));
        deal_.getDeal().add(create(CardBelote.SPADE_10,CardBelote.SPADE_KING,CardBelote.SPADE_QUEEN,CardBelote.SPADE_9,CardBelote.DIAMOND_10,CardBelote.DIAMOND_9,CardBelote.DIAMOND_8));
        deal_.getDeal().add(create(CardBelote.SPADE_1,CardBelote.SPADE_JACK,CardBelote.SPADE_8,CardBelote.SPADE_7,CardBelote.DIAMOND_1,CardBelote.DIAMOND_KING,CardBelote.DIAMOND_QUEEN,CardBelote.DIAMOND_JACK));
        deal_.getDeal().add(create(CardBelote.HEART_JACK,CardBelote.DIAMOND_7,CardBelote.CLUB_10,CardBelote.CLUB_KING,CardBelote.CLUB_9,CardBelote.CLUB_8,CardBelote.CLUB_7));
        deal_.getDeal().add(create(CardBelote.HEART_JACK,CardBelote.DIAMOND_7,CardBelote.CLUB_10,CardBelote.HEART_9,CardBelote.HEART_1,CardBelote.HEART_10,CardBelote.SPADE_10,CardBelote.SPADE_KING,CardBelote.SPADE_QUEEN,CardBelote.SPADE_1,CardBelote.SPADE_JACK,CardBelote.SPADE_8));
        GameBelote g_ = newGameBeloteWithourDecl(r_, trs_, pr_, d_, bids_, deal_);
        GameBeloteTeamsRelation team_ = g_.getTeamsRelation();
        GameBeloteTrickInfo info_ = newGameBeloteTrickInfo(g_);
        GameBeloteProgTrick gt_ = newGameBeloteProgTrickDeal(g_, info_, team_, h_);
        assertSame(CardBelote.SPADE_7, gt_.enCours());
    }
    @Test
    public void enCours4Test() {
        RulesBelote r_ = new RulesBelote();
        byte d_ = 2;
        CustList<BidBeloteSuit> bids_ = new CustList<BidBeloteSuit>();
        bids_.add(new BidBeloteSuit());
        BidBeloteSuit b_ = new BidBeloteSuit();
        b_.setSuit(Suit.HEART);
        b_.setEnchere(BidBelote.SUIT);
        bids_.add(b_);
        HandBelote h_ = new HandBelote();
        h_.ajouter(CardBelote.HEART_KING);
        h_.ajouter(CardBelote.HEART_7);
        h_.ajouter(CardBelote.CLUB_KING);
        h_.ajouter(CardBelote.CLUB_8);
        h_.ajouter(CardBelote.CLUB_7);
        h_.ajouter(CardBelote.DIAMOND_1);
        h_.ajouter(CardBelote.DIAMOND_KING);
        h_.ajouter(CardBelote.DIAMOND_JACK);
        HandBelote last_ = new HandBelote();
        last_.ajouter(CardBelote.HEART_JACK);
        CustList<TrickBelote> trs_ = new CustList<TrickBelote>();
        TrickBelote pr_ = new TrickBelote(r_.getRepartition().getNextPlayer(d_));
        pr_.ajouter(CardBelote.HEART_10);
        pr_.ajouter(CardBelote.HEART_JACK);
        pr_.ajouter(CardBelote.HEART_8);
        DealBelote deal_ = new DealBelote(new CustList<HandBelote>(),d_);
        deal_.getDeal().add(create(CardBelote.HEART_9,CardBelote.HEART_1,CardBelote.HEART_QUEEN,CardBelote.SPADE_1,CardBelote.SPADE_10,CardBelote.SPADE_KING,CardBelote.SPADE_QUEEN));
        deal_.getDeal().add(create(CardBelote.SPADE_JACK,CardBelote.SPADE_9,CardBelote.SPADE_8,CardBelote.SPADE_7,CardBelote.DIAMOND_10,CardBelote.DIAMOND_QUEEN,CardBelote.DIAMOND_9));
        deal_.getDeal().add(create(CardBelote.HEART_KING,CardBelote.HEART_7,CardBelote.DIAMOND_1,CardBelote.DIAMOND_KING,CardBelote.DIAMOND_JACK,CardBelote.CLUB_KING,CardBelote.CLUB_8,CardBelote.CLUB_7));
        deal_.getDeal().add(create(CardBelote.DIAMOND_8,CardBelote.DIAMOND_7,CardBelote.CLUB_1,CardBelote.CLUB_10,CardBelote.CLUB_QUEEN,CardBelote.CLUB_JACK,CardBelote.CLUB_9));
        deal_.getDeal().add(create(CardBelote.HEART_JACK,CardBelote.DIAMOND_8,CardBelote.DIAMOND_7,CardBelote.CLUB_1,CardBelote.HEART_9,CardBelote.HEART_1,CardBelote.SPADE_JACK,CardBelote.SPADE_9,CardBelote.SPADE_8,CardBelote.HEART_KING,CardBelote.HEART_7,CardBelote.DIAMOND_1));
        GameBelote g_ = newGameBeloteWithourDecl(r_, trs_, pr_, d_, bids_, deal_);
        GameBeloteTeamsRelation team_ = g_.getTeamsRelation();
        GameBeloteTrickInfo info_ = newGameBeloteTrickInfo(g_);
        GameBeloteProgTrick gt_ = newGameBeloteProgTrickDeal(g_, info_, team_, h_);
        assertSame(CardBelote.HEART_KING, gt_.enCours());
    }
    @Test
    public void enCours5Test() {
        RulesBelote r_ = new RulesBelote();
        byte d_ = 2;
        CustList<BidBeloteSuit> bids_ = new CustList<BidBeloteSuit>();
        bids_.add(new BidBeloteSuit());
        bids_.add(new BidBeloteSuit());
        BidBeloteSuit b_ = new BidBeloteSuit();
        b_.setSuit(Suit.CLUB);
        b_.setEnchere(BidBelote.SUIT);
        bids_.add(b_);
        HandBelote h_ = new HandBelote();
        h_.ajouter(CardBelote.SPADE_1);
        h_.ajouter(CardBelote.SPADE_7);
        h_.ajouter(CardBelote.SPADE_8);
        h_.ajouter(CardBelote.SPADE_JACK);
        h_.ajouter(CardBelote.DIAMOND_QUEEN);
        h_.ajouter(CardBelote.DIAMOND_1);
        h_.ajouter(CardBelote.DIAMOND_KING);
        h_.ajouter(CardBelote.DIAMOND_JACK);
        HandBelote last_ = new HandBelote();
        last_.ajouter(CardBelote.CLUB_JACK);
        CustList<TrickBelote> trs_ = new CustList<TrickBelote>();
        TrickBelote pr_ = new TrickBelote(r_.getRepartition().getNextPlayer(d_));
        pr_.ajouter(CardBelote.CLUB_8);
        pr_.ajouter(CardBelote.CLUB_QUEEN);
        pr_.ajouter(CardBelote.CLUB_JACK);
        DealBelote deal_ = new DealBelote(new CustList<HandBelote>(),d_);
        deal_.getDeal().add(create(CardBelote.HEART_1,CardBelote.HEART_10,CardBelote.HEART_KING,CardBelote.HEART_QUEEN,CardBelote.HEART_JACK,CardBelote.HEART_9,CardBelote.HEART_8));
        deal_.getDeal().add(create(CardBelote.HEART_7,CardBelote.SPADE_10,CardBelote.SPADE_KING,CardBelote.SPADE_QUEEN,CardBelote.SPADE_9,CardBelote.DIAMOND_10,CardBelote.DIAMOND_9));
        deal_.getDeal().add(create(CardBelote.SPADE_1,CardBelote.SPADE_JACK,CardBelote.SPADE_8,CardBelote.SPADE_7,CardBelote.DIAMOND_1,CardBelote.DIAMOND_KING,CardBelote.DIAMOND_QUEEN,CardBelote.DIAMOND_JACK));
        deal_.getDeal().add(create(CardBelote.DIAMOND_8,CardBelote.DIAMOND_7,CardBelote.CLUB_9,CardBelote.CLUB_1,CardBelote.CLUB_10,CardBelote.CLUB_KING,CardBelote.CLUB_7));
        deal_.getDeal().add(create(CardBelote.CLUB_JACK,CardBelote.DIAMOND_8,CardBelote.DIAMOND_7,CardBelote.CLUB_9,CardBelote.HEART_1,CardBelote.HEART_10,CardBelote.HEART_KING,CardBelote.HEART_7,CardBelote.SPADE_10,CardBelote.SPADE_1,CardBelote.SPADE_JACK,CardBelote.SPADE_8));
        GameBelote g_ = newGameBeloteWithourDecl(r_, trs_, pr_, d_, bids_, deal_);
        GameBeloteTeamsRelation team_ = g_.getTeamsRelation();
        GameBeloteTrickInfo info_ = newGameBeloteTrickInfo(g_);
        GameBeloteProgTrick gt_ = newGameBeloteProgTrickDeal(g_, info_, team_, h_);
        assertSame(CardBelote.SPADE_7, gt_.enCours());
    }
    @Test
    public void enCours6Test() {
        RulesBelote r_ = new RulesBelote();
        r_.getAllowedBids().put(BidBelote.NO_TRUMP,true);
        byte d_ = 2;
        CustList<BidBeloteSuit> bids_ = new CustList<BidBeloteSuit>();
        BidBeloteSuit b_ = new BidBeloteSuit();
        b_.setSuit(Suit.UNDEFINED);
        b_.setEnchere(BidBelote.NO_TRUMP);
        bids_.add(b_);
        HandBelote h_ = new HandBelote();
        h_.ajouter(CardBelote.HEART_KING);
        h_.ajouter(CardBelote.HEART_7);
        h_.ajouter(CardBelote.CLUB_KING);
        h_.ajouter(CardBelote.CLUB_8);
        h_.ajouter(CardBelote.HEART_8);
        h_.ajouter(CardBelote.DIAMOND_1);
        h_.ajouter(CardBelote.DIAMOND_KING);
        h_.ajouter(CardBelote.DIAMOND_JACK);
        HandBelote last_ = new HandBelote();
        last_.ajouter(CardBelote.HEART_JACK);
        CustList<TrickBelote> trs_ = new CustList<TrickBelote>();
        TrickBelote pr_ = new TrickBelote(r_.getRepartition().getNextPlayer(d_));
        pr_.ajouter(CardBelote.CLUB_10);
        pr_.ajouter(CardBelote.CLUB_7);
        DealBelote deal_ = new DealBelote(new CustList<HandBelote>(),d_);
        deal_.getDeal().add(create(CardBelote.HEART_1,CardBelote.HEART_10,CardBelote.HEART_QUEEN,CardBelote.HEART_9,CardBelote.SPADE_1,CardBelote.SPADE_10,CardBelote.SPADE_KING));
        deal_.getDeal().add(create(CardBelote.HEART_KING,CardBelote.HEART_8,CardBelote.HEART_7,CardBelote.DIAMOND_1,CardBelote.DIAMOND_KING,CardBelote.DIAMOND_JACK,CardBelote.CLUB_KING,CardBelote.CLUB_8));
        deal_.getDeal().add(create(CardBelote.SPADE_QUEEN,CardBelote.SPADE_JACK,CardBelote.SPADE_9,CardBelote.SPADE_8,CardBelote.SPADE_7,CardBelote.DIAMOND_10,CardBelote.DIAMOND_QUEEN,CardBelote.DIAMOND_9));
        deal_.getDeal().add(create(CardBelote.HEART_JACK,CardBelote.DIAMOND_8,CardBelote.DIAMOND_7,CardBelote.CLUB_1,CardBelote.CLUB_QUEEN,CardBelote.CLUB_JACK,CardBelote.CLUB_9));
        deal_.getDeal().add(create(CardBelote.HEART_JACK,CardBelote.DIAMOND_8,CardBelote.DIAMOND_7,CardBelote.HEART_1,CardBelote.HEART_10,CardBelote.HEART_QUEEN,CardBelote.HEART_KING,CardBelote.HEART_8,CardBelote.HEART_7,CardBelote.SPADE_QUEEN,CardBelote.SPADE_JACK,CardBelote.SPADE_9));
        GameBelote g_ = newGameBeloteWithourDecl(r_, trs_, pr_, d_, bids_, deal_);
        GameBeloteTeamsRelation team_ = g_.getTeamsRelation();
        GameBeloteTrickInfo info_ = newGameBeloteTrickInfo(g_);
        GameBeloteProgTrick gt_ = newGameBeloteProgTrickDeal(g_, info_, team_, h_);
        assertSame(CardBelote.CLUB_8, gt_.enCours());
    }
    @Test
    public void enCours7Test() {
        RulesBelote r_ = new RulesBelote();
        r_.getAllowedBids().put(BidBelote.NO_TRUMP,true);
        byte d_ = 2;
        CustList<BidBeloteSuit> bids_ = new CustList<BidBeloteSuit>();
        bids_.add(new BidBeloteSuit());
        bids_.add(new BidBeloteSuit());
        BidBeloteSuit b_ = new BidBeloteSuit();
        b_.setSuit(Suit.UNDEFINED);
        b_.setEnchere(BidBelote.NO_TRUMP);
        bids_.add(b_);
        HandBelote h_ = new HandBelote();
        h_.ajouter(CardBelote.SPADE_1);
        h_.ajouter(CardBelote.SPADE_7);
        h_.ajouter(CardBelote.SPADE_8);
        h_.ajouter(CardBelote.SPADE_JACK);
        h_.ajouter(CardBelote.DIAMOND_QUEEN);
        h_.ajouter(CardBelote.DIAMOND_1);
        h_.ajouter(CardBelote.DIAMOND_KING);
        h_.ajouter(CardBelote.DIAMOND_JACK);
        HandBelote last_ = new HandBelote();
        last_.ajouter(CardBelote.CLUB_1);
        CustList<TrickBelote> trs_ = new CustList<TrickBelote>();
        TrickBelote pr_ = new TrickBelote(r_.getRepartition().getNextPlayer(d_));
        pr_.ajouter(CardBelote.CLUB_8);
        pr_.ajouter(CardBelote.CLUB_QUEEN);
        pr_.ajouter(CardBelote.CLUB_1);
        DealBelote deal_ = new DealBelote(new CustList<HandBelote>(),d_);
        deal_.getDeal().add(create(CardBelote.HEART_1,CardBelote.HEART_10,CardBelote.HEART_KING,CardBelote.HEART_QUEEN,CardBelote.HEART_JACK,CardBelote.HEART_9,CardBelote.HEART_8));
        deal_.getDeal().add(create(CardBelote.HEART_7,CardBelote.SPADE_10,CardBelote.SPADE_KING,CardBelote.SPADE_QUEEN,CardBelote.SPADE_9,CardBelote.DIAMOND_10,CardBelote.DIAMOND_9));
        deal_.getDeal().add(create(CardBelote.SPADE_1,CardBelote.SPADE_JACK,CardBelote.SPADE_8,CardBelote.SPADE_7,CardBelote.DIAMOND_1,CardBelote.DIAMOND_KING,CardBelote.DIAMOND_QUEEN,CardBelote.DIAMOND_JACK));
        deal_.getDeal().add(create(CardBelote.DIAMOND_8,CardBelote.DIAMOND_7,CardBelote.CLUB_10,CardBelote.CLUB_KING,CardBelote.CLUB_JACK,CardBelote.CLUB_9,CardBelote.CLUB_7));
        deal_.getDeal().add(create(CardBelote.CLUB_1,CardBelote.DIAMOND_8,CardBelote.DIAMOND_7,CardBelote.CLUB_10,CardBelote.HEART_1,CardBelote.HEART_10,CardBelote.HEART_KING,CardBelote.HEART_7,CardBelote.SPADE_10,CardBelote.SPADE_1,CardBelote.SPADE_JACK,CardBelote.SPADE_8));
        GameBelote g_ = newGameBeloteWithourDecl(r_, trs_, pr_, d_, bids_, deal_);
        GameBeloteTeamsRelation team_ = g_.getTeamsRelation();
        GameBeloteTrickInfo info_ = newGameBeloteTrickInfo(g_);
        GameBeloteProgTrick gt_ = newGameBeloteProgTrickDeal(g_, info_, team_, h_);
        assertSame(CardBelote.SPADE_7, gt_.enCours());
    }
    @Test
    public void enCours8Test() {
        RulesBelote r_ = new RulesBelote();
        r_.getAllowedBids().put(BidBelote.ALL_TRUMP,true);
        byte d_ = 2;
        CustList<BidBeloteSuit> bids_ = new CustList<BidBeloteSuit>();
        BidBeloteSuit b_ = new BidBeloteSuit();
        b_.setSuit(Suit.UNDEFINED);
        b_.setEnchere(BidBelote.ALL_TRUMP);
        bids_.add(b_);
        HandBelote h_ = new HandBelote();
        h_.ajouter(CardBelote.HEART_KING);
        h_.ajouter(CardBelote.HEART_7);
        h_.ajouter(CardBelote.CLUB_KING);
        h_.ajouter(CardBelote.CLUB_8);
        h_.ajouter(CardBelote.CLUB_7);
        h_.ajouter(CardBelote.DIAMOND_1);
        h_.ajouter(CardBelote.DIAMOND_KING);
        h_.ajouter(CardBelote.DIAMOND_JACK);
        HandBelote last_ = new HandBelote();
        last_.ajouter(CardBelote.HEART_JACK);
        CustList<TrickBelote> trs_ = new CustList<TrickBelote>();
        TrickBelote pr_ = new TrickBelote(r_.getRepartition().getNextPlayer(d_));
        pr_.ajouter(CardBelote.HEART_JACK);
        pr_.ajouter(CardBelote.HEART_10);
        pr_.ajouter(CardBelote.HEART_8);
        DealBelote deal_ = new DealBelote(new CustList<HandBelote>(),d_);
        deal_.getDeal().add(create(CardBelote.HEART_9,CardBelote.HEART_1,CardBelote.HEART_QUEEN,CardBelote.SPADE_JACK,CardBelote.SPADE_9,CardBelote.SPADE_1,CardBelote.SPADE_10));
        deal_.getDeal().add(create(CardBelote.SPADE_KING,CardBelote.SPADE_QUEEN,CardBelote.SPADE_8,CardBelote.SPADE_7,CardBelote.DIAMOND_9,CardBelote.DIAMOND_10,CardBelote.DIAMOND_QUEEN));
        deal_.getDeal().add(create(CardBelote.HEART_KING,CardBelote.HEART_7,CardBelote.DIAMOND_JACK,CardBelote.DIAMOND_1,CardBelote.DIAMOND_KING,CardBelote.CLUB_KING,CardBelote.CLUB_8,CardBelote.CLUB_7));
        deal_.getDeal().add(create(CardBelote.DIAMOND_8,CardBelote.DIAMOND_7,CardBelote.CLUB_JACK,CardBelote.CLUB_9,CardBelote.CLUB_1,CardBelote.CLUB_10,CardBelote.CLUB_QUEEN));
        deal_.getDeal().add(create(CardBelote.HEART_JACK,CardBelote.DIAMOND_8,CardBelote.DIAMOND_7,CardBelote.HEART_9,CardBelote.HEART_1,CardBelote.HEART_QUEEN,CardBelote.SPADE_KING,CardBelote.SPADE_QUEEN,CardBelote.SPADE_8,CardBelote.HEART_KING,CardBelote.HEART_7,CardBelote.DIAMOND_JACK));
        GameBelote g_ = newGameBeloteWithourDecl(r_, trs_, pr_, d_, bids_, deal_);
        GameBeloteTeamsRelation team_ = g_.getTeamsRelation();
        GameBeloteTrickInfo info_ = newGameBeloteTrickInfo(g_);
        GameBeloteProgTrick gt_ = newGameBeloteProgTrickDeal(g_, info_, team_, h_);
        assertSame(CardBelote.HEART_7, gt_.enCours());
    }
    @Test
    public void enCours9Test() {
        RulesBelote r_ = new RulesBelote();
        r_.getAllowedBids().put(BidBelote.ALL_TRUMP,true);
        byte d_ = 2;
        CustList<BidBeloteSuit> bids_ = new CustList<BidBeloteSuit>();
        bids_.add(new BidBeloteSuit());
        bids_.add(new BidBeloteSuit());
        BidBeloteSuit b_ = new BidBeloteSuit();
        b_.setSuit(Suit.UNDEFINED);
        b_.setEnchere(BidBelote.ALL_TRUMP);
        bids_.add(b_);
        HandBelote h_ = new HandBelote();
        h_.ajouter(CardBelote.SPADE_1);
        h_.ajouter(CardBelote.SPADE_7);
        h_.ajouter(CardBelote.SPADE_8);
        h_.ajouter(CardBelote.SPADE_JACK);
        h_.ajouter(CardBelote.DIAMOND_QUEEN);
        h_.ajouter(CardBelote.DIAMOND_1);
        h_.ajouter(CardBelote.DIAMOND_KING);
        h_.ajouter(CardBelote.DIAMOND_JACK);
        HandBelote last_ = new HandBelote();
        last_.ajouter(CardBelote.CLUB_JACK);
        CustList<TrickBelote> trs_ = new CustList<TrickBelote>();
        TrickBelote pr_ = new TrickBelote(r_.getRepartition().getNextPlayer(d_));
        pr_.ajouter(CardBelote.CLUB_8);
        pr_.ajouter(CardBelote.CLUB_QUEEN);
        pr_.ajouter(CardBelote.CLUB_JACK);
        DealBelote deal_ = new DealBelote(new CustList<HandBelote>(),d_);
        deal_.getDeal().add(create(CardBelote.HEART_JACK,CardBelote.HEART_9,CardBelote.HEART_1,CardBelote.HEART_10,CardBelote.HEART_KING,CardBelote.HEART_QUEEN,CardBelote.HEART_8));
        deal_.getDeal().add(create(CardBelote.HEART_7,CardBelote.SPADE_9,CardBelote.SPADE_10,CardBelote.SPADE_KING,CardBelote.SPADE_QUEEN,CardBelote.DIAMOND_9,CardBelote.DIAMOND_10));
        deal_.getDeal().add(create(CardBelote.SPADE_JACK,CardBelote.SPADE_1,CardBelote.SPADE_8,CardBelote.SPADE_7,CardBelote.DIAMOND_JACK,CardBelote.DIAMOND_1,CardBelote.DIAMOND_KING,CardBelote.DIAMOND_QUEEN));
        deal_.getDeal().add(create(CardBelote.DIAMOND_8,CardBelote.DIAMOND_7,CardBelote.CLUB_9,CardBelote.CLUB_1,CardBelote.CLUB_10,CardBelote.CLUB_KING,CardBelote.CLUB_7));
        deal_.getDeal().add(create(CardBelote.CLUB_JACK,CardBelote.DIAMOND_8,CardBelote.DIAMOND_7,CardBelote.CLUB_9,CardBelote.HEART_JACK,CardBelote.HEART_9,CardBelote.HEART_1,CardBelote.HEART_7,CardBelote.SPADE_9,CardBelote.SPADE_JACK,CardBelote.SPADE_1,CardBelote.SPADE_8));
        GameBelote g_ = newGameBeloteWithourDecl(r_, trs_, pr_, d_, bids_, deal_);
        GameBeloteTeamsRelation team_ = g_.getTeamsRelation();
        GameBeloteTrickInfo info_ = newGameBeloteTrickInfo(g_);
        GameBeloteProgTrick gt_ = newGameBeloteProgTrickDeal(g_, info_, team_, h_);
        assertSame(CardBelote.SPADE_7, gt_.enCours());
    }
    @Test
    public void enCours10Test() {
        RulesBelote r_ = new RulesBelote();
        r_.getAllowedBids().put(BidBelote.NO_TRUMP,true);
        byte d_ = 2;
        CustList<BidBeloteSuit> bids_ = new CustList<BidBeloteSuit>();
        BidBeloteSuit b_ = new BidBeloteSuit();
        b_.setSuit(Suit.UNDEFINED);
        b_.setEnchere(BidBelote.NO_TRUMP);
        bids_.add(b_);
        HandBelote h_ = new HandBelote();
        h_.ajouter(CardBelote.HEART_KING);
        h_.ajouter(CardBelote.HEART_7);
        h_.ajouter(CardBelote.HEART_9);
        h_.ajouter(CardBelote.CLUB_8);
        h_.ajouter(CardBelote.HEART_8);
        h_.ajouter(CardBelote.DIAMOND_1);
        h_.ajouter(CardBelote.DIAMOND_KING);
        h_.ajouter(CardBelote.DIAMOND_JACK);
        HandBelote last_ = new HandBelote();
        last_.ajouter(CardBelote.HEART_JACK);
        CustList<TrickBelote> trs_ = new CustList<TrickBelote>();
        TrickBelote pr_ = new TrickBelote(r_.getRepartition().getNextPlayer(d_));
        pr_.ajouter(CardBelote.CLUB_10);
        pr_.ajouter(CardBelote.CLUB_7);
        DealBelote deal_ = new DealBelote(new CustList<HandBelote>(),d_);
        deal_.getDeal().add(create(CardBelote.HEART_1,CardBelote.HEART_10,CardBelote.HEART_QUEEN,CardBelote.SPADE_1,CardBelote.SPADE_10,CardBelote.SPADE_KING,CardBelote.SPADE_QUEEN));
        deal_.getDeal().add(create(CardBelote.HEART_KING,CardBelote.HEART_9,CardBelote.HEART_8,CardBelote.HEART_7,CardBelote.DIAMOND_1,CardBelote.DIAMOND_KING,CardBelote.DIAMOND_JACK,CardBelote.CLUB_8));
        deal_.getDeal().add(create(CardBelote.SPADE_JACK,CardBelote.SPADE_9,CardBelote.SPADE_8,CardBelote.SPADE_7,CardBelote.DIAMOND_10,CardBelote.DIAMOND_QUEEN,CardBelote.DIAMOND_9,CardBelote.DIAMOND_8));
        deal_.getDeal().add(create(CardBelote.HEART_JACK,CardBelote.DIAMOND_7,CardBelote.CLUB_1,CardBelote.CLUB_KING,CardBelote.CLUB_QUEEN,CardBelote.CLUB_JACK,CardBelote.CLUB_9));
        deal_.getDeal().add(create(CardBelote.HEART_JACK,CardBelote.DIAMOND_7,CardBelote.CLUB_1,CardBelote.HEART_1,CardBelote.HEART_10,CardBelote.HEART_QUEEN,CardBelote.HEART_KING,CardBelote.HEART_9,CardBelote.HEART_8,CardBelote.SPADE_JACK,CardBelote.SPADE_9,CardBelote.SPADE_8));
        GameBelote g_ = newGameBeloteWithourDecl(r_, trs_, pr_, d_, bids_, deal_);
        GameBeloteTeamsRelation team_ = g_.getTeamsRelation();
        GameBeloteTrickInfo info_ = newGameBeloteTrickInfo(g_);
        GameBeloteProgTrick gt_ = newGameBeloteProgTrickDeal(g_, info_, team_, h_);
        assertSame(CardBelote.CLUB_8, gt_.enCours());
    }
}
