package code.scripts.confs;

import code.bean.nat.NatDualConfigurationContext;
import code.util.CollCapacity;
import code.util.StringList;
import code.util.StringMap;

public final class PkScriptPages {
public static final String ABILITY_ABILITIES="ability/abilities";
public static final String ABILITY_ABILITY="ability/ability";
public static final String COMBO_COMBO="combo/combo";
public static final String DIFFICULTY="difficulty";
public static final String ENDROUND_ENDROUND="endround/endround";
public static final String ENDROUND_EVENT="endround/event";
public static final String ENDROUND_FOE="endround/foe";
public static final String ENDROUND_INDIVIDUAL="endround/individual";
public static final String ENDROUND_MULTIRELATION="endround/multirelation";
public static final String ENDROUND_POSITIONRELATION="endround/positionrelation";
public static final String ENDROUND_POSITIONTARGET="endround/positiontarget";
public static final String ENDROUND_SINGLERELATION="endround/singlerelation";
public static final String ENDROUND_STATUS="endround/status";
public static final String ENDROUND_STATUSRELATION="endround/statusrelation";
public static final String ENDROUND_TEAM="endround/team";
public static final String FIGHT="fight";
public static final String FIGHTER="fighter";
public static final String GAMEPROG="gameprog";
public static final String GENERAL_GENERAL="general/general";
public static final String INDEX="index";
public static final String ITEMS_BALL="items/ball";
public static final String ITEMS_BERRY="items/berry";
public static final String ITEMS_BOOST="items/boost";
public static final String ITEMS_EVOITEM="items/evoitem";
public static final String ITEMS_EVOSTONE="items/evostone";
public static final String ITEMS_FOSSIL="items/fossil";
public static final String ITEMS_HEALINGHP="items/healinghp";
public static final String ITEMS_HEALINGHPSTATUS="items/healinghpstatus";
public static final String ITEMS_HEALINGITEM="items/healingitem";
public static final String ITEMS_HEALINGPP="items/healingpp";
public static final String ITEMS_HEALINGSTATUS="items/healingstatus";
public static final String ITEMS_ITEM="items/item";
public static final String ITEMS_ITEMFORBATTLE="items/itemforbattle";
public static final String ITEMS_ITEMS="items/items";
public static final String ITEMS_REPEL="items/repel";
public static final String LANGS_LANGS="langs/langs";
public static final String MAP_LEVEL="map/level";
public static final String MAP_POKEMON_KEY="map/pokemon_key";
public static final String MOVES_DATA="moves/data";
public static final String MOVES_EFFECTS_EFF="moves/effects/eff";
public static final String MOVES_EFFECTS_EFFACCURACY="moves/effects/effaccuracy";
public static final String MOVES_EFFECTS_EFFALLY="moves/effects/effally";
public static final String MOVES_EFFECTS_EFFBATONPASS="moves/effects/effbatonpass";
public static final String MOVES_EFFECTS_EFFCLONE="moves/effects/effclone";
public static final String MOVES_EFFECTS_EFFCOMMONSTATISTICS="moves/effects/effcommonstatistics";
public static final String MOVES_EFFECTS_EFFCOPYFIGHTER="moves/effects/effcopyfighter";
public static final String MOVES_EFFECTS_EFFCOPYMOVE="moves/effects/effcopymove";
public static final String MOVES_EFFECTS_EFFCOUNTERATTACK="moves/effects/effcounterattack";
public static final String MOVES_EFFECTS_EFFDAMAGE="moves/effects/effdamage";
public static final String MOVES_EFFECTS_EFFDAMAGERATE="moves/effects/effdamagerate";
public static final String MOVES_EFFECTS_EFFENDROUND="moves/effects/effendround";
public static final String MOVES_EFFECTS_EFFFULLHPRATE="moves/effects/efffullhprate";
public static final String MOVES_EFFECTS_EFFGLOBAL="moves/effects/effglobal";
public static final String MOVES_EFFECTS_EFFINVOKE="moves/effects/effinvoke";
public static final String MOVES_EFFECTS_EFFMULTSUFFEREDMOVEPOWER="moves/effects/effmultsufferedmovepower";
public static final String MOVES_EFFECTS_EFFMULTUSEDMOVEPOWER="moves/effects/effmultusedmovepower";
public static final String MOVES_EFFECTS_EFFORDER="moves/effects/efforder";
public static final String MOVES_EFFECTS_EFFPROTECTFROMTYPES="moves/effects/effprotectfromtypes";
public static final String MOVES_EFFECTS_EFFPROTECTION="moves/effects/effprotection";
public static final String MOVES_EFFECTS_EFFREMAINEDHPRATE="moves/effects/effremainedhprate";
public static final String MOVES_EFFECTS_EFFRESTRICTION="moves/effects/effrestriction";
public static final String MOVES_EFFECTS_EFFSTATIS="moves/effects/effstatis";
public static final String MOVES_EFFECTS_EFFSTATUS="moves/effects/effstatus";
public static final String MOVES_EFFECTS_EFFSWITCHABILITIES="moves/effects/effswitchabilities";
public static final String MOVES_EFFECTS_EFFSWITCHITEMS="moves/effects/effswitchitems";
public static final String MOVES_EFFECTS_EFFSWITCHMOVESTYPES="moves/effects/effswitchmovestypes";
public static final String MOVES_EFFECTS_EFFSWITCHPOINTVIEW="moves/effects/effswitchpointview";
public static final String MOVES_EFFECTS_EFFSWITCHPOSITION="moves/effects/effswitchposition";
public static final String MOVES_EFFECTS_EFFSWITCHTYPES="moves/effects/effswitchtypes";
public static final String MOVES_EFFECTS_EFFTEAM="moves/effects/effteam";
public static final String MOVES_EFFECTS_EFFTEAMWHILESENDINGFOE="moves/effects/effteamwhilesendingfoe";
public static final String MOVES_EFFECTS_EFFUNPROTECTFROMTYPES="moves/effects/effunprotectfromtypes";
public static final String MOVES_EFFECTS_EFFVARPP="moves/effects/effvarpp";
public static final String MOVES_EFFECTS_EFFWINMONEY="moves/effects/effwinmoney";
public static final String MOVES_MOVES="moves/moves";
public static final String MSG_ABILITIES="msg_abilities";
public static final String MSG_ABILITY="msg_ability";
public static final String MSG_BALL="msg_ball";
public static final String MSG_BERRY="msg_berry";
public static final String MSG_BOOST="msg_boost";
public static final String MSG_COMBO="msg_combo";
public static final String MSG_DIFFICULTY="msg_difficulty";
public static final String MSG_EFF="msg_eff";
public static final String MSG_EFFACCURACY="msg_effaccuracy";
public static final String MSG_EFFALLY="msg_effally";
public static final String MSG_EFFBATONPASS="msg_effbatonpass";
public static final String MSG_EFFCLONE="msg_effclone";
public static final String MSG_EFFCOMMONSTATISTICS="msg_effcommonstatistics";
public static final String MSG_EFFCOPYFIGHTER="msg_effcopyfighter";
public static final String MSG_EFFCOPYMOVE="msg_effcopymove";
public static final String MSG_EFFCOUNTERATTACK="msg_effcounterattack";
public static final String MSG_EFFDAMAGE="msg_effdamage";
public static final String MSG_EFFDAMAGERATE="msg_effdamagerate";
public static final String MSG_EFFENDROUND="msg_effendround";
public static final String MSG_EFFFULLHPRATE="msg_efffullhprate";
public static final String MSG_EFFGLOBAL="msg_effglobal";
public static final String MSG_EFFINVOKE="msg_effinvoke";
public static final String MSG_EFFMULTSUFFEREDMOVEPOWER="msg_effmultsufferedmovepower";
public static final String MSG_EFFMULTUSEDMOVEPOWER="msg_effmultusedmovepower";
public static final String MSG_EFFORDER="msg_efforder";
public static final String MSG_EFFPROTECTFROMTYPES="msg_effprotectfromtypes";
public static final String MSG_EFFPROTECTION="msg_effprotection";
public static final String MSG_EFFREMAINEDHPRATE="msg_effremainedhprate";
public static final String MSG_EFFRESTRICTION="msg_effrestriction";
public static final String MSG_EFFSTATIS="msg_effstatis";
public static final String MSG_EFFSTATUS="msg_effstatus";
public static final String MSG_EFFSWITCHABILITIES="msg_effswitchabilities";
public static final String MSG_EFFSWITCHITEMS="msg_effswitchitems";
public static final String MSG_EFFSWITCHMOVETYPES="msg_effswitchmovetypes";
public static final String MSG_EFFSWITCHPOINTVIEW="msg_effswitchpointview";
public static final String MSG_EFFSWITCHPOSITION="msg_effswitchposition";
public static final String MSG_EFFSWITCHTYPES="msg_effswitchtypes";
public static final String MSG_EFFTEAM="msg_effteam";
public static final String MSG_EFFTEAMWHILESENDINGFOE="msg_effteamwhilesendingfoe";
public static final String MSG_EFFUNPROTECTFROMTYPES="msg_effunprotectfromtypes";
public static final String MSG_EFFVARPP="msg_effvarpp";
public static final String MSG_EFFWINMONEY="msg_effwinmoney";
public static final String MSG_EFF_SENDING="msg_eff_sending";
public static final String MSG_ENDROUND="msg_endround";
public static final String MSG_EVENT="msg_event";
public static final String MSG_EVOHAPPINESS="msg_evohappiness";
public static final String MSG_EVOITEM="msg_evoitem";
public static final String MSG_EVOLEVEL="msg_evolevel";
public static final String MSG_EVOLEVELGENDER="msg_evolevelgender";
public static final String MSG_EVOMOVE="msg_evomove";
public static final String MSG_EVOSTONE="msg_evostone";
public static final String MSG_EVOSTONEGENDER="msg_evostonegender";
public static final String MSG_EVOTEAM="msg_evoteam";
public static final String MSG_EVOTYPE="msg_evotype";
public static final String MSG_EVO_ITEM="msg_evo_item";
public static final String MSG_EVO_STONE="msg_evo_stone";
public static final String MSG_FIGHT="msg_fight";
public static final String MSG_FIGHTER="msg_fighter";
public static final String MSG_FOE="msg_foe";
public static final String MSG_FOSSIL="msg_fossil";
public static final String MSG_GENERALHELP="msg_generalhelp";
public static final String MSG_HEALINGHP="msg_healinghp";
public static final String MSG_HEALINGHPSTATUS="msg_healinghpstatus";
public static final String MSG_HEALINGITEM="msg_healingitem";
public static final String MSG_HEALINGPP="msg_healingpp";
public static final String MSG_HEALINGSTATUS="msg_healingstatus";
public static final String MSG_HELPROUND="msg_helpround";
public static final String MSG_INDEX="msg_index";
public static final String MSG_INDIVIDUAL="msg_individual";
public static final String MSG_ITEM="msg_item";
public static final String MSG_ITEMFORBATTLE="msg_itemforbattle";
public static final String MSG_ITEMS="msg_items";
public static final String MSG_LANG="msg_lang";
public static final String MSG_LEVELMAP="msg_levelmap";
public static final String MSG_LEVELSIMU="msg_levelsimu";
public static final String MSG_MOVEDATA="msg_movedata";
public static final String MSG_MOVES="msg_moves";
public static final String MSG_MULTIRELATION="msg_multirelation";
public static final String MSG_PKDATA="msg_pkdata";
public static final String MSG_POKEDEX="msg_pokedex";
public static final String MSG_POKEMON="msg_pokemon";
public static final String MSG_POKEMON_NPC="msg_pokemon_npc";
public static final String MSG_POSITIONRELATION="msg_positionrelation";
public static final String MSG_POSITIONTARGET="msg_positiontarget";
public static final String MSG_PROG="msg_prog";
public static final String MSG_REPEL="msg_repel";
public static final String MSG_SIMULATION="msg_simulation";
public static final String MSG_SINGLERELATION="msg_singlerelation";
public static final String MSG_SOLUTION="msg_solution";
public static final String MSG_STATUS="msg_status";
public static final String MSG_STATUSEND="msg_statusend";
public static final String MSG_STATUSRELATION="msg_statusrelation";
public static final String MSG_STATUSSET="msg_statusset";
public static final String MSG_TEAM="msg_team";
public static final String POKEMON="pokemon";
public static final String POKEMON_DATA="pokemon/data";
public static final String POKEMON_EVOLUTIONS_EVOHAPPINESS="pokemon/evolutions/evohappiness";
public static final String POKEMON_EVOLUTIONS_EVOITEM="pokemon/evolutions/evoitem";
public static final String POKEMON_EVOLUTIONS_EVOLEVEL="pokemon/evolutions/evolevel";
public static final String POKEMON_EVOLUTIONS_EVOLEVELGENDER="pokemon/evolutions/evolevelgender";
public static final String POKEMON_EVOLUTIONS_EVOMOVE="pokemon/evolutions/evomove";
public static final String POKEMON_EVOLUTIONS_EVOSTONE="pokemon/evolutions/evostone";
public static final String POKEMON_EVOLUTIONS_EVOSTONEGENDER="pokemon/evolutions/evostonegender";
public static final String POKEMON_EVOLUTIONS_EVOTEAM="pokemon/evolutions/evoteam";
public static final String POKEMON_EVOLUTIONS_EVOTYPE="pokemon/evolutions/evotype";
public static final String POKEMON_POKEDEX="pokemon/pokedex";
public static final String ROUND_ROUND="round/round";
public static final String SENDING_EFFSENDING="sending/effsending";
public static final String SIMULATION_LEVELSIMU="simulation/levelsimu";
public static final String SIMULATION_SIMULATION="simulation/simulation";
public static final String SOLUTION_SOLUTION="solution/solution";
public static final String STATUS_STATUS="status/status";
public static final String STATUS_STATUSSET="status/statusset";
public static final String TEAM="team";
public static final String REN_ADD_WEB_CSS_ABILITIES_CSS="web/css/abilities.css";
//public static final String REN_ADD_WEB_CSS_ATTAQUES_CSS="web/css/attaques.css";
//public static final String REN_ADD_WEB_CSS_CAPACITES_CSS="web/css/capacites.css";
public static final String REN_ADD_WEB_CSS_ITEMS_CSS="web/css/items.css";
public static final String REN_ADD_WEB_CSS_MOVES_CSS="web/css/moves.css";
//public static final String REN_ADD_WEB_CSS_OBJETS_CSS="web/css/objets.css";
public static final String REN_ADD_WEB_CSS_POKEDEX_CSS="web/css/pokedex.css";
public static final String REN_ADD_WEB_CSS_SIMULATION_CSS="web/css/simulation.css";
//public static final String REN_ADD_WEB_CSS_STATUTS_CSS="web/css/statuts.css";
public static final String REN_ADD_WEB_FIGHT_CSS_FIGHT_CSS="web_fight/css/fight.css";
public static final String REN_ADD_WEB_FIGHT_MESSAGES="web_fight/messages";
public static final String REN_ADD_WEB_GAME_CSS_DIFFICULTY_CSS="web_game/css/difficulty.css";
public static final String REN_ADD_WEB_GAME_MESSAGES="web_game/messages";
public static final String REN_ADD_WEB_HTML_ABILITY_ABILITIES_HTML="web/html/ability/abilities.html";
public static final String REN_ADD_WEB_HTML_ABILITY_ABILITY_HTML="web/html/ability/ability.html";
public static final String REN_ADD_WEB_HTML_ABILITY_DATA_HTML="web/html/ability/data.html";
public static final String REN_ADD_WEB_HTML_COMBO_COMBOS_HTML="web/html/combo/combos.html";
public static final String REN_ADD_WEB_HTML_COMBO_COMBO_HTML="web/html/combo/combo.html";
public static final String REN_ADD_WEB_HTML_ENDROUND_EFF_HTML="web/html/endround/eff.html";
public static final String REN_ADD_WEB_HTML_ENDROUND_ENDROUND_HTML="web/html/endround/endround.html";
public static final String REN_ADD_WEB_HTML_ENDROUND_FOE_HTML="web/html/endround/foe.html";
public static final String REN_ADD_WEB_HTML_ENDROUND_GLOBAL_HTML="web/html/endround/global.html";
public static final String REN_ADD_WEB_HTML_ENDROUND_INDIVIDUAL_HTML="web/html/endround/individual.html";
public static final String REN_ADD_WEB_HTML_ENDROUND_MULTIRELATION_HTML="web/html/endround/multirelation.html";
public static final String REN_ADD_WEB_HTML_ENDROUND_POSITIONRELATION_HTML="web/html/endround/positionrelation.html";
public static final String REN_ADD_WEB_HTML_ENDROUND_POSITIONTARGET_HTML="web/html/endround/positiontarget.html";
public static final String REN_ADD_WEB_HTML_ENDROUND_SINGLERELATION_HTML="web/html/endround/singlerelation.html";
public static final String REN_ADD_WEB_HTML_ENDROUND_STATUSRELATION_HTML="web/html/endround/statusrelation.html";
public static final String REN_ADD_WEB_HTML_ENDROUND_STATUS_HTML="web/html/endround/status.html";
public static final String REN_ADD_WEB_HTML_ENDROUND_TEAM_HTML="web/html/endround/team.html";
public static final String REN_ADD_WEB_HTML_GENERAL_GENERAL_HTML="web/html/general/general.html";
public static final String REN_ADD_WEB_HTML_ITEMS_BALL_HTML="web/html/items/ball.html";
public static final String REN_ADD_WEB_HTML_ITEMS_BERRY_HTML="web/html/items/berry.html";
public static final String REN_ADD_WEB_HTML_ITEMS_BOOST_HTML="web/html/items/boost.html";
public static final String REN_ADD_WEB_HTML_ITEMS_EVO_ITEM_HTML="web/html/items/evo_item.html";
public static final String REN_ADD_WEB_HTML_ITEMS_EVO_STONE_HTML="web/html/items/evo_stone.html";
public static final String REN_ADD_WEB_HTML_ITEMS_FOSSIL_HTML="web/html/items/fossil.html";
public static final String REN_ADD_WEB_HTML_ITEMS_HEALINGHPSTATUS_HTML="web/html/items/healinghpstatus.html";
public static final String REN_ADD_WEB_HTML_ITEMS_HEALINGHP_HTML="web/html/items/healinghp.html";
public static final String REN_ADD_WEB_HTML_ITEMS_HEALINGITEM_HTML="web/html/items/healingitem.html";
public static final String REN_ADD_WEB_HTML_ITEMS_HEALINGPP_HTML="web/html/items/healingpp.html";
public static final String REN_ADD_WEB_HTML_ITEMS_HEALINGSTATUS_HTML="web/html/items/healingstatus.html";
public static final String REN_ADD_WEB_HTML_ITEMS_ITEMFORBATTLE_HTML="web/html/items/itemforbattle.html";
public static final String REN_ADD_WEB_HTML_ITEMS_ITEMS_HTML="web/html/items/items.html";
public static final String REN_ADD_WEB_HTML_ITEMS_ITEM_HTML="web/html/items/item.html";
public static final String REN_ADD_WEB_HTML_ITEMS_REPEL_HTML="web/html/items/repel.html";
public static final String REN_ADD_WEB_HTML_ITEMS_SELLINGITEM_HTML="web/html/items/sellingitem.html";
public static final String REN_ADD_WEB_HTML_LANGS_LANGS_HTML="web/html/langs/langs.html";
public static final String REN_ADD_WEB_HTML_MAP_ELEMENTS_ALLY_HTML="web/html/map/elements/ally.html";
public static final String REN_ADD_WEB_HTML_MAP_ELEMENTS_AREA_HTML="web/html/map/elements/area.html";
public static final String REN_ADD_WEB_HTML_MAP_ELEMENTS_DEALER_HTML="web/html/map/elements/dealer.html";
public static final String REN_ADD_WEB_HTML_MAP_ELEMENTS_DUAL_FIGHT_HTML="web/html/map/elements/dual_fight.html";
public static final String REN_ADD_WEB_HTML_MAP_ELEMENTS_LEG_PK_HTML="web/html/map/elements/leg_pk.html";
public static final String REN_ADD_WEB_HTML_MAP_ELEMENTS_POKEMON_TEAM_HTML="web/html/map/elements/pokemon_team.html";
public static final String REN_ADD_WEB_HTML_MAP_ELEMENTS_SELLER_HTML="web/html/map/elements/seller.html";
public static final String REN_ADD_WEB_HTML_MAP_ELEMENTS_TRAINER_MULTI_FIGHT_HTML="web/html/map/elements/trainer_multi_fight.html";
public static final String REN_ADD_WEB_HTML_MAP_ELEMENTS_TRAINER_ONE_FIGHT_HTML="web/html/map/elements/trainer_one_fight.html";
public static final String REN_ADD_WEB_HTML_MAP_LEVEL_HTML="web/html/map/level.html";
public static final String REN_ADD_WEB_HTML_MAP_MAP_HTML="web/html/map/map.html";
public static final String REN_ADD_WEB_HTML_MOVES_DATA_HTML="web/html/moves/data.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFACCURACY_HTML="web/html/moves/effects/effaccuracy.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFALLY_HTML="web/html/moves/effects/effally.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFBATONPASS_HTML="web/html/moves/effects/effbatonpass.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFCLONE_HTML="web/html/moves/effects/effclone.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFCOMMONSTATISTICS_HTML="web/html/moves/effects/effcommonstatistics.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFCOPYFIGHTER_HTML="web/html/moves/effects/effcopyfighter.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFCOPYMOVE_HTML="web/html/moves/effects/effcopymove.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFCOUNTERATTACK_HTML="web/html/moves/effects/effcounterattack.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFDAMAGERATE_HTML="web/html/moves/effects/effdamagerate.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFDAMAGE_HTML="web/html/moves/effects/effdamage.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFENDROUND_HTML="web/html/moves/effects/effendround.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFFULLHPRATE_HTML="web/html/moves/effects/efffullhprate.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFGLOBAL_HTML="web/html/moves/effects/effglobal.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFINVOKE_HTML="web/html/moves/effects/effinvoke.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFMULTSUFFEREDMOVEPOWER_HTML="web/html/moves/effects/effmultsufferedmovepower.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFMULTUSEDMOVEPOWER_HTML="web/html/moves/effects/effmultusedmovepower.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFORDER_HTML="web/html/moves/effects/efforder.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFPROTECTFROMTYPES_HTML="web/html/moves/effects/effprotectfromtypes.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFPROTECTION_HTML="web/html/moves/effects/effprotection.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFREMAINEDHPRATE_HTML="web/html/moves/effects/effremainedhprate.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFRESTRICTION_HTML="web/html/moves/effects/effrestriction.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFSTATIS_HTML="web/html/moves/effects/effstatis.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFSTATUS_HTML="web/html/moves/effects/effstatus.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFSWITCHABILITIES_HTML="web/html/moves/effects/effswitchabilities.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFSWITCHITEMS_HTML="web/html/moves/effects/effswitchitems.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFSWITCHMOVETYPES_HTML="web/html/moves/effects/effswitchmovetypes.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFSWITCHPOINTVIEW_HTML="web/html/moves/effects/effswitchpointview.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFSWITCHPOSITION_HTML="web/html/moves/effects/effswitchposition.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFSWITCHTYPES_HTML="web/html/moves/effects/effswitchtypes.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFTEAMWHILESENDINGFOE_HTML="web/html/moves/effects/effteamwhilesendingfoe.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFTEAM_HTML="web/html/moves/effects/effteam.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFUNPROTECTFROMTYPES_HTML="web/html/moves/effects/effunprotectfromtypes.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFVARPP_HTML="web/html/moves/effects/effvarpp.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFWINMONEY_HTML="web/html/moves/effects/effwinmoney.html";
public static final String REN_ADD_WEB_HTML_MOVES_EFFECTS_EFF_HTML="web/html/moves/effects/eff.html";
//private static final String REN_ADD_WEB_HTML_MOVES_MOVELINE_HTML="web/html/moves/moveline.html";
public static final String REN_ADD_WEB_HTML_MOVES_MOVES_HTML="web/html/moves/moves.html";
public static final String REN_ADD_WEB_HTML_POKEMON_DATA_HTML="web/html/pokemon/data.html";
public static final String REN_ADD_WEB_HTML_POKEMON_EVOLUTIONS_EVOHAPPY_HTML="web/html/pokemon/evolutions/evohappy.html";
public static final String REN_ADD_WEB_HTML_POKEMON_EVOLUTIONS_EVOITEM_HTML="web/html/pokemon/evolutions/evoitem.html";
public static final String REN_ADD_WEB_HTML_POKEMON_EVOLUTIONS_EVOLEVELGENDER_HTML="web/html/pokemon/evolutions/evolevelgender.html";
public static final String REN_ADD_WEB_HTML_POKEMON_EVOLUTIONS_EVOLEVEL_HTML="web/html/pokemon/evolutions/evolevel.html";
public static final String REN_ADD_WEB_HTML_POKEMON_EVOLUTIONS_EVOMOVE_HTML="web/html/pokemon/evolutions/evomove.html";
public static final String REN_ADD_WEB_HTML_POKEMON_EVOLUTIONS_EVOSTONEGENDER_HTML="web/html/pokemon/evolutions/evostonegender.html";
public static final String REN_ADD_WEB_HTML_POKEMON_EVOLUTIONS_EVOSTONE_HTML="web/html/pokemon/evolutions/evostone.html";
public static final String REN_ADD_WEB_HTML_POKEMON_EVOLUTIONS_EVOTEAM_HTML="web/html/pokemon/evolutions/evoteam.html";
public static final String REN_ADD_WEB_HTML_POKEMON_EVOLUTIONS_EVOTYPE_HTML="web/html/pokemon/evolutions/evotype.html";
public static final String REN_ADD_WEB_HTML_POKEMON_POKEDEX_HTML="web/html/pokemon/pokedex.html";
public static final String REN_ADD_WEB_HTML_ROUND_HELPROUND_HTML="web/html/round/helpround.html";
public static final String REN_ADD_WEB_HTML_SENDING_EFFSENDING_HTML="web/html/sending/effsending.html";
public static final String REN_ADD_WEB_HTML_SIMULATION_ADDPOKEMON_HTML="web/html/simulation/addpokemon.html";
public static final String REN_ADD_WEB_HTML_SIMULATION_EDITPOKEMONMOVES_HTML="web/html/simulation/editpokemonmoves.html";
public static final String REN_ADD_WEB_HTML_SIMULATION_EDITPOKEMONTRAINER_HTML="web/html/simulation/editpokemontrainer.html";
public static final String REN_ADD_WEB_HTML_SIMULATION_EDITPOKEMON_HTML="web/html/simulation/editpokemon.html";
public static final String REN_ADD_WEB_HTML_SIMULATION_SELECTABILITY_HTML="web/html/simulation/selectability.html";
public static final String REN_ADD_WEB_HTML_SIMULATION_SELECTITEM_HTML="web/html/simulation/selectitem.html";
public static final String REN_ADD_WEB_HTML_SIMULATION_SELECTPOKEMON_HTML="web/html/simulation/selectpokemon.html";
public static final String REN_ADD_WEB_HTML_SIMULATION_SIMULATIONLEVEL_HTML="web/html/simulation/simulationlevel.html";
public static final String REN_ADD_WEB_HTML_SIMULATION_SIMULATION_HTML="web/html/simulation/simulation.html";
public static final String REN_ADD_WEB_HTML_SOLUTION_SOLUTION_HTML="web/html/solution/solution.html";
public static final String REN_ADD_WEB_HTML_INDEX_HTML="web/html/index.html";
public static final String REN_ADD_WEB_HTML_STATUS_DATA_HTML="web/html/status/data.html";
public static final String REN_ADD_WEB_HTML_STATUS_STATUS_HTML="web/html/status/status.html";
public static final String REN_ADD_WEB_MESSAGES="web/messages";
public static final String REN_ADD_WEB_PK_CSS_POKEMON_CSS="web_pk/css/pokemon.css";
public static final String REN_ADD_WEB_PK_HTML_POKEMON_HTML="web_pk/html/pokemon.html";
public static final String REN_ADD_WEB_PK_MESSAGES="web_pk/messages";
public static final String REN_ADD_WEB_PROG_CSS_DIFFICULTY_CSS="web_prog/css/difficulty.css";
public static final String REN_ADD_WEB_PROG_HTML_GAMEPROG_HTML="web_prog/html/gameprog.html";
public static final String REN_ADD_WEB_PROG_HTML_GAMEPROGALL_HTML="web_prog/html/gameprogall.html";
public static final String REN_ADD_WEB_PROG_HTML_GAMEPROGNOTATALL_HTML="web_prog/html/gameprognotatall.html";
public static final String REN_ADD_WEB_PROG_HTML_GAMEPROGPART_HTML="web_prog/html/gameprogpart.html";
public static final String REN_ADD_WEB_PROG_MESSAGES="web_prog/messages";
public static final String WEB_FIGHT_HTML_FIGHTER_HTML="web_fight/html/fighter.html";
public static final String WEB_FIGHT_HTML_TEAM_HTML="web_fight/html/team.html";
public static final String WEB_FIGHT_HTML_FIGHT_HTML="web_fight/html/fight.html";
public static final String WEB_FIGHT_HTML_FIGHTDETAIL_HTML = "web_fight/html/fightdetail.html";
public static final String WEB_GAME_HTML_DIFFICULTY_HTML="web_game/html/difficulty.html";
public static final String DIFF_COMMON_HTML = "diff_common.html";

    private PkScriptPages() {
    }
    public static void initAnaData(NatDualConfigurationContext _d){
        StringMap<String> properties_ = new StringMap<String>(new CollCapacity(89));
        properties_.addEntry(MSG_POKEDEX,POKEMON_POKEDEX);
        properties_.addEntry(MSG_PKDATA,POKEMON_DATA);
        properties_.addEntry(MSG_EVOLEVEL,POKEMON_EVOLUTIONS_EVOLEVEL);
        properties_.addEntry(MSG_EVOLEVELGENDER,POKEMON_EVOLUTIONS_EVOLEVELGENDER);
        properties_.addEntry(MSG_EVOHAPPINESS,POKEMON_EVOLUTIONS_EVOHAPPINESS);
        properties_.addEntry(MSG_EVOMOVE,POKEMON_EVOLUTIONS_EVOMOVE);
        properties_.addEntry(MSG_EVOITEM,POKEMON_EVOLUTIONS_EVOITEM);
        properties_.addEntry(MSG_EVOSTONE,POKEMON_EVOLUTIONS_EVOSTONE);
        properties_.addEntry(MSG_EVOSTONEGENDER,POKEMON_EVOLUTIONS_EVOSTONEGENDER);
        properties_.addEntry(MSG_EVOTEAM,POKEMON_EVOLUTIONS_EVOTEAM);
        properties_.addEntry(MSG_EVOTYPE,POKEMON_EVOLUTIONS_EVOTYPE);
        properties_.addEntry(MSG_MOVES,MOVES_MOVES);
        properties_.addEntry(MSG_MOVEDATA,MOVES_DATA);
        properties_.addEntry(MSG_EFF,MOVES_EFFECTS_EFF);
        properties_.addEntry(MSG_EFFDAMAGE,MOVES_EFFECTS_EFFDAMAGE);
        properties_.addEntry(MSG_EFFDAMAGERATE,MOVES_EFFECTS_EFFDAMAGERATE);
        properties_.addEntry(MSG_EFFSTATIS,MOVES_EFFECTS_EFFSTATIS);
        properties_.addEntry(MSG_EFFSTATUS,MOVES_EFFECTS_EFFSTATUS);
        properties_.addEntry(MSG_EFFTEAM,MOVES_EFFECTS_EFFTEAM);
        properties_.addEntry(MSG_EFFGLOBAL,MOVES_EFFECTS_EFFGLOBAL);
        properties_.addEntry(MSG_EFFENDROUND,MOVES_EFFECTS_EFFENDROUND);
        properties_.addEntry(MSG_EFFTEAMWHILESENDINGFOE,MOVES_EFFECTS_EFFTEAMWHILESENDINGFOE);
        properties_.addEntry(MSG_EFFCOPYMOVE,MOVES_EFFECTS_EFFCOPYMOVE);
        properties_.addEntry(MSG_EFFFULLHPRATE,MOVES_EFFECTS_EFFFULLHPRATE);
        properties_.addEntry(MSG_EFFINVOKE,MOVES_EFFECTS_EFFINVOKE);
        properties_.addEntry(MSG_EFFSWITCHMOVETYPES,MOVES_EFFECTS_EFFSWITCHMOVESTYPES);
        properties_.addEntry(MSG_EFFCOUNTERATTACK,MOVES_EFFECTS_EFFCOUNTERATTACK);
        properties_.addEntry(MSG_EFFPROTECTION,MOVES_EFFECTS_EFFPROTECTION);
        properties_.addEntry(MSG_EFFACCURACY,MOVES_EFFECTS_EFFACCURACY);
        properties_.addEntry(MSG_EFFCOPYFIGHTER,MOVES_EFFECTS_EFFCOPYFIGHTER);
        properties_.addEntry(MSG_EFFPROTECTFROMTYPES,MOVES_EFFECTS_EFFPROTECTFROMTYPES);
        properties_.addEntry(MSG_EFFUNPROTECTFROMTYPES,MOVES_EFFECTS_EFFUNPROTECTFROMTYPES);
        properties_.addEntry(MSG_EFFALLY,MOVES_EFFECTS_EFFALLY);
        properties_.addEntry(MSG_EFFBATONPASS,MOVES_EFFECTS_EFFBATONPASS);
        properties_.addEntry(MSG_EFFCLONE,MOVES_EFFECTS_EFFCLONE);
        properties_.addEntry(MSG_EFFCOMMONSTATISTICS,MOVES_EFFECTS_EFFCOMMONSTATISTICS);
        properties_.addEntry(MSG_EFFORDER,MOVES_EFFECTS_EFFORDER);
        properties_.addEntry(MSG_EFFRESTRICTION,MOVES_EFFECTS_EFFRESTRICTION);
        properties_.addEntry(MSG_EFFSWITCHABILITIES,MOVES_EFFECTS_EFFSWITCHABILITIES);
        properties_.addEntry(MSG_EFFSWITCHITEMS,MOVES_EFFECTS_EFFSWITCHITEMS);
        properties_.addEntry(MSG_EFFSWITCHTYPES,MOVES_EFFECTS_EFFSWITCHTYPES);
        properties_.addEntry(MSG_EFFSWITCHPOINTVIEW,MOVES_EFFECTS_EFFSWITCHPOINTVIEW);
        properties_.addEntry(MSG_EFFREMAINEDHPRATE,MOVES_EFFECTS_EFFREMAINEDHPRATE);
        properties_.addEntry(MSG_EFFMULTUSEDMOVEPOWER,MOVES_EFFECTS_EFFMULTUSEDMOVEPOWER);
        properties_.addEntry(MSG_EFFMULTSUFFEREDMOVEPOWER,MOVES_EFFECTS_EFFMULTSUFFEREDMOVEPOWER);
        properties_.addEntry(MSG_EFFSWITCHPOSITION,MOVES_EFFECTS_EFFSWITCHPOSITION);
        properties_.addEntry(MSG_EFFVARPP,MOVES_EFFECTS_EFFVARPP);
        properties_.addEntry(MSG_EFFWINMONEY,MOVES_EFFECTS_EFFWINMONEY);
        properties_.addEntry(MSG_EFF_SENDING,SENDING_EFFSENDING);
        properties_.addEntry(MSG_ITEMS,ITEMS_ITEMS);
        properties_.addEntry(MSG_ITEM,ITEMS_ITEM);
        properties_.addEntry(MSG_BALL,ITEMS_BALL);
        properties_.addEntry(MSG_BERRY,ITEMS_BERRY);
        properties_.addEntry(MSG_BOOST,ITEMS_BOOST);
        properties_.addEntry(MSG_EVO_ITEM,ITEMS_EVOITEM);
        properties_.addEntry(MSG_EVO_STONE,ITEMS_EVOSTONE);
        properties_.addEntry(MSG_FOSSIL,ITEMS_FOSSIL);
        properties_.addEntry(MSG_HEALINGHP,ITEMS_HEALINGHP);
        properties_.addEntry(MSG_HEALINGHPSTATUS,ITEMS_HEALINGHPSTATUS);
        properties_.addEntry(MSG_HEALINGITEM,ITEMS_HEALINGITEM);
        properties_.addEntry(MSG_HEALINGPP,ITEMS_HEALINGPP);
        properties_.addEntry(MSG_HEALINGSTATUS,ITEMS_HEALINGSTATUS);
        properties_.addEntry(MSG_ITEMFORBATTLE,ITEMS_ITEMFORBATTLE);
        properties_.addEntry(MSG_REPEL,ITEMS_REPEL);
        properties_.addEntry(MSG_ABILITIES,ABILITY_ABILITIES);
        properties_.addEntry(MSG_ABILITY,ABILITY_ABILITY);
        properties_.addEntry(MSG_STATUS,STATUS_STATUS);
        properties_.addEntry(MSG_STATUSSET,STATUS_STATUSSET);
        properties_.addEntry(MSG_ENDROUND,ENDROUND_ENDROUND);
        properties_.addEntry(MSG_INDIVIDUAL,ENDROUND_INDIVIDUAL);
        properties_.addEntry(MSG_EVENT,ENDROUND_EVENT);
        properties_.addEntry(MSG_STATUSEND,ENDROUND_STATUS);
        properties_.addEntry(MSG_STATUSRELATION,ENDROUND_STATUSRELATION);
        properties_.addEntry(MSG_SINGLERELATION,ENDROUND_SINGLERELATION);
        properties_.addEntry(MSG_FOE,ENDROUND_FOE);
        properties_.addEntry(MSG_TEAM,ENDROUND_TEAM);
        properties_.addEntry(MSG_MULTIRELATION,ENDROUND_MULTIRELATION);
        properties_.addEntry(MSG_POSITIONRELATION,ENDROUND_POSITIONRELATION);
        properties_.addEntry(MSG_POSITIONTARGET,ENDROUND_POSITIONTARGET);
        properties_.addEntry(MSG_COMBO,COMBO_COMBO);
        properties_.addEntry(MSG_HELPROUND,ROUND_ROUND);
        properties_.addEntry(MSG_LEVELMAP,MAP_LEVEL);
        properties_.addEntry(MSG_POKEMON_NPC,MAP_POKEMON_KEY);
        properties_.addEntry(MSG_INDEX,INDEX);
        properties_.addEntry(MSG_SOLUTION,SOLUTION_SOLUTION);
        properties_.addEntry(MSG_SIMULATION,SIMULATION_SIMULATION);
        properties_.addEntry(MSG_LEVELSIMU,SIMULATION_LEVELSIMU);
        properties_.addEntry(MSG_GENERALHELP,GENERAL_GENERAL);
        properties_.addEntry(MSG_LANG,LANGS_LANGS);
        properties_.addEntry(MSG_DIFFICULTY,DIFFICULTY);
        _d.setProperties(properties_);
        _d.setMessagesFolder(REN_ADD_WEB_MESSAGES);
        StringList added_ = new StringList(new CollCapacity(118));
        added_.add(REN_ADD_WEB_CSS_ABILITIES_CSS);
//        added_.add(REN_ADD_WEB_CSS_ATTAQUES_CSS);
//        added_.add(REN_ADD_WEB_CSS_CAPACITES_CSS);
        added_.add(REN_ADD_WEB_CSS_ITEMS_CSS);
        added_.add(REN_ADD_WEB_CSS_MOVES_CSS);
//        added_.add(REN_ADD_WEB_CSS_OBJETS_CSS);
        added_.add(REN_ADD_WEB_CSS_POKEDEX_CSS);
        added_.add(REN_ADD_WEB_CSS_SIMULATION_CSS);
//        added_.add(REN_ADD_WEB_CSS_STATUTS_CSS);
//        added_.add(REN_ADD_WEB_HTML_ABILITY_ABILITIES_HTML);
//        added_.add(REN_ADD_WEB_HTML_ABILITY_ABILITY_HTML);
//        added_.add(AikiBeansAbilitiesStd.WEB_HTML_ABILITY_DATA_HTML);
//        added_.add(REN_ADD_WEB_HTML_COMBO_COMBO_HTML);
//        added_.add(REN_ADD_WEB_HTML_COMBO_COMBOS_HTML);
//        added_.add(AikiBeansEndroundStd.PAGE_EFF);
//        added_.add(AikiBeansEndroundStd.PAGE_END_ROUND);
//        added_.add(AikiBeansEndroundStd.PAGE_FOE);
//        added_.add(AikiBeansEndroundStd.PAGE_GLOBAL);
//        added_.add(AikiBeansEndroundStd.PAGE_INDIVIDUAL);
//        added_.add(AikiBeansEndroundStd.PAGE_MULTIRELATION);
//        added_.add(AikiBeansEndroundStd.PAGE_POSITIONRELATION);
//        added_.add(AikiBeansEndroundStd.PAGE_POSITIONTARGET);
//        added_.add(AikiBeansEndroundStd.PAGE_SINGLERELATION);
//        added_.add(AikiBeansEndroundStd.PAGE_STATUS);
//        added_.add(AikiBeansEndroundStd.PAGE_STATUSRELATION);
//        added_.add(AikiBeansEndroundStd.PAGE_TEAM);
//        added_.add(REN_ADD_WEB_HTML_GENERAL_GENERAL_HTML);
//        added_.add(REN_ADD_WEB_HTML_ITEMS_BALL_HTML);
//        added_.add(REN_ADD_WEB_HTML_ITEMS_BERRY_HTML);
//        added_.add(REN_ADD_WEB_HTML_ITEMS_BOOST_HTML);
//        added_.add(REN_ADD_WEB_HTML_ITEMS_EVO_ITEM_HTML);
//        added_.add(REN_ADD_WEB_HTML_ITEMS_EVO_STONE_HTML);
//        added_.add(REN_ADD_WEB_HTML_ITEMS_FOSSIL_HTML);
//        added_.add(REN_ADD_WEB_HTML_ITEMS_HEALINGHP_HTML);
//        added_.add(REN_ADD_WEB_HTML_ITEMS_HEALINGHPSTATUS_HTML);
//        added_.add(REN_ADD_WEB_HTML_ITEMS_HEALINGITEM_HTML);
//        added_.add(REN_ADD_WEB_HTML_ITEMS_HEALINGPP_HTML);
//        added_.add(REN_ADD_WEB_HTML_ITEMS_HEALINGSTATUS_HTML);
//        added_.add(REN_ADD_WEB_HTML_ITEMS_ITEM_HTML);
//        added_.add(REN_ADD_WEB_HTML_ITEMS_ITEMFORBATTLE_HTML);
//        added_.add(REN_ADD_WEB_HTML_ITEMS_ITEMS_HTML);
//        added_.add(REN_ADD_WEB_HTML_ITEMS_REPEL_HTML);
//        added_.add(REN_ADD_WEB_HTML_ITEMS_SELLINGITEM_HTML);
//        added_.add(REN_ADD_WEB_HTML_LANGS_LANGS_HTML);
//        added_.add(REN_ADD_WEB_HTML_MAP_ELEMENTS_ALLY_HTML);
//        added_.add(REN_ADD_WEB_HTML_MAP_ELEMENTS_AREA_HTML);
//        added_.add(REN_ADD_WEB_HTML_MAP_ELEMENTS_DEALER_HTML);
//        added_.add(REN_ADD_WEB_HTML_MAP_ELEMENTS_DUAL_FIGHT_HTML);
//        added_.add(REN_ADD_WEB_HTML_MAP_ELEMENTS_LEG_PK_HTML);
//        added_.add(REN_ADD_WEB_HTML_MAP_ELEMENTS_POKEMON_TEAM_HTML);
//        added_.add(REN_ADD_WEB_HTML_MAP_ELEMENTS_SELLER_HTML);
//        added_.add(REN_ADD_WEB_HTML_MAP_ELEMENTS_TRAINER_MULTI_FIGHT_HTML);
//        added_.add(REN_ADD_WEB_HTML_MAP_ELEMENTS_TRAINER_ONE_FIGHT_HTML);
//        added_.add(REN_ADD_WEB_HTML_MAP_LEVEL_HTML);
//        added_.add(REN_ADD_WEB_HTML_MAP_MAP_HTML);
//        added_.add(REN_ADD_WEB_HTML_MOVES_DATA_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFF_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFACCURACY_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFALLY_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFBATONPASS_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFCLONE_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFCOMMONSTATISTICS_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFCOPYFIGHTER_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFCOPYMOVE_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFCOUNTERATTACK_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFDAMAGE_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFDAMAGERATE_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFENDROUND_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFFULLHPRATE_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFGLOBAL_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFINVOKE_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFMULTSUFFEREDMOVEPOWER_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFMULTUSEDMOVEPOWER_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFORDER_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFPROTECTFROMTYPES_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFPROTECTION_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFREMAINEDHPRATE_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFRESTRICTION_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFSTATIS_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFSTATUS_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFSWITCHABILITIES_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFSWITCHITEMS_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFSWITCHMOVETYPES_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFSWITCHPOINTVIEW_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFSWITCHPOSITION_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFSWITCHTYPES_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFTEAM_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFTEAMWHILESENDINGFOE_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFUNPROTECTFROMTYPES_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFVARPP_HTML);
//        added_.add(AikiBeansMovesEffectsStd.WEB_HTML_MOVES_EFFECTS_EFFWINMONEY_HTML);
//        added_.add(AikiBeansMovesStd.WEB_HTML_MOVES_MOVE_LINE_HTML);
//        added_.add(AikiBeansMovesStd.WEB_HTML_MOVES_MOVES_HTML);
//        added_.add(AikiBeansPokemonStd.WEB_HTML_POKEMON_DATA_HTML);
//        added_.add(AikiBeansPokemonStd.WEB_HTML_POKEMON_EVOS_HAPPY);
//        added_.add(AikiBeansPokemonStd.WEB_HTML_POKEMON_EVOS_ITEM);
//        added_.add(AikiBeansPokemonStd.WEB_HTML_POKEMON_EVOS_LEVEL);
//        added_.add(AikiBeansPokemonStd.WEB_HTML_POKEMON_EVOS_LEVELGENDER);
//        added_.add(AikiBeansPokemonStd.WEB_HTML_POKEMON_EVOS_MOVE);
//        added_.add(AikiBeansPokemonStd.WEB_HTML_POKEMON_EVOS_STONE);
//        added_.add(AikiBeansPokemonStd.WEB_HTML_POKEMON_EVOS_STONEGENDER);
//        added_.add(AikiBeansPokemonStd.WEB_HTML_POKEMON_EVOS_TEAM);
//        added_.add(AikiBeansPokemonStd.WEB_HTML_POKEMON_EVOS_TYPE);
//        added_.add(REN_ADD_WEB_HTML_POKEMON_POKEDEX_HTML);
//        added_.add(REN_ADD_WEB_HTML_ROUND_HELPROUND_HTML);
//        added_.add(REN_ADD_WEB_HTML_SENDING_EFFSENDING_HTML);
//        added_.add(REN_ADD_WEB_HTML_SIMULATION_ADDPOKEMON_HTML);
//        added_.add(REN_ADD_WEB_HTML_SIMULATION_EDITPOKEMON_HTML);
//        added_.add(REN_ADD_WEB_HTML_SIMULATION_EDITPOKEMONMOVES_HTML);
//        added_.add(REN_ADD_WEB_HTML_SIMULATION_EDITPOKEMONTRAINER_HTML);
//        added_.add(REN_ADD_WEB_HTML_SIMULATION_SELECTABILITY_HTML);
//        added_.add(REN_ADD_WEB_HTML_SIMULATION_SELECTITEM_HTML);
//        added_.add(REN_ADD_WEB_HTML_SIMULATION_SELECTPOKEMON_HTML);
//        added_.add(REN_ADD_WEB_HTML_SIMULATION_SIMULATION_HTML);
//        added_.add(REN_ADD_WEB_HTML_SIMULATION_SIMULATIONLEVEL_HTML);
//        added_.add(REN_ADD_WEB_HTML_SOLUTION_SOLUTION_HTML);
//        added_.add(AikiBeansStatusStd.WEB_HTML_STATUS_DATA_HTML);
//        added_.add(REN_ADD_WEB_HTML_STATUS_STATUS_HTML);
        _d.setAddedFiles(added_);
//        StringList rend_ = new StringList(new CollCapacity(109));
//        rend_.add(REN_ADD_WEB_HTML_ABILITY_ABILITIES_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ABILITY_ABILITY_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ABILITY_DATA_HTML);
//        rend_.add(REN_ADD_WEB_HTML_COMBO_COMBO_HTML);
//        rend_.add(REN_ADD_WEB_HTML_COMBO_COMBOS_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ENDROUND_EFF_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ENDROUND_ENDROUND_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ENDROUND_FOE_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ENDROUND_GLOBAL_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ENDROUND_INDIVIDUAL_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ENDROUND_MULTIRELATION_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ENDROUND_POSITIONRELATION_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ENDROUND_POSITIONTARGET_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ENDROUND_SINGLERELATION_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ENDROUND_STATUS_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ENDROUND_STATUSRELATION_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ENDROUND_TEAM_HTML);
//        rend_.add(REN_ADD_WEB_HTML_GENERAL_GENERAL_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ITEMS_BALL_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ITEMS_BERRY_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ITEMS_BOOST_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ITEMS_EVO_ITEM_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ITEMS_EVO_STONE_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ITEMS_FOSSIL_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ITEMS_HEALINGHP_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ITEMS_HEALINGHPSTATUS_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ITEMS_HEALINGITEM_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ITEMS_HEALINGPP_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ITEMS_HEALINGSTATUS_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ITEMS_ITEM_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ITEMS_ITEMFORBATTLE_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ITEMS_ITEMS_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ITEMS_REPEL_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ITEMS_SELLINGITEM_HTML);
//        rend_.add(REN_ADD_WEB_HTML_LANGS_LANGS_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MAP_ELEMENTS_ALLY_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MAP_ELEMENTS_AREA_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MAP_ELEMENTS_DEALER_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MAP_ELEMENTS_DUAL_FIGHT_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MAP_ELEMENTS_LEG_PK_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MAP_ELEMENTS_POKEMON_TEAM_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MAP_ELEMENTS_SELLER_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MAP_ELEMENTS_TRAINER_MULTI_FIGHT_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MAP_ELEMENTS_TRAINER_ONE_FIGHT_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MAP_LEVEL_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MAP_MAP_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_DATA_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFF_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFACCURACY_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFALLY_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFBATONPASS_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFCLONE_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFCOMMONSTATISTICS_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFCOPYFIGHTER_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFCOPYMOVE_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFCOUNTERATTACK_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFDAMAGE_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFDAMAGERATE_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFENDROUND_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFFULLHPRATE_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFGLOBAL_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFINVOKE_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFMULTSUFFEREDMOVEPOWER_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFMULTUSEDMOVEPOWER_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFORDER_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFPROTECTFROMTYPES_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFPROTECTION_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFREMAINEDHPRATE_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFRESTRICTION_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFSTATIS_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFSTATUS_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFSWITCHABILITIES_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFSWITCHITEMS_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFSWITCHMOVETYPES_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFSWITCHPOINTVIEW_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFSWITCHPOSITION_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFSWITCHTYPES_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFTEAM_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFTEAMWHILESENDINGFOE_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFUNPROTECTFROMTYPES_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFVARPP_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_EFFECTS_EFFWINMONEY_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_MOVELINE_HTML);
//        rend_.add(REN_ADD_WEB_HTML_MOVES_MOVES_HTML);
//        rend_.add(REN_ADD_WEB_HTML_POKEMON_DATA_HTML);
//        rend_.add(REN_ADD_WEB_HTML_POKEMON_EVOLUTIONS_EVOHAPPY_HTML);
//        rend_.add(REN_ADD_WEB_HTML_POKEMON_EVOLUTIONS_EVOITEM_HTML);
//        rend_.add(REN_ADD_WEB_HTML_POKEMON_EVOLUTIONS_EVOLEVEL_HTML);
//        rend_.add(REN_ADD_WEB_HTML_POKEMON_EVOLUTIONS_EVOLEVELGENDER_HTML);
//        rend_.add(REN_ADD_WEB_HTML_POKEMON_EVOLUTIONS_EVOMOVE_HTML);
//        rend_.add(REN_ADD_WEB_HTML_POKEMON_EVOLUTIONS_EVOSTONE_HTML);
//        rend_.add(REN_ADD_WEB_HTML_POKEMON_EVOLUTIONS_EVOSTONEGENDER_HTML);
//        rend_.add(REN_ADD_WEB_HTML_POKEMON_EVOLUTIONS_EVOTEAM_HTML);
//        rend_.add(REN_ADD_WEB_HTML_POKEMON_EVOLUTIONS_EVOTYPE_HTML);
//        rend_.add(REN_ADD_WEB_HTML_POKEMON_POKEDEX_HTML);
//        rend_.add(REN_ADD_WEB_HTML_ROUND_HELPROUND_HTML);
//        rend_.add(REN_ADD_WEB_HTML_SENDING_EFFSENDING_HTML);
//        rend_.add(REN_ADD_WEB_HTML_SIMULATION_ADDPOKEMON_HTML);
//        rend_.add(REN_ADD_WEB_HTML_SIMULATION_EDITPOKEMON_HTML);
//        rend_.add(REN_ADD_WEB_HTML_SIMULATION_EDITPOKEMONMOVES_HTML);
//        rend_.add(REN_ADD_WEB_HTML_SIMULATION_EDITPOKEMONTRAINER_HTML);
//        rend_.add(REN_ADD_WEB_HTML_SIMULATION_SELECTABILITY_HTML);
//        rend_.add(REN_ADD_WEB_HTML_SIMULATION_SELECTITEM_HTML);
//        rend_.add(REN_ADD_WEB_HTML_SIMULATION_SELECTPOKEMON_HTML);
//        rend_.add(REN_ADD_WEB_HTML_SIMULATION_SIMULATION_HTML);
//        rend_.add(REN_ADD_WEB_HTML_SIMULATION_SIMULATIONLEVEL_HTML);
//        rend_.add(REN_ADD_WEB_HTML_SOLUTION_SOLUTION_HTML);
//        rend_.add(REN_ADD_WEB_HTML_STATUS_DATA_HTML);
//        rend_.add(REN_ADD_WEB_HTML_STATUS_STATUS_HTML);
//        _d.setRenderFiles(rend_);
    }
    public static void initAnaFight(NatDualConfigurationContext _d){
        StringMap<String> properties_ = new StringMap<String>(new CollCapacity(3));
        properties_.addEntry(MSG_FIGHTER,FIGHTER);
        properties_.addEntry(MSG_FIGHT,FIGHT);
        properties_.addEntry(MSG_TEAM,TEAM);
        _d.setProperties(properties_);
        _d.setMessagesFolder(REN_ADD_WEB_FIGHT_MESSAGES);
        StringList added_ = new StringList(new CollCapacity(4));
        added_.add(REN_ADD_WEB_FIGHT_CSS_FIGHT_CSS);
//        added_.add(AikiBeansFightStd.WEB_FIGHT_HTML_FIGHTDETAIL_HTML);
//        added_.add(AikiBeansFightStd.WEB_FIGHT_HTML_FIGHTER_HTML);
//        added_.add(AikiBeansFightStd.WEB_FIGHT_HTML_TEAM_HTML);
        _d.setAddedFiles(added_);
//        StringList rend_ = new StringList(new CollCapacity(3));
//        rend_.add(AikiBeansFightStd.WEB_FIGHT_HTML_FIGHTDETAIL_HTML);
//        rend_.add(AikiBeansFightStd.WEB_FIGHT_HTML_FIGHTER_HTML);
//        rend_.add(AikiBeansFightStd.WEB_FIGHT_HTML_TEAM_HTML);
//        _d.setRenderFiles(rend_);
    }
    public static void initAnaDiff(NatDualConfigurationContext _d){
        StringMap<String> properties_ = new StringMap<String>(new CollCapacity(1));
        properties_.addEntry(MSG_DIFFICULTY,DIFFICULTY);
        _d.setProperties(properties_);
        _d.setMessagesFolder(REN_ADD_WEB_GAME_MESSAGES);
        StringList added_ = new StringList(new CollCapacity(1));
        added_.add(REN_ADD_WEB_GAME_CSS_DIFFICULTY_CSS);
        _d.setAddedFiles(added_);
    }
    public static void initAnaDetPk(NatDualConfigurationContext _d){
        StringMap<String> properties_ = new StringMap<String>(new CollCapacity(1));
        properties_.addEntry(MSG_POKEMON,POKEMON);
        _d.setProperties(properties_);
        _d.setMessagesFolder(REN_ADD_WEB_PK_MESSAGES);
        StringList added_ = new StringList(new CollCapacity(1));
        added_.add(REN_ADD_WEB_PK_CSS_POKEMON_CSS);
        _d.setAddedFiles(added_);
    }
    public static void initAnaProg(NatDualConfigurationContext _d){
        StringMap<String> properties_ = new StringMap<String>(new CollCapacity(1));
        properties_.addEntry(MSG_PROG,GAMEPROG);
        _d.setProperties(properties_);
        _d.setMessagesFolder(REN_ADD_WEB_PROG_MESSAGES);
        StringList added_ = new StringList(new CollCapacity(4));
        added_.add(REN_ADD_WEB_PROG_CSS_DIFFICULTY_CSS);
//        added_.add(REN_ADD_WEB_PROG_HTML_GAMEPROGALL_HTML);
//        added_.add(REN_ADD_WEB_PROG_HTML_GAMEPROGNOTATALL_HTML);
//        added_.add(REN_ADD_WEB_PROG_HTML_GAMEPROGPART_HTML);
        _d.setAddedFiles(added_);
//        StringList rend_ = new StringList(new CollCapacity(3));
//        rend_.add(REN_ADD_WEB_PROG_HTML_GAMEPROGALL_HTML);
//        rend_.add(REN_ADD_WEB_PROG_HTML_GAMEPROGNOTATALL_HTML);
//        rend_.add(REN_ADD_WEB_PROG_HTML_GAMEPROGPART_HTML);
//        _d.setRenderFiles(rend_);
    }
}
