package aiki.sml.trs;
import code.util.*;
import aiki.sml.init.CstIgame;
public final class Cst3 extends CstIgame {
private static final String SEP = "\t";
private Cst3(){}
static StringMap<String> cs(){
StringMap<String> f = new StringMap<String>(new CollCapacity(9));
f.addEntry("1",I_COUPE);
f.addEntry("2",I_ENVOL);
f.addEntry("3",I_SURF);
f.addEntry("4",I_FORCE);
f.addEntry("5",I_SIPHON);
f.addEntry("6",I_ECLATE_ROC);
f.addEntry("7",I_CASCADE);
f.addEntry("8",I_ESCALADE);
f.addEntry("9",I_PLONGEE);
return f;
}
static StringMap<String> ct(){
StringMap<String> f = new StringMap<String>(new CollCapacity(100));
f.addEntry("1",I_AIGUISAGE+SEP+R_1);
f.addEntry("2",I_DRACOGRIFFE+SEP+R_1);
f.addEntry("3",I_CHOC_PSY+SEP+R_1);
f.addEntry("4",I_PLENITUDE+SEP+R_1);
f.addEntry("5",I_HURLEMENT+SEP+R_1);
f.addEntry("6",I_TOXIK+SEP+R_1);
f.addEntry("7",I_GRELE+SEP+R_1);
f.addEntry("8",I_GONFLETTE+SEP+R_1);
f.addEntry("9",I_CHOC_VENIN+SEP+R_1);
f.addEntry("10",I_PUIS_CACHEE+SEP+R_1);
f.addEntry("11",I_ZENITH+SEP+R_1);
f.addEntry("12",I_PROVOC+SEP+R_1);
f.addEntry("13",I_LASER_GLACE+SEP+R_1);
f.addEntry("14",I_BLIZZARD+SEP+R_1);
f.addEntry("15",I_ULTRALASER+SEP+R_1);
f.addEntry("17",I_ABRI+SEP+R_1);
f.addEntry("16",I_MUR_LUMIERE+SEP+R_1);
f.addEntry("19",I_ATTERRISSAGE+SEP+R_1);
f.addEntry("18",I_DANSE_PLUIE+SEP+R_1);
f.addEntry("21",I_FRUSTRATION+SEP+R_1);
f.addEntry("20",I_RUNE_PROTECT+SEP+R_1);
f.addEntry("23",I_ANTI_AIR+SEP+R_1);
f.addEntry("22",I_LANCE_SOLEIL+SEP+R_1);
f.addEntry("25",I_FATAL_FOUDRE+SEP+R_1);
f.addEntry("24",I_TONNERRE+SEP+R_1);
f.addEntry("27",I_RETOUR+SEP+R_1);
f.addEntry("26",I_SEISME+SEP+R_1);
f.addEntry("29",I_PSYKO+SEP+R_1);
f.addEntry("28",I_TUNNEL+SEP+R_1);
f.addEntry("31",I_CASSE_BRIQUE+SEP+R_1);
f.addEntry("30",I_BALL_OMBRE+SEP+R_1);
f.addEntry("34",I_CRADOVAGUE+SEP+R_1);
f.addEntry("35",I_LANCE_FLAMME+SEP+R_1);
f.addEntry("32",I_REFLET+SEP+R_1);
f.addEntry("33",I_PROTECTION+SEP+R_1);
f.addEntry("38",I_DEFLAGRATION+SEP+R_1);
f.addEntry("39",I_TOMBEROCHE+SEP+R_1);
f.addEntry("36",I_BOMB_BEURK+SEP+R_1);
f.addEntry("37",I_TEMPETESABLE+SEP+R_1);
f.addEntry("42",I_FACADE+SEP+R_1);
f.addEntry("43",I_NITROCHARGE+SEP+R_1);
f.addEntry("40",I_AEROPIQUE+SEP+R_1);
f.addEntry("41",I_TOURMENTE+SEP+R_1);
f.addEntry("46",I_LARCIN+SEP+R_1);
f.addEntry("47",I_BALAYETTE+SEP+R_1);
f.addEntry("44",I_REPOS+SEP+R_1);
f.addEntry("45",I_ATTRACTION+SEP+R_1);
f.addEntry("51",I_AILE_D_ACIER+SEP+R_1);
f.addEntry("50",I_SURCHAUFFE+SEP+R_1);
f.addEntry("49",I_ECHO+SEP+R_1);
f.addEntry("48",I_CHANT_CANON+SEP+R_1);
f.addEntry("55",I_EBULLITION+SEP+R_1);
f.addEntry("54",I_FAUX_CHAGE+SEP+R_1);
f.addEntry("53",I_ECO_SPHERE+SEP+R_1);
f.addEntry("52",I_EXPLOFORCE+SEP+R_1);
f.addEntry("59",I_CALCINATION+SEP+R_1);
f.addEntry("58",I_CHUTE_LIBRE+SEP+R_1);
f.addEntry("57",I_RAYON_CHARGE+SEP+R_1);
f.addEntry("56",I_DEGOMMAGE+SEP+R_1);
f.addEntry("63",I_EMBARGO+SEP+R_1);
f.addEntry("62",I_ACROBATIE+SEP+R_1);
f.addEntry("61",I_FEU_FOLLET+SEP+R_1);
f.addEntry("60",I_A_LA_QUEUE+SEP+R_1);
f.addEntry("68",I_GIGA_IMPACT+SEP+R_1);
f.addEntry("69",I_POLIROCHE+SEP+R_1);
f.addEntry("70",I_FLASH+SEP+R_1);
f.addEntry("71",I_LAME_DE_ROC+SEP+R_1);
f.addEntry("64",I_EXPLOSION+SEP+R_1);
f.addEntry("65",I_GRIFFE_OMBRE+SEP+R_1);
f.addEntry("66",I_REPRESAILLES+SEP+R_1);
f.addEntry("67",I_VENGEANCE+SEP+R_1);
f.addEntry("76",I_SURVINSECTE+SEP+R_1);
f.addEntry("77",I_BOOST+SEP+R_1);
f.addEntry("78",I_PIETISOL+SEP+R_1);
f.addEntry("79",I_SOUFFLE_GLACE+SEP+R_1);
f.addEntry("72",I_CHANGE_ECLAIR+SEP+R_1);
f.addEntry("73",I_CAGE_ECLAIR+SEP+R_1);
f.addEntry("74",I_GYROBALLE+SEP+R_1);
f.addEntry("75",I_DANSE_LAMES+SEP+R_1);
f.addEntry("85",I_DEVOREVE+SEP+R_1);
f.addEntry("84",I_DIRECT_TOXIK+SEP+R_1);
f.addEntry("87",I_VANTARDISE+SEP+R_1);
f.addEntry("86",I_NOEUD_HERBE+SEP+R_1);
f.addEntry("81",I_PLAIE_CROIX+SEP+R_1);
f.addEntry("80",I_EBOULEMENT+SEP+R_1);
f.addEntry("83",I_HARCELEMENT+SEP+R_1);
f.addEntry("82",I_DRACO_QUEUE+SEP+R_1);
f.addEntry("93",I_ECLAIR_FOU+SEP+R_1);
f.addEntry("92",I_DISTORSION+SEP+R_1);
f.addEntry("95",I_ABOIEMENT+SEP+R_1);
f.addEntry("94",I_ECLATE_ROC+SEP+R_1);
f.addEntry("89",I_DEMI_TOUR+SEP+R_1);
f.addEntry("88",I_BLABLA_DODO+SEP+R_1);
f.addEntry("91",I_LUMINOCANON+SEP+R_1);
f.addEntry("90",I_CLONAGE+SEP+R_1);
f.addEntry("100",I_CONFIDENCE+SEP+R_1);
f.addEntry("98",I_POING_BOOST+SEP+R_1);
f.addEntry("99",I_ECLAT_MAGIQUE+SEP+R_1);
f.addEntry("96",I_FORCE_NATURE+SEP+R_1);
f.addEntry("97",I_VIBROBSCUR+SEP+R_1);
return f;
}
}
