package aiki.sml.trs;
public final class Trs25{
private static final String F_FC_DIV="div";
private static final String F_FC_PUIS="puis";
private static final String F_FC_QUOT="quot";
private static final String F_FC_MOD="mod";
private static final String F_FC_MODTAUX="modtaux";
private static final String F_FC_ABS="abs";
private static final String F_FC_ENT="ent";
private static final String F_FC_TAUX="taux";
private static final String F_FC_TRONCATURE="troncature";
private static final String F_FC_NUM="num";
private static final String F_FC_DEN="den";
private static final String F_FC_MIN="min";
private static final String F_FC_MAX="max";
private static final String F_FC_MOY="moy";
private static final String F_FC_VAR="var";
private static final String F_FC_CARACFERME="caracferme";
private static final String F_FC_CARACOUVERT="caracouvert";
private static final String F_FC_CARACSEMIOUVERTG="caracsemiouvertg";
private static final String F_FC_CARACSEMIOUVERTD="caracsemiouvertd";
private static final String F_FC_CARACGAUCHEOUVERT="caracgaucheouvert";
private static final String F_FC_CARACDROITEOUVERT="caracdroiteouvert";
private static final String F_FC_CARACGAUCHEFERME="caracgaucheferme";
private static final String F_FC_CARACDROITEFERME="caracdroiteferme";
private static final String F_FC_SGN="sgn";
private static final String F_FC_CARDINAL="cardinal";
private static final String F_FC_INTER="inter";
private static final String F_FC_UNION="union";
private static final String F_FC_COMPLEMENTAIRE="complementaire";
private static final String F_FC_INCLUSNUM="inclusnum";
private static final String F_FC_NONINCLUSNUM="noninclusnum";
private static final String F_FC_EGALNUM="egalnum";
private static final String F_FC_DIFFERENTNUM="differentnum";
private static final String F_FC_VIDE="vide";
private Trs25(){}
static String tr(){
String f=F_FC_DIV+"\tDivision\n";
f+=F_FC_PUIS+"\tPuissance\n";
f+=F_FC_QUOT+"\tQuotient de la division euclidienne\n";
f+=F_FC_MOD+"\tReste de la division euclidienne\n";
f+=F_FC_MODTAUX+"\tReste de la division\n";
f+=F_FC_ABS+"\tValeur absolue\n";
f+=F_FC_ENT+"\tPartie enti&egrave;re\n";
f+=F_FC_TAUX+"\tNombre rationnel\n";
f+=F_FC_TRONCATURE+"\tTroncature de\n";
f+=F_FC_NUM+"\tNum&eacute;rateur\n";
f+=F_FC_DEN+"\tD&eacute;nominateur\n";
f+=F_FC_MIN+"\tMinimum\n";
f+=F_FC_MAX+"\tMaximum\n";
f+=F_FC_MOY+"\tMoyenne\n";
f+=F_FC_VAR+"\tVariance\n";
f+=F_FC_CARACFERME+"\tCaract&eacute;ristique du ferm&eacute;\n";
f+=F_FC_CARACOUVERT+"\tCaract&eacute;ristique de l'ouvert\n";
f+=F_FC_CARACSEMIOUVERTG+"\tCaract&eacute;ristique de l'intervalle semi ouvert &agrave; gauche\n";
f+=F_FC_CARACSEMIOUVERTD+"\tCaract&eacute;ristique de l'intervalle semi ouvert &agrave; droite\n";
f+=F_FC_CARACGAUCHEOUVERT+"\tCaract&eacute;ristique de l'intervalle ouvert &agrave; gauche\n";
f+=F_FC_CARACDROITEOUVERT+"\tCaract&eacute;ristique de l'intervalle ouvert &agrave; droite\n";
f+=F_FC_CARACGAUCHEFERME+"\tCaract&eacute;ristique de l'intervalle &agrave; gauche ferm&eacute;\n";
f+=F_FC_CARACDROITEFERME+"\tCaract&eacute;ristique de l'intervalle &agrave; droite ferm&eacute;\n";
f+=F_FC_SGN+"\tSigne\n";
f+=F_FC_CARDINAL+"\tNombre d'&eacute;l&eacute;ments\n";
f+=F_FC_INTER+"\tIntersection\n";
f+=F_FC_UNION+"\tUnion\n";
f+=F_FC_COMPLEMENTAIRE+"\tCompl&eacute;mentaire de\n";
f+=F_FC_INCLUSNUM+"\tInclusion num&eacute;rique\n";
f+=F_FC_NONINCLUSNUM+"\tNon inclusion num&eacute;rique\n";
f+=F_FC_EGALNUM+"\tEgalit&eacute; num&eacute;rique\n";
f+=F_FC_DIFFERENTNUM+"\tDiff&eacute;rence num&eacute;rique\n";
f+=F_FC_VIDE+"\tEnsemble vide\n";
return f;
}
}
